### ISSUE TITLE
The LES "showcase buurtbatterij - overzicht" stopped working

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1010]
When I try to open the LES _showcase buurtbatterij - overzicht_ https://moses.energytransitionmodel.com/testing_grounds/471 it doesn't work any more and I get the following screen: 

![mega error](https://cloud.githubusercontent.com/assets/17741822/15574180/44557580-234c-11e6-8984-c8c14e92a08b.PNG)

**Comment by antw** [comment]
Fixed that for you. A number was entered as `2,5` when the application requires `2.5`.

**Comment by ChaelKruip** [comment]
@antw can you have a look please?

**Comment by antw** [comment]
Will close this since the LES is now working. #1009 has a more detailed description of the problem and solution.

@Sanne512 If this happens again, you might be able to fix it by adding "/edit" to the end of the address and changing the value to use the correct format, and then saving the LES.

For example:

* For https://moses.energytransitionmodel.com/testing_grounds/471, visit https://moses.energytransitionmodel.com/testing_grounds/471/edit
