### ISSUE TITLE
Now there's gas, but no tab 'gas load' anymore?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1024]
https://moses.energytransitionmodel.com/testing_grounds/427

![image](https://cloud.githubusercontent.com/assets/104830/15743732/d0740aec-28c7-11e6-8ce8-5b57a1a7f0cb.png)

**Comment by ChaelKruip** [comment]
Assigning @grdw

**Comment by dennisschoenmakers** [comment]
The reverse is also true:

No gas technologies, but now we *do* have a gas tab...

![image](https://cloud.githubusercontent.com/assets/104830/15744562/f71bc860-28cc-11e6-8d0e-7b618cd69fed.png)

**Comment by antw** [comment]
The "Gas load" tab shows when you have gas *assets* (connectors or pipes) installed. If you have no gas assets, there's not much point in showing the tab.

**Comment by antw** [comment]
> Well, in LES 427 there is non-zero gas load being calculated. How can that be?

It has a hybrid heat pump, which has a gas component. The "Gas load" tab does not show because as an older LES it does not have an associated `GasAssetList` record, which describes the pipes and connectors installed at each pressure level.

Maybe we should still show the "Gas load" page, even though the load would be identical at each pressure level.

**Comment by ChaelKruip** [comment]
> Well, in LES 427 there is non-zero gas load being calculated. How can that be?

You have gas-technologies but no gas infrastructure. LESses created before the gas-asset list, don't have pipes and connectors and, therefore, no gas load charts.

**Comment by antw** [comment]
> Hmm, this would be possible with no extra changes in the current code?

To be honest, I'm not sure. The gas network defaults to infinite capacity and 1.0 efficiency at each level, but I'll need to test it.

However, some time ago I added[a message](https://github.com/quintel/etmoses/blob/35671936b822730a1f57da7c579854f457a1114f/app/views/testing_grounds/gas_load.html.haml#L23-L27) to be shown if a user accidentally visits the gas load page with no assets. This was because the gas charts were typically blank, and not of much use. I can look into it...
