### ISSUE TITLE
Red dots are not consisent:

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1026]
Only when I click it, it becomes red:

### Right one is not red

![image](https://cloud.githubusercontent.com/assets/104830/15744285/5b1087f4-28cb-11e6-958d-04a8c589248c.png)

### I click it: yes, it is red

![image](https://cloud.githubusercontent.com/assets/104830/15744297/6bf0543c-28cb-11e6-8298-3a61be8133d9.png)

**Comment by ChaelKruip** [comment]
Assigning @grdw as I recall he has pushed something fixing the colouring of nodes recently.

**Comment by ChaelKruip** [comment]
I open [the LES](https://moses.energytransitionmodel.com/testing_grounds/480) and only the second end-node is red:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/15746583/776ac49e-28d7-11e6-8afd-6a66c950ca5d.png)
Selecting the third end-node and all of a sudden it also turns red:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/15746616/94f6e4a2-28d7-11e6-8ff3-f23463a9a575.png)

They should both be red to begin with.

**Comment by antw** [comment]
Is this not because we initially retrieve only the load for the selected node? (insert something about being a poet here).

**Comment by grdw** [comment]
> Is this not because we initially retrieve only the load for the selected node? (insert something about being a poet here).

Thanks for being sharp here. The way ETMoses currently draws the loads is the following:

1. Fetch the topology
2. Draw the topology
3. If and only if you already selected a node for that LES (so in @ChaelKruip's case node 2). It only fetches the loads for that node.
4. Set the capacity color.

**Comment by ChaelKruip** [comment]
> Is this not because we initially retrieve only the load for the selected node?

But... does that mean that you'd have to click every node in the topology in order to see if it is congested?! 😧  That's new and not very desirable.

When it comes to plotting the curves, I agree that it probably is fine to only request data that you actually need. But the network should show the problem nodes from the get-go IMO. 

Perhaps a way to get best of both worlds is to mark each node 'red' or 'blue' on the server so the congestion status can be shown on the topology even though the curves are not plotted yet.

**Comment by grdw** [comment]
> But... does that mean that you'd have to click every node in the topology in order to see if it is congested?!

You can also look at it in that fashion. But when it comes to very large LES's it's actually desirable to only fetch a certain subset of nodes.

> Perhaps a way to get best of both worlds is to mark each node 'red' or 'blue' on the server so the congestion status can be shown on the topology even though the curves are not plotted yet.

Hmm,, that would suggest that you already calculated the LES fully? But than again you probably already did when you see this bug.

**Comment by antw** [comment]
> Perhaps a way to get best of both worlds is to mark each node 'red' or 'blue' on the server so the congestion status can be shown on the topology even though the curves are not plotted yet.

I think this is non-trivial. If caching is enabled (staging and production), we'd need to extend the caching system to store whether load exceeds capacity on each node. If caching isn't enabled (development), this probably triggers another calculation of the network.

A quick-fix might be to request the loads for all nodes in the topology (instead of only those clicked on by the visitor). It's not ideal, especially for large LESes, but it's probably the best that can be done on a short timescale.

**Comment by ChaelKruip** [comment]
> But when it comes to very large LES's it's actually desirable to only fetch a certain subset of nodes.

It may be desirable to fetch only the *data* for a subset of nodes but the status of those nodes should be apparent at first glance.

> that would suggest that you already calculated the LES fully?

Not necessarily. Only the current week could also give you a 'status' for the topology.

**Comment by ChaelKruip** [comment]
> I think this is non-trivial. 

I'll take your word on that!

> A quick-fix might be to request the loads for all nodes in the topology (instead of only those clicked on by the visitor). It's not ideal, especially for large LESes, but it's probably the best that can be done on a short timescale.

Sounds good. Especially the 'quick' part 😉
