### ISSUE TITLE
How are we going to translate the 'availability' for EV batteries to ETMoses?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#106]
In ETM-pro you can specify how much of the EV battery you can use for storage. But how can we translate that number to something in ETLoader? That would require us to change the profiles for EV right?

**Comment by jorisberkhout** [comment]
Changing milestone to 'Deploy January 2016'.

**Comment by jorisberkhout** [comment]
As discussed with @ChaelKruip .

This issue points to a fundamental difference between ETModel and ETMoses. The 'availability' slider for EV in the ETM is used to set a statistical property of all EV in the scenario, namely which percentage of all batteries combined can be used for flexibility purposes (storing excess electricity and using this electricity at a later time). In ETMoses, each EV has its own charging / load profiles that determine when the EV needs to be charged to have enough electricity in the 'tank' to do the next scheduled trip. By applying one of the relevant strategies, the remaining capacity of the battery can be used for flexibility purposes.

To cut a long story short, the answer to the question in this issue is: we're **not** going to translate the availability sliders setting to ETMoses. Closing this issue.
