### ISSUE TITLE
Stacked and individual load curves don't show negative load (on LIVE)

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1063]
In [this LES](https://moses.energytransitionmodel.com/testing_grounds/482), the total load looks like this:
<img width="650" alt="etmoses" src="https://cloud.githubusercontent.com/assets/1303760/15991687/bd098388-30ba-11e6-931c-d4568e9868b2.png">
But the individual loads don't show the negative production:
<img width="610" alt="etmoses" src="https://cloud.githubusercontent.com/assets/1303760/15991699/f225e7aa-30ba-11e6-80f3-92aa11253744.png">
and neither does the stacked loads:
<img width="595" alt="etmoses" src="https://cloud.githubusercontent.com/assets/1303760/15991702/097b746a-30bb-11e6-9d56-c8ac6615b68d.png">

**Comment by grdw** [comment]
To tell you what I'm seeing:

Total:
<img width="589" alt="screen shot 2016-06-15 at 12 14 32" src="https://cloud.githubusercontent.com/assets/2676542/16076279/d3bd6998-32f2-11e6-9554-5d748bb247fe.png">

Technologies I used:
<img width="574" alt="screen shot 2016-06-15 at 12 14 40" src="https://cloud.githubusercontent.com/assets/2676542/16076280/d3bedde6-32f2-11e6-9d8d-21d9893f5a22.png">

Stacked:
<img width="581" alt="screen shot 2016-06-15 at 12 14 49" src="https://cloud.githubusercontent.com/assets/2676542/16076282/d3c10c38-32f2-11e6-8b5d-6a5796ad76d8.png">

Individual:
<img width="582" alt="screen shot 2016-06-15 at 12 14 58" src="https://cloud.githubusercontent.com/assets/2676542/16076281/d3bff82a-32f2-11e6-8b58-4a55ddc2aac0.png">

The thing is that as my console proofs:
<img width="1069" alt="screen shot 2016-06-15 at 12 16 11" src="https://cloud.githubusercontent.com/assets/2676542/16076320/0128b266-32f3-11e6-83cd-6da2ca33a0a3.png">

All loads for Solar Panel all 0 for individual and stacked.

**Comment by grdw** [comment]
After some digging it looks as though there's no production being held into account for the `SubPath`'s.

However, the `PullConsumption` [here](https://github.com/quintel/etmoses/blob/master/app/models/calculation/pull_consumption.rb#L44) - does log some values (which look okay) for the load of the solar panels. The thing is that I don't quiet get how these values are passed on to the `tech_loads` ....

**Comment by antw** [comment]
FWIW I know about this, and it has always been this way; it's not a new bug. It's not a front-end or chart issue, but rather a limitation of the network calculation itself. I have some rough ideas – but nothing firm yet – for how to fix it.

Fundamentally, the problem is that the model is driven by consumption, not production. We can't account for production the same way we do consumption; during the calculation production is actually "*potential* production" (e.g. includes the energy which *might* be discharged from storage).

**Comment by ChaelKruip** [comment]
> I have some rough ideas – but nothing firm yet – for how to fix it.

I would like to hear your ideas about this @antw. Let's pick this up with priority. 

> during the calculation production is actually "potential production"

But afterwards there must be a way to know what every technology did right?

**Comment by antw** [comment]
> I would like to hear your ideas about this @antw.

I need to think this through some more and experiment a bit, because calling them "ideas" might still be optimistic. I'll make this my first priority next week.

> But afterwards there must be a way to know what every technology did right?

You can query a technology to find out what it's (net) load was, and that would work fine if we wanted only to show the load of technologies on endpoints. However, the need to show tech loads on non-endpoints means that this isn't sufficient. If a technology has a load of -2kW (2kW production), how much of that was used in the endpoint, and how much made it to the parent node?

When we compute consumption, technologies don't see that there's 2kW of production available from technology *a*, 3kW from technology *b*, and 1kW from *c*; they see that there is 6kW available in total. If a consumer wants 3kW, the calculator says "there is 6kW available, here's your 3!". What it does not do is say "have 2kW from producer *a*, and 1kW from *b*".

**Comment by ChaelKruip** [comment]
> I'll make this my first priority next week.

👍 

> You can query a technology to find out what it's (net) load was, and that would work fine if we wanted only to show the load of technologies on endpoints. However, the need to show tech loads on non-endpoints means that this isn't sufficient. If a technology has a load of -2kW (2kW production), how much of that was used in the endpoint, and how much made it to the parent node?

> When we compute consumption, technologies don't see that there's 2kW of production available from technology a, 3kW from technology b, and 1kW from c; they see that there is 6kW available in total. If a consumer wants 3kW, the calculator says "there is 6kW available, here's your 3!". What it does not do is say "have 2kW from producer a, and 1kW from b".

Thanks for clarifying that! I was indeed still thinking about the end-points only...

**Comment by ThomBuijs** [comment]
@Sanne512

**Comment by ChaelKruip** [comment]
> @Sanne512

@ThomBuijs what do you mean by this? Are you including @Sanne512 in the discussion? If so, please state so explicitly. If you would like to (co-)assign @Sanne512 you can do that using the Assignees drop-down menu right of this page.

**Comment by ThomBuijs** [comment]
I meant to include her. My apologies for the inconvenience.

**Comment by ChaelKruip** [comment]
> I meant to include her. My apologies for the inconvenience.

No problem! 👍

**Comment by Sanne512** [comment]
I'm including @MarjoleinSchwachofer

**Comment by ChaelKruip** [comment]
From https://github.com/quintel/etmoses/issues/1325: 

> I just wondered wether the gas production would be added to the stacked gas chart. Beacuse PV is already an item in the electricty chart, it just doesn't show correctly. But P2G is not an item in the gas stacked chart yet. Will this be added in your improvements in #1063, because it isn't explicitly stated there?

So, let's not forget about P2G.

**Comment by ChaelKruip** [comment]
This has been fixed on BETA and will be pushed to LIVE at the next deploy. Closing.
