### ISSUE TITLE
Naming of load should be made consistent

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1067]
"Load" => "Electricity load"
<img width="1243" alt="etmoses" src="https://cloud.githubusercontent.com/assets/1303760/15993418/fae75312-30e5-11e6-9ad1-834148cfd8ea.png">

**Comment by antw** [comment]
I'm not sure I agree with calling either of these "Electricity load".

The one on the top-left might be better as "Network", but that tab describes more than just "*Electricity* load". Perhaps "Gas load" might become "Gas infrastructure"?

The instance on the right makes little sense as "Electricity load", since the chart also includes gas and heat.

**Comment by ChaelKruip** [comment]
> I'm not sure I agree with calling either of these "Electricity load".

Excellent points @antw!

> Perhaps "Gas load" might become "Gas infrastructure"?

I like that!
