### ISSUE TITLE
ETModel rounds some parameters (P2G) when exporting to ETMoses. Should be floats instead of integers

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1094]
It seems to me that when exporting my ETM scenario to ETMoses something goes wrong with rounding some parameters.

This issue came up when I changed my P2G from 0.8 to 0.133 (to represent ~ 0.1 MW) .
After the change the technology P2G was no longer present. 
In the 0.8 case the technology was overrepresented as one full plant.

![image](https://cloud.githubusercontent.com/assets/19907658/16119826/80f5985c-33dd-11e6-8726-1751b656442d.png)

I think the same goes for other " supply" parameters.

I can get around this for now by overrepresenting my P2G in ETM and downscaling in ETMoses (by adjusting the technology). But I think this issue will come up often when people want to implement similar technologies to their small-scale scenario's.

@grdw @ChaelKruip

@antw ?
 @DorinevanderVlies

**Comment by ChaelKruip** [comment]
Thinking about this a bit better, I've realised that this is a feature instead of a bug :)

If we would use floats, the number of units of technologies cannot be represented in the technology matrix. Perhaps in the future we can improve this (by installing a certain capacity instead of a number of units). Closing for now.
