### ISSUE TITLE
[Airbrake] [Staging] Missing use profile for Heat pump for space heating (air)

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1114]
**Airbrake error:** [#3540](https://quintel.airbrake.io/projects/111227/groups/1712340572991633540)
**Airbrake project:** ETMoses

**Error type:** `RuntimeError`
**Error message:** `` Missing use profile for Heat pump for space heating (air) ``
**Where:** `testing_grounds#data`
**Occurred at:** Jun 20, 2016 13:53:44 UTC
**First seen at:** Jun 20, 2016 13:53:44 UTC
**Occurrences:** 1 (1 since last deploy on Jun 20, 2016 12:43:47 UTC)

**URL:** [https://beta-moses.energytransitionmodel.com/testing_grounds/233/data.json](https://beta-moses.energytransitionmodel.com/testing_grounds/233/data.json)
**File:** `[PROJECT_ROOT]/app/models/network/technologies/legacy_buffer.rb`

**Backtrace:**
```
[PROJECT_ROOT]/app/models/network/technologies/legacy_buffer.rb:6:in build
[PROJECT_ROOT]/app/models/network/technologies/heat_pump.rb:10:in build
[PROJECT_ROOT]/app/models/network/technologies.rb:11:in from_installed
[PROJECT_ROOT]/app/models/calculation/technology_load.rb:67:in create_tech
```

**Comment by antw** [comment]
Old LES using old-style heat pumps; maybe the time has come to get rid of this and the LegacyBuffer class? However there are about 20 LESes on production using this feature (all from 2015), so we'd have to migrate them to use shared demand profiles/buffers. That's doable, but of course the loads will change on account of using different profiles.

We can't keep what we have for long, because the technology form for these standalone heat-pumps is all wrong:

![screen shot 2016-06-20 at 16 02 31](https://cloud.githubusercontent.com/assets/4383/16199181/84398084-3700-11e6-99b8-6afd9c545696.png)

**Comment by ChaelKruip** [comment]
> Old LES using old-style heat pumps; maybe the time has come to get rid of this and the LegacyBuffer class? However there are about 20 LESes on production using this feature (all from 2015)

Can you post the titles and authors here @antw? We can ask @Sanne512 and @JeroenvdLogt if we need to keep supporting these LESes or not. Removing them would have my preference.

**Comment by antw** [comment]
> Can you post the titles and authors here @antw?

I believe some are private. I'll get a list of IDs, titles, and authors and put them into the Moses Slack channel.

There will be some on beta also, but as beta is for testing *new* features... 😈

**Comment by Sanne512** [comment]
> Can you post the titles and authors here @antw?<

When you post the concerned LESses here @JeroenvdLogt and I will let you know if we're still using this. 

> I believe some are private.<

Can you retrieve these or do you need input from @JeroenvdLogt to locate these?

**Comment by antw** [comment]
Thanks @Sanne512. These are the LESes which belong to you and Jeroen:

| LES | Creation Date |
|-----|:-------------:|
| First trial oefencase Goor - units in topology - [LES-336](https://moses.energytransitionmodel.com/testing_grounds/336) | 2015-10-13 10:19:48 UTC |
| First trial oefencase Goor - units in topology - [LES-337](https://moses.energytransitionmodel.com/testing_grounds/337) | 2015-10-13 13:30:19 UTC |
| units topology fresh test - [LES-338](https://moses.energytransitionmodel.com/testing_grounds/338) | 2015-10-13 13:46:21 UTC |
| oefening vrijdag 13-10-2015 opslag netbeheerder - [LES-339](https://moses.energytransitionmodel.com/testing_grounds/339) | 2015-10-13 14:01:16 UTC |
| Oefencase Etten-Leur SSU - [LES-341](https://moses.energytransitionmodel.com/testing_grounds/341) | 2015-10-15 10:18:10 UTC |
| Ben en Ben uitleg - [LES-359](https://moses.energytransitionmodel.com/testing_grounds/359) | 2015-11-19 10:00:20 UTC |
| USEF: doorrekening Lochem 2025 referentie - [LES-361](https://moses.energytransitionmodel.com/testing_grounds/361) | 2015-11-27 11:11:42 UTC |

If you're okay with these being removed, it won't be immediate but will likely happen in the next couple of days. We'll also retain a backup, just-in-case.

**Comment by Sanne512** [comment]
@JeroenvdLogt and I are still using the the last LES in the table: 

> USEF: doorrekening Lochem 2025 referentie - LES-361	2015-11-27 11:11:42 UTC<

What do we need to change in this LES so it will be supported again?

**Comment by antw** [comment]
The LES contains the following technologies:

* Heat pump for space heating (air)
* Heat pump for space heating (ground)
* Heat pump for hot water (air)

If we were to remove support for the old-style heat pumps, you would have to remove those, add "Buffer space heating" and "Buffer water heating" technologies, and add new heat pumps.

To save you the effort, I created a copy of your LES with the change already made: [USEF: doorrekening Lochem 2025 referentie (with heat profiles)](https://moses.energytransitionmodel.com/testing_grounds/488). The demands will be different because it no longer models the load of only heat pumps for space heating and hot water, but tries to use the heat pumps to meet *all* demand for space heating and hot water.

When you have time, would you mind taking a look at that to see what you think? Of course, we will not delete any old scenarios without your approval.

You can create your own copy of that LES by choosing "Edit LES", "General", and "Save as a new Local Energy Solution".

--

In case you want to try it for yourself, here's what I did:

1. Add a "Buffer space heating" and "Buffer water heating" to each endpoint

  <img width="433" alt="screen shot 2016-06-21 at 12 21 30" src="https://cloud.githubusercontent.com/assets/4383/16227781/badc3f14-37aa-11e6-8ae7-d704f5eaf08a.png">

2. Add new heat pumps to these buffers (they will appear with a grey background underneath the buffer):

  <img width="456" alt="screen shot 2016-06-21 at 12 22 12" src="https://cloud.githubusercontent.com/assets/4383/16227789/cf7f3124-37aa-11e6-8207-722bbc907406.png">

  ... and set their attributes (particularly number of units) to match the old heat pumps.

3. Delete the old heat pumps (which will have a white background):

  <img width="1145" alt="screen shot 2016-06-21 at 12 23 46" src="https://cloud.githubusercontent.com/assets/4383/16227822/07d7252c-37ab-11e6-9fb0-d4f109664d36.png">

I suggest creating a copy of your LES before you start: click on "Edit LES", then "General", and "Save as new Local Energy Solution". Make your changes to the new LES, and this will keep the original intact.

**Comment by Sanne512** [comment]
@ChaelKruip Is this issue still relevant?

**Comment by ChaelKruip** [comment]
> @ChaelKruip Is this issue still relevant?

That depends: Have you and @JeroenvdLogt made the suggested copies of the LESses using buffers? If so, we can close this.

**Comment by Sanne512** [comment]
Yes, we have so i'm closing the issue.

**Comment by antw** [comment]
I'll reopen this because I still need to remove the old LESes and profiles, and get rid of the old heat pump code.
