### ISSUE TITLE
Will not download electricity storage curve

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1127]
In the following LES https://moses.energytransitionmodel.com/testing_grounds/471 when I try to download the electricity storage curve at the node Buurtbatterij I get an error: 
![bug electricity storage curve](https://cloud.githubusercontent.com/assets/17741822/16294755/db0cba06-3922-11e6-8be5-960c2fb8168a.PNG)

The steps I took: 

1. Opening the LES
2. Clicking the node Buurtbatterij
3. Switching the view to whole year (which I still do by first clicking another week than the first week of January and then whole year, because if I click whole year directly I get an error) 
4. Clicking options --> Electricity storage curves

**Comment by Sanne512** [comment]
The same happens in this LES:

https://moses.energytransitionmodel.com/testing_grounds/476  

I was wondering what the status is? Because I need this option for a report that's due next week. If it's not possible to fix this before then, I would also like to know, because if that's the case I need to figure out something else for the report.

**Comment by ChaelKruip** [comment]
@antw can you give us an indication of how much time this would take to fix?

**Comment by antw** [comment]
I have fixed the neighbourhood battery not appearing in the CSV.

We have to compute the network from scratch to create the storage CSV since the cached copy doesn't contain enough information. This is why it sometimes takes a long time for the file to download, and sometimes results the error shown above.

@Sanne512 If you are still unable to download the CSV files, please let me know which ones you want and for which LESes, and I'll make sure we get a copy to you ASAP.

**Comment by Sanne512** [comment]
> @Sanne512 If you are still unable to download the CSV files, please let me know which ones you want and for which LESes, and I'll make sure we get a copy to you ASAP.

I was able to download the ones I need. Thanks!
