### ISSUE TITLE
Same input different outcome

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1130]
I have created a LES with five different scenarios: https://moses.energytransitionmodel.com/testing_grounds/471 and recreated each scenario in a single LES. When I compare the electricity load graph at the MSR of the fourth scenario: the strand MSR 4 in the LES buurtbatterij - overzicht with the electricity load graph in the LES buurtbatterij - buurtbatterij  https://moses.energytransitionmodel.com/testing_grounds/476 I get a different outcome, even though the input is the same. The two electricity load graphs: 

![bug overzicht msr4 load graph](https://cloud.githubusercontent.com/assets/17741822/16298063/c318e332-3933-11e6-8e80-dcaedc8102de.PNG)

LES buurtbatterij - overzicht

![bug buurtbatterij msr load graph](https://cloud.githubusercontent.com/assets/17741822/16298111/ffb23942-3933-11e6-8725-b95419785fe6.PNG)

LES buurtbatterij - buurtbatterij

I've checked the input for the topology and the technology table in the two LESses and they are exactly the same. In both LESses I've only checked the strategy "Storage in batteries prioritising local PV production". I don't understand why I get a different result.

**Comment by ChaelKruip** [comment]
Assigning @antw.

**Comment by antw** [comment]
I looked into this at the time the issue was created, and I think the two scenarios were not identical. The neighbourhood battery in one of the LESes had a COP assigned (COP is not supported on the battery) among other differences. Today, the two give identical results:

| Showcase buurtbatterij - overzicht | Showcase buurtbatterij - buurtbatterij |
| --- | --- |
| <img width="578" alt="screen shot 2016-06-29 at 15 57 25" src="https://cloud.githubusercontent.com/assets/4383/16454782/5d05c702-3e12-11e6-9e88-446e3fa63793.png"> | <img width="575" alt="screen shot 2016-06-29 at 15 57 37" src="https://cloud.githubusercontent.com/assets/4383/16454790/61d5027a-3e12-11e6-9d7d-6e5345e19477.png"> |
