### ISSUE TITLE
Different outcome when same load is assigned to different node

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1153]
### Problem
I have four scenario's. 
All of them have the same technologies and same total amount of capacity/units. The only thing that varies is how the capacities/units are divided among the nodes.
The problem is that the outcome of the scenario's is different. 

### Question
Is this something I can fix (by defining my technology profile differently?) or is it a bug?

###  The four LES's
Straight topology [LES 558](https://beta-moses.energytransitionmodel.com/testing_grounds/558).
Ameland topology, all load on node "Hollum dorp" [ LES 561](https://beta-moses.energytransitionmodel.com/testing_grounds/561).
Ameland topology, all load on node "Hollum omgeving" [LES 562](https://beta-moses.energytransitionmodel.com/testing_grounds/562).
Ameland topology, load divided realistically among nodes [LES 563](https://beta-moses.energytransitionmodel.com/testing_grounds/563).

### Outcome of the scenario's
A check I performed is whether the top node (high voltage) gives the same result for all scenario's. As the total load and production is the same this should be the case.

For scenario straight topology ([LES 558](https://beta-moses.energytransitionmodel.com/testing_grounds/558)) and all load on Hollum dorp ([LES 561](https://beta-moses.energytransitionmodel.com/testing_grounds/561)) the curve of the High voltage node is indeed (optically) the same.
The other scenario's however give very different outcomes. The figure below shows the 4 curves of the High voltage node.

![image](https://cloud.githubusercontent.com/assets/19907658/16518063/30c893b6-3f81-11e6-9a6e-947cbe9fe612.png)

@dennisschoenmakers, FYI

**Comment by ChaelKruip** [comment]
> The only thing that varies is how the capacities/units are divided among the nodes.

I have a sneaking suspicion that the observed differences are due to one of two things:

* the aggregation of household base-load profiles. As described in [this part of the documentation](https://github.com/quintel/etmoses/wiki/Base-loads), groups of houses larger than 30 households only use aggregated (EDSN) profiles. 562 and 563 seem to use EDSN profiles (just from looking at the images) while the 558 and 561 seem to use individual profiles.
* the concurrency setting for base-load. Can you check if the concurrency setting is the same for all LESses?

**Comment by DorinevanderVlies** [comment]
I figured out that in this case the problem occurs when I add the electric heaters.
I put two technology profile CSV files in a gist. One with all load and one without the electric heating.

[Gist with technology profiles](https://gist.github.com/DorinevanderVlies/e82365f4a8b0e8566a63a4a76ea517fb)


@dennisschoenmakers FYI

**Comment by antw** [comment]
I'm not sure what the issue is here. I tried both CSVs and the results look as I would expect. When there are electric heaters the electricity load is higher, and gas load is consequently lower.

In both cases, the heat demand is satisfied, but using different technologies:

| With electric heater | Without electric heater |
| --- | --- |
| ![screen shot 2016-07-04 at 14 45 18](https://cloud.githubusercontent.com/assets/4383/16562670/05af286c-41f6-11e6-8f32-fc2ab72b06f3.png) ![screen shot 2016-07-04 at 14 46 19](https://cloud.githubusercontent.com/assets/4383/16562689/1d5c3090-41f6-11e6-84f5-57d3c64780a5.png) | ![screen shot 2016-07-04 at 14 45 22](https://cloud.githubusercontent.com/assets/4383/16562676/0bb48694-41f6-11e6-8d71-9207cb71f88f.png) ![screen shot 2016-07-04 at 14 46 55](https://cloud.githubusercontent.com/assets/4383/16562697/2b37a550-41f6-11e6-95b4-d37e6a038b13.png) |

Could someone please clarify?

**Comment by DorinevanderVlies** [comment]
The problem is that the first node does not have the same load as the other nodes. This is unexpected as the technologies assigned to all the nodes are exactly the same.
