### ISSUE TITLE
Not all technologies have default investment and O&M

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1225]
Some technologies have default settings for initial investment, OM costs and technical life.
There are some technologies which don't have this. 

In a [test les](https://beta-moses.energytransitionmodel.com/testing_grounds/596/edit) I added all possible technologies once. A screenshot of (part of) the CSV is shown below.

The following technologies currently do not have default investment, OM costs and technical life.
- congestion battery
- households_water_heater_hybrid_heatpump_air_water_electricity_gas
- households_water_heater_network_gas
- households_water_heater_combined_network_gas
- households_water_heater_hybrid_heatpump_air_water_electricity_electricity
- households_space_heater_hybrid_heatpump_air_water_electricity_gas
- households_space_heater_hybrid_heatpump_air_water_electricity_electricity

Note, the combined heater network gas is a special case as the same investment can be spread over space heating and hot water.

![image](https://cloud.githubusercontent.com/assets/19907658/16654467/3a5ec60a-4456-11e6-80ca-c4a12e4741ca.png)

cc @dennisschoenmakers

**Comment by grdw** [comment]
Most of these technologies have nowhere to draw those values from. This is a bit of scoping problem also. To bore you with a bit of technical details: ETEngine holds the data for certain converters. However most converters you are specifying don't exist in ETEngine, therefor there's no default. 

The only two technologies that strike me as odd are:

````
households_water_heater_network_gas
households_water_heater_combined_network_gas
````

Since they do exist in ETEngine and should therefor present some information about investment, OM costs and technical life. But I'll have to check if these values are specified for those converters.

**Comment by ChaelKruip** [comment]
> But I'll have to check if these values are specified for those converters.

👍

**Comment by ChaelKruip** [comment]
> The only two technologies that strike me as odd are:

The hybrid heat pump also exists in the ETM and should have attributes. We can discuss how to divide those costs over the two components (gas and electricity part).
