### ISSUE TITLE
Question: why doesn't this gas load range code work as it should?

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1273]
I am currently struggling really badly with these [lines](https://github.com/quintel/etmoses/blob/issues/%231266-gas-chart/app/controllers/calculation_controller.rb#L8-L15). 

To explain it as easily as I can, when you select a week which isn't '01 January - 07 January' than all the gas loads reduce to 0.0. The thing is, `gas_network` comes down quiet okay (I see all the loads for any random week). But either the `GasChain` or the `LoadSummary` are doing something vague which makes the loads drop to 0.0. Which one is it, could you maybe point me out a little in the correct direction?

**Comment by antw** [comment]
This is because a load range (`range_start`/`range_end`) is being requested such as `673..1346` and you're were then slicing the load array by that range. However, when calculating weekly loads, the values always start at index 0 regardless of which week is being computed.

i.e. the loads are in the first 673 elements of the array:

```ruby
loads = [1.0, 2.0, 3.0, 4.0, ..., 673.0]
```

... and so, if you slice it like this:

```ruby
loads[673...(673 * 2)]
```

... then you're going to get back nothing of value. :smiley:
