### ISSUE TITLE
Measure flexibility realised in market model doesn't work

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#1275]
In the LES Lunch and Learn - buurtbatterij (https://moses.energytransitionmodel.com/testing_grounds/512/edit) I added the following measure to the market model. 
![bug measure flex realized 20160715](https://cloud.githubusercontent.com/assets/17741822/16867849/8ba149a6-4a74-11e6-875d-62d4407c5d32.PNG)

Flex is being realized by the neighourhood battery at the buurtbatterij node of which the aggregator is the stakeholder: 
![bug measure flex load buurtbatterij 20160715](https://cloud.githubusercontent.com/assets/17741822/16867889/c2033f36-4a74-11e6-87cf-f90fbd5f1006.PNG)

But it is not being calculated in the business case
![bug measure flex business case 20160715](https://cloud.githubusercontent.com/assets/17741822/16867949/1aa60088-4a75-11e6-87e5-9d6131f81f6b.PNG)
:

**Comment by Sanne512** [comment]
I need this for a presentation next week. How long will it take to fix this?

**Comment by ChaelKruip** [comment]
Adding priority label and assigning @antw

**Comment by antw** [comment]
The problem here is the use of "Flexibility realised" on endpoint containing the neighbourhood battery. "Flexibility realised" measures occasions where the absolute load on an endpoint is lower with the strategies turned on (the green curve) than when they are turned off (blue curve).

By "absolute" I mean that if the blue load is 2kW (consumption) and the green load is -2kW (production), then there is no flexibility happening. However if the green load was -1kW, we'd measure that the flexibility at that point-in-time is 1kW, since the green load is 1kW *closer* to 0kW. The documentation does not make this clear; I will update it.

I believe the idea behind "flexibility realised" was to measure the load on endpoints containing households and storage technologies (P2P batteries come to mind), so that a third-party could pay the owner of those endpoints for using their storage instead the network, particularly during periods of congestion.

On your neighbourhood battery node, there is never any flexibility occurring because the green load is always the same – or higher – than the blue load. If you want to pay the aggregator for the energy produced by the neighbourhood battery, you should use the "kWh of electricity produced" measure instead.

<img width="1029" alt="screen shot 2016-07-18 at 09 59 41" src="https://cloud.githubusercontent.com/assets/4383/16910082/643a1864-4cce-11e6-823c-35445306d43c.png">

I will close this because I think it solves your problem. If not, please reopen.

**Comment by ChaelKruip** [comment]
> "Flexibility realised" measures occasions where the absolute load on an endpoint is lower with the strategies turned on (the green curve) than when they are turned off (blue curve).

@antw would it be difficult to change the definition of "Flexibility realised" to:

"The absolute difference between the blue and green curve"?

@Sanne512 would that definition be more aligned with your expectations/needs?

**Comment by antw** [comment]
> @antw would it be difficult to change the definition of "Flexibility realised" to:
> "The absolute difference between the blue and green curve"?

But does this not cause us to measure periods when the green curve load is *higher* than the blue? That's whats happening on the neighbourhood battery node; there's never *flexibility* happening there because the load is always higher with the strategies turned on. However, there *is* flexibility occurring on the parent node:

<img width="565" alt="screen shot 2016-07-18 at 10 16 03" src="https://cloud.githubusercontent.com/assets/4383/16910461/b079888e-4cd0-11e6-9205-d630412c7bcd.png">

Is the suggestion that a blue load of 2kW and green load of -2kW is 4kW of flexibility, and not 0kW? What if the green load is -10kW?

I really feel that what should be measured in this situation is *production* of the battery node, but if you want the flexibility measure changed to something else it shouldn't be too hard to do so.

**Comment by ChaelKruip** [comment]
> But does this not cause us to measure periods when the green curve load is higher than the blue? 

Yes. And I agree that this is probably not what people want to pay for or expect.

> I really feel that what should be measured in this situation is production of the battery node

Me too!

> but if you want the flexibility measure changed to something else it shouldn't be too hard to do so.

I think the current measure is fine. Perhaps we could add the 'absolute difference' measure at some point in the future but for now there is no need.

**Comment by Sanne512** [comment]
> I will close this because I think it solves your problem.

It did! But I'm reopening the issue, because now I have a similar issue with the flex measure for solar capping and I don't understand what's happening. I added the following measure: 

![bug measure flex solar capping](https://cloud.githubusercontent.com/assets/17741822/16911070/afe103e6-4cdc-11e6-92d8-b27d3bef53b3.PNG)

I have the following graph for the load at the "Huishoudens" node: 

![image](https://cloud.githubusercontent.com/assets/17741822/16911125/f37b5106-4cdc-11e6-9ec9-660f5b4d58c5.png)

So I would expect there to be a money flow from the system operator to the customer, but this is not happening. 

![image](https://cloud.githubusercontent.com/assets/17741822/16911167/34c8ee66-4cdd-11e6-8cda-af6b1889e224.png)

What's going on here?
