### ISSUE TITLE
Compressor shouldn't be included automatically

### ISSUE THREAD

**Issue by MarjoleinSchwachofer** [quintel/etmoses#1326]
The compressor in the gas network shouldn't be introduced automatically, since they are not there in real gas networks nowadays and you cannot see the problems with to much feed in. 

You should be able to add it manually if there is to much feed-in and make this clear in the documentation.
 
@Sanne512 @ThomBuijs @JeroenvdLogt FYI

**Comment by MarjoleinSchwachofer** [comment]
Yes. Just made a new LES to check ( beta server) and it again adds compressors:
![image](https://cloud.githubusercontent.com/assets/17849585/17140677/950b3d16-5349-11e6-8de3-1aae43142a19.png)

**Comment by ChaelKruip** [comment]
> Yes. Just made a new LES to check ( beta server) and it again adds compressors:

The compressors are added indeed but with quantity = 0.0 , so they are not taken into account in the calculation or in the business cases. This way of treating them makes it easier for a user to add them by changing the quantity rather than having to add a "compressor line" for each pressure level.

Closing. Please re-open if this does not solve your problem.
