### ISSUE TITLE
Question about deficit in gas flow chart

### ISSUE THREAD

**Issue by MarjoleinSchwachofer** [quintel/etmoses#1332]
Deficit is part of the gas flow chart. In the documentation it states:

> Deficit: if the local production of gas is not sufficient to meet the consumption, gas needs to be sourced from higher pressure levels; if the capacity of the connector is limited, it might happen that not all this gas can be sourced, leading to deficits. For now we assume that the capacity of all connectors is infinite

Question: Is it possible to have a deficit? E.g. if you change the gas demand to a very high value  and the gas asset calculation taked normal average values for the number of pipes. Or is there no capacity defined for the connectors?

If the capacity is infinite, the deficit is always zero and could be left out the chart.

**Comment by ChaelKruip** [comment]
> If the capacity is infinite, the deficit is always zero and could be left out the chart.

You are 100% right. The deficit is there because of historical reasons. @Sanne512 was looking into capacities of gas connectors (from high to low pressure) but in the end concluded that we would better set them to infinite as she could not find the numbers. My reason for keeping them is that one day we might be able to find appropriate capacity values for connectors and this chart will work as expected.

**Comment by ChaelKruip** [comment]
Closing. Please re-open if your question is not satisfactorily answered.
