### ISSUE TITLE
Heat infra page needs some attention

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1338]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/17175653/010d3892-5409-11e6-8fe0-2d96e40a1605.png)

It seems that:
* The page is always marked as 'edited' (yellow bar)
* The "Aggregator" is the default stakeholder (should be "System Operator")

**Comment by MarjoleinSchwachofer** [comment]
Maybe there could be a new stakeholder defined for the heat network? Otherwise it will be the same stakeholders als the system operator for E and G in the business case and currently this are seperate parties. Heat producers currenlty are also sometimes the network operator, but there can also be  split and  a seperate producer and system operator. I suggest the heat system operator. Is it difficult to add this as a new stakeholder?

**Comment by ChaelKruip** [comment]
> I suggest the heat system operator.

👍  I'm making a separate issue for this. We can further discuss the possibility of doing this there.
