### ISSUE TITLE
Setting default storage value to a specified default for Storage technologies

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#134]
@ChaelKruip and I thought it would be nice to do this last week but now a lot of `spec/models/network`-specs are failing.

@antw How can this be achieved in the 'nicest' way?

**Comment by antw** [comment]
I'm not sure why this needs to default to zero. It's an optional attribute, and `nil` and `0.0` don't mean the same thing. `nil` means "this attribute is not relevant to this technology", and `0.0` means "this storage technology stores nothing".

Setting a default value causes the specs fail because InstalledTechnology *expects* irrelevant attributes to be `nil` [when loading profiles](https://github.com/quintel/etloader/blob/493936dace9b7b37630de6d5e0b7b4c8f936df17/app/models/installed_technology.rb#L43-L69); this will change when I deal with #125 (this week).

**Comment by ChaelKruip** [comment]
To clarify: I think it would be nice if the 'storage' attribute would get a default value for storage technologies only. In those cases, we already have values researched. 

BTW: 'volume [kWh]' would perhaps be a better name IMHO. 'Storage' suggests to me that this is a bool indicating if this technology is able to store.

**Comment by antw** [comment]
> I think it would be nice if the 'storage' attribute would get a default value for storage technologies only.

Presumably this value would be non-zero and specific to each technology? If so, this would be better as part of the Technology model so that you could set different defaults on each one.

> BTW: 'volume [kWh]' would perhaps be a better name IMHO. 'Storage' suggests to me that this is a bool indicating if this technology is able to store.

This will happen; I'll see to it tomorrow. :+1:

**Comment by ChaelKruip** [comment]
Can this be closed @antw @grdw ?

**Comment by antw** [comment]
> Can this be closed

Yes.

Volume and capacity are now imported from ETEngine. I don't think there's any need for Moses to define a default.
