### ISSUE TITLE
Batteries not plotted in stacked or individual view of load chart

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1378]
In [this LES](https://beta-moses.energytransitionmodel.com/testing_grounds/700):
![etmoses_](https://cloud.githubusercontent.com/assets/1303760/17740761/07b1c572-649a-11e6-852b-6e12584c79ae.png)
and 
![etmoses_](https://cloud.githubusercontent.com/assets/1303760/17740788/17359b9a-649a-11e6-8fe7-5f19c87eb958.png)

Although I see their effect in the total view:
![etmoses_](https://cloud.githubusercontent.com/assets/1303760/17740818/343b84ac-649a-11e6-96c2-feb88fdbc928.png)

**Comment by antw** [comment]
This looks correct to me. The battery consumption and production happens on the "Rubroek" endpoint node. The charging and discharging would not be visible higher in the network, since the load is contained to the endpoint:

#### Rubroek

![screen shot 2016-08-17 at 16 26 08](https://cloud.githubusercontent.com/assets/4383/17742301/59f64090-6497-11e6-909e-24ef9a444d4a.png)

#### MS-LS Trafo

![screen shot 2016-08-17 at 16 27 37](https://cloud.githubusercontent.com/assets/4383/17742336/875a2998-6497-11e6-8bd5-56cb4b36d715.png)

**Comment by ChaelKruip** [comment]
> This looks correct to me. 

Thanks for convincing me too 👍
