### ISSUE TITLE
How would I expand the network calculation with hybrids?

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#1381]
It's now only able to take `electricity`, `gas` and `heat` as a carrier. The thing I'm having trouble with is that the hybrid consists of two parts, a `gas` part and an `electricity` part but the main `InstalledTechnology` object is a `hybrid` carrier... So I'm a bit clueless. I could fish out the corresponding component for a hybrid technology but than I miss all the investment attributes) of the main hybrid technology.

I'd like some class like:

````ruby
# This is just some poor sketch... 
class Network
  class Technologies
    class Hybrid
      def initialize(hybrid)
        @hybrid = hybrid
      end
      
      def gas_part
        @hybrid.attributes.merge(component_for_carrier(:gas).attributes)      
      end

      def electricity_part
        @hybrid.attributes.merge(component_for_carrier(:electricty).attributes)      
      end

      private

      def component_for_carrier(carrier)
        @hybrid.components.detect do |component|
          component.carrier == carrier
        end
      end
    end
  end
end
````

And than implement it somewhere in the calculation code? But I would have no clue where and how to be honest.

**Comment by antw** [comment]
I'm not sure why you'd want to do this? I thought the idea was that InstalledTechnology would be able to [split *itself* up into the individual components](https://github.com/quintel/etmoses/issues/1368#issuecomment-239768365), that way the `Network` would need almost no changes (after all, the gas and electric components are basically two completely separate technologies inside one box). The pseudo-code above looks more like an InstalledTechnology subclass than a `Network::Technology`.

There would have to be some changes to the network builders ([such as here](https://github.com/quintel/etmoses/blob/705d940d557d3f58a12a1a905f5f67b700b2fb47/app/models/network/builders/electricity.rb#L51), [here](https://github.com/quintel/etmoses/blob/705d940d557d3f58a12a1a905f5f67b700b2fb47/app/models/network/builders/gas.rb#L43), and [here](https://github.com/quintel/etmoses/blob/705d940d557d3f58a12a1a905f5f67b700b2fb47/app/models/network/builders/heat.rb#L66)) so that these components are included in the list of installed technologies. Something like:

```ruby
node.set(:installed_techs, techs.flat_map do do |tech|
  # Get the individual components of each technology:
  tech.components.select { |t| t.carrier == :electricity }
end.compact)

**Comment by antw** [comment]
I should add: by the time you get to the Network::Technologies, it is already too late to deal with different carriers. A technology belongs to the electricity, gas, or heat networks, and has no knowledge that other networks even exist (power-to-gas [is an exception](https://github.com/quintel/etmoses/blob/705d940d557d3f58a12a1a905f5f67b700b2fb47/app/models/network/technologies/siphon.rb#L32-L34), but even that [needs to be told about the gas network](https://github.com/quintel/etmoses/blob/705d940d557d3f58a12a1a905f5f67b700b2fb47/app/models/calculation/technology_load.rb#L34-L38) before the calculation happens).

I think the suggestion of having a hybrid `Network::Technology` which acts on multiple networks isn't possible currently, and likely isn't desirable due to the added complexity.

**Comment by grdw** [comment]
> I'm not sure why you'd want to do this? I thought the idea was that InstalledTechnology would be able to split itself up into the individual components

Hmm, allow me to rephrase the question to; where does that happen in the code currently? I can't seem to find the `each_profile_curve` method being used anywhere except the definition of itself.

> and likely isn't desirable due to the added complexity.

Yes. I get that.

**Comment by antw** [comment]
> I can't seem to find the each_profile_curve method being used anywhere except the definition of itself.

Seems that `each_profile_curve` is no longer used. Instead, [InstalledTechnology#profile_curve](https://github.com/quintel/etmoses/blob/705d940d557d3f58a12a1a905f5f67b700b2fb47/app/models/installed_technology.rb#L101-L103) is called [here](https://github.com/quintel/etmoses/blob/705d940d557d3f58a12a1a905f5f67b700b2fb47/app/models/calculation/technology_load.rb#L49-L60).

**Comment by grdw** [comment]
>  Instead, InstalledTechnology#profile_curve is called here.

Thanks! I think I know how to solve it from here.

**Comment by grdw** [comment]
The idea is now to [decorate](https://github.com/quintel/etmoses/pull/1322/files#diff-20eec9c046de572e74b4d7d6632bbd6cR1) right before calculating. I'm almost there I guess, there are only some attributes missing in the components that are needed from the parent element but that's rather easy from this point.

**Comment by grdw** [comment]
Staging:
![screen shot 2016-08-18 at 15 36 22](https://cloud.githubusercontent.com/assets/2676542/17775674/959d1764-6559-11e6-8d0f-4d888ee1032f.png)

Local:
![screen shot 2016-08-18 at 15 36 27](https://cloud.githubusercontent.com/assets/2676542/17775675/95cbc2b2-6559-11e6-81a5-115f5ec6e8b0.png)

I spot a difference between staging and local? @ChaelKruip do you know what might be going on here? It looks as though the gas part is not doing anything.

**Comment by antw** [comment]
Try enabling the P2H strategy and see if that makes any difference. Perhaps the recent changes with that strategy upset the HHP...

**Comment by grdw** [comment]
With P2H enabled.

Staging:
![screen shot 2016-08-18 at 15 41 41](https://cloud.githubusercontent.com/assets/2676542/17775822/54cfdf9a-655a-11e6-86d1-6c0d0c31c539.png)

Local:
![screen shot 2016-08-18 at 15 41 46](https://cloud.githubusercontent.com/assets/2676542/17775823/54d27d36-655a-11e6-9337-f381ccd65373.png)

**Comment by grdw** [comment]
Ho, nvm. My units were not similar. ...

**Comment by grdw** [comment]
If I however synchronise the units of the buffer (so both 1)

![screen shot 2016-08-18 at 15 44 57](https://cloud.githubusercontent.com/assets/2676542/17775930/c1e81110-655a-11e6-8e28-118938b30490.png)
![screen shot 2016-08-18 at 15 45 02](https://cloud.githubusercontent.com/assets/2676542/17775929/c1e84086-655a-11e6-833e-79767197c046.png)

**Comment by antw** [comment]
You might want to cherry-pick 4bf9e7dd on to your branch; that should ensure it's not CoP/efficiency-related.

**Comment by grdw** [comment]
When cherry-picking your commit (4bf9e7d) it turned from

![screen shot 2016-08-18 at 15 45 02](https://cloud.githubusercontent.com/assets/2676542/17776835/6d665094-655e-11e6-93d7-2cf323d9ca65.png)

to: 

![screen shot 2016-08-18 at 16 11 10](https://cloud.githubusercontent.com/assets/2676542/17776836/6d854616-655e-11e6-98b7-1c3365dff6e3.png)

**Comment by grdw** [comment]
The number are off due to: https://github.com/quintel/etmoses/issues/1382 I do think it's odd that the gas is off on staging but the gas is on locally. Why would that be?

**Comment by antw** [comment]
I looked into this and I believe the (extra) gas consumption is due to #1261. I don't think this pull request is responsible for the problem.

**Comment by grdw** [comment]
Closing continuing the discussion in #1368
