### ISSUE TITLE
The stakeholder cooperation is not in my LES but still in the businessmodel?

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1406]
I'm using this [LES](https://moses.energytransitionmodel.com/testing_grounds/542/business_cases/306) where I have no stakeholder named cooperation. However I still have this stakeholder in my business case and it has a outgoing cashflow which I don't understand. I cannot see the stakeholder in the marketmodel, topology, gas asset lists or the technology table. Can someone have a look at it or explain this to me please?

**Comment by ChaelKruip** [comment]
Looking at the gas asset list in the database, the cooperation is the owner of all gas assets. In the front-end this is not shown however. 

It seems that only stakeholders that are present in the topology file can be selected to own a part of the gas assets. **This is wrong.**
Moreover, the cooperation used to be the default stakeholder for gas assets so perhaps something has gone wrong when we changed that.

Hope this helps @grdw and @antw to fix the problem.

**Comment by antw** [comment]
I've changed the stakeholder for the gas assets to be "system operator" (since I believe that is correct for the live/production application). The cooperation has no longer appears in the business case.

![screen shot 2016-08-31 at 16 09 22](https://cloud.githubusercontent.com/assets/4383/18134157/534d3d6c-6f95-11e6-9332-37347f14c3db.png)

> It seems that only stakeholders that are present in the topology file can be selected to own a part of the gas assets. This is wrong.

This has been fixed on beta. All stakeholders are available to be chosen for gas and heat assets.

![screen shot 2016-08-31 at 16 08 15](https://cloud.githubusercontent.com/assets/4383/18134177/7579ff7e-6f95-11e6-9fa6-5c6c5f9ee89d.png)

@ThomBuijs We plan on publishing a new version to [the "live" site](https://moses.energytransitionmodel.com) some time next week, after which this should no longer be a problem.

**Comment by ThomBuijs** [comment]
I made a new [LES](https://moses.energytransitionmodel.com/testing_grounds/545/business_cases/309) and the cooperation stakeholder is back again. This time its value is zero, but I would rather leave him out of the picture at all. Any ideas on how to solve this?

**Comment by ThomBuijs** [comment]
I forgot to change the stakeholder to system operator.. So I am closing this, since it is fixed now.
