### ISSUE TITLE
Load chart should have more persistence

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#141]
It should remember if you chose a specific:
* week
* time-window
* toggle (show capacity, show storage)

when you select different nodes

**Comment by grdw** [comment]
> - week
> - time-window

This is easy to remember. There is one hurdle though. Whenever someone pushes the 'enable storage' toggle, the chart needs to be refreshed due to changes in the data of the chart, this 'forgets' all the previous week and time-window settings.

**Comment by antw** [comment]
I think @ChaelKruip was looking for the chart to remember the chosen settings *for all nodes*, so that if you select "Jan 1 – Jan 7" on LV1, then choose to view the load chart for LV2, that chart will load showing "Jan 1 – Jan 7" also.

Currently it seems to remember the setting on a per-node basis, but defaults back to the annual view when showing a different node.

--

The request itself is not hard, but I think the front-end JS code is getting to the point that even simple features like this are a pain to implement. We started with a *temporary* load chart and have added more and more stuff on top. I think we should add this persistence, but we're going to have to rewrite the front-end to make it *actually maintainable* before we do anything more ambitious. :disappointed:

**Comment by grdw** [comment]
> I think @ChaelKruip was looking for the chart to remember the chosen settings for all nodes, so that if you select "Jan 1 – Jan 7" on LV1, then choose to view the load chart for LV2, that chart will load showing "Jan 1 – Jan 7" also.

I thought that when you switched back to the same node, your week settings should be memorized.

> but we're going to have to rewrite the front-end to make it actually maintainable

@antw I agree.

**Comment by antw** [comment]
> I thought that when you switched back to the same node, your previous week settings should be memorized.

That's what you implemented – and it works perfectly by the way. I thought the request was that the chosen week should be a global setting, and apply to every chart. Maybe I'm misunderstanding what was requested; @ChaelKruip can you clarify?

**Comment by grdw** [comment]
I talked to @ChaelKruip - he did mean:

> so that if you select "Jan 1 – Jan 7" on LV1, then choose to view the load chart for LV2, that chart will load showing "Jan 1 – Jan 7" also.

I'm going to try to do it. But first, clean-up time!

![broom](http://img2.wikia.nocookie.net/__cb20120111032935/disney/images/5/52/Magic_Broom-Plush.jpg)

**Comment by grdw** [comment]
@ChaelKruip if you could take a look.
