### ISSUE TITLE
Hiding the ETM type under the name attribute in the technologies table

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#142]
Right now the table is a bit to narrow due to the large table headers. Hiding the 'type' column might be a good solution to make it less narrow.

![screen shot 2015-05-20 at 3 00 42 pm](https://cloud.githubusercontent.com/assets/2676542/7726262/068b0834-ff01-11e4-8973-936b42a23f13.png)

**Comment by antw** [comment]
The type is needed if you want to add or change technologies manually (and is very useful for testing new features), but I agree that having separate "Name" and "Type" columns feels redundant.

Perhaps we could drop the separate "name" field, keep the "type", but instead show a nice human-readable name (instead of `transport_car_using_electricity`, etc).

```html
<select name="installed_technology[type]">
  <option value="base_load">Household</option>
  <option value="transport_car_using_electricity">Electric car</option>
  <!-- ... -->
</select>
```

We'd lose the ability to set a custom name on one technology, but I think that's okay. I don't see any testing grounds which use custom names anyway. @ChaelKruip What do you think?

We could also use this as an opportunity to remove the human-readable technology names from the `technologies` table, and put them in a locale file so they may be translated later?

**Comment by ChaelKruip** [comment]
> We'd lose the ability to set a custom name on one technology, but I think that's okay. 

Me too!
I would be happy with just one of the two columns and the custom names are the least useful I agree.

**Comment by grdw** [comment]
I changed the `name` and `profile` attributes into select boxes. :smile: 

Still needs some cleanin-up though.
