### ISSUE TITLE
Allow capacity to be shown in individual and stacked load view as well

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1451]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/18739859/bed14d90-80a6-11e6-87b5-b39294d1fee6.png)

**Comment by antw** [comment]
Capacity seems less meaningful on these charts since the net load shown on the "total" chart is the consumption (positive) minus production (negative). You could have a technology consuming well beyond the capacity of the node, but as long as some other technology is producing then the node isn't over-capacity.

| Total Load | Stacked Load |
| --- | --- |
| <img width="547" alt="screen shot 2016-09-22 at 20 23 07" src="https://cloud.githubusercontent.com/assets/4383/18762830/790b0222-8102-11e6-8f56-94d6c3e5b9b4.png"> | <img width="552" alt="screen shot 2016-09-22 at 20 23 20" src="https://cloud.githubusercontent.com/assets/4383/18762833/7c63f19a-8102-11e6-89cb-db34482c4e2f.png"> |

Imagine if the node capacity were 24kW; if we draw it as a straight red line on the stacked chart – as we do on the "total load" chart – it may give the impression that the node is over-capacity when in reality it isn't.

**Comment by ChaelKruip** [comment]
> Capacity seems less meaningful on these charts since the net load shown on the "total" chart is the consumption (positive) minus production (negative), and nodes are considered over-capacity only when the net load is too extreme. 

100% right. Closing.
