### ISSUE TITLE
Why does the size of the buffervolume have an impact on the output of the heating technology?

### ISSUE THREAD

**Issue by ThomBuijs** [quintel/etmoses#1465]
I'm using this [LES](https://moses.energytransitionmodel.com/testing_grounds/600). When the volume of the buffer becomes below a certain value the output of the heating technology (a heatpump and a gas heater in my les) will change accourdingly. In my opion this should not make a difference, as long as the input and output capacity of the buffer are equal or higher than that of the buffering heating technology. When I change the volume of the buffer to 0 kWh the output of the heating technologies becomes zero. However, on the wiki it is stated that this should work and would simulate a situation without a buffer but still with a heat demand. 
I want to set the value of the buffer to zero so that no energy is used for filling the buffer. Setting all the heating technologies to boosting has the effect of a buffer with no volume.

**Comment by ChaelKruip** [comment]
> In my opion this should make a difference

You mean *shouldn't* right? In that case I agree completely 😄 

> When I change the volume of the buffer to 0 kWh the output of the heating technologies becomes zero.

I think this is wrong. @antw can you pitch in?

> Setting all the heating technologies to boosting has the effect of a buffer with no volume.

Right. 

> I want to set the value of the buffer to zero so that no energy is used for filling the buffer.

Why do this if you can set all technologies to boosting?

**Comment by ThomBuijs** [comment]
I didn't think of this untill I was finishing this issue. Still I think that it isn't working as it should be, therefore I am making this comment :)

**Comment by antw** [comment]
A fix for boosting technologies being constrained by the buffer volume will be published momentarily.

Buffering technologies are limited by the capacity of the buffer because their energy must pass *through* the buffer prior to being consumed. Boosting technologies skip the buffer, and are therefore not limited by its volume.

It was decided some time ago that a buffer could be filled and emptied only once at each point in the simulation (every 15 minutes). If you have a 1kWh buffer and a 10kW technology, the the tech will run at a maximum of 4kW, since that is how much load is required to fill the buffer from 0-to-100% in 15 minutes. Effectively, the technology runs at 4kW, which results in 1kWh added to the buffer, then that 1kWh is immediately consumed, emptying the buffer back to 0%.
