### ISSUE TITLE
Yearly gas load chart fails to calculate for my LES

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1476]
In [this LES](https://moses.energytransitionmodel.com/testing_grounds/612/gas_load), the yearly gas load chart fails to load:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/19106726/3c6583a6-8ae9-11e6-8a2f-2ef4ee4ee735.png)

**Comment by grdw** [comment]
I threw away the cache. It seems to be loading now... related: #1419.

**Comment by grdw** [comment]
![screen shot 2016-10-05 at 11 04 52](https://cloud.githubusercontent.com/assets/2676542/19107228/8f7c8ea2-8aeb-11e6-94e9-1dc2071b34c0.png)

And done. 👍  

However, this is a bit of a patch fix. Can you maybe recall if you canceled the calculation? Did anything else to maybe 'break' the cache that you're aware of?

**Comment by ChaelKruip** [comment]
> Can you maybe recall if you canceled the calculation? Did anything else to maybe 'break' the cache that you're aware of?

Nope.

**Comment by antw** [comment]
I managed to reproduce it by computing a full annual calculation before viewing the gas summary. Apparently using the `resolution: high` option causes the network cache to use the suffix `current_week` when looking for cache files, instead of `year`.

I changed the calculator to use `resolution: low` and it works fine now (don't worry, the full year – with all 35,040 points – still gets calculated).
