### ISSUE TITLE
What is the last moment that a business case is calculated?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1482]
When you compare your current BC with the BC of another LES, how sure can you be that all changes have been taken into account in the BC of the other LES? Do you need to (re-)calculate the BC before you close your LES?

**Comment by antw** [comment]
> Do you need to (re-)calculate the BC before you close your LES?

That's how it looks to me.

The DelayedJob which recomputes the business case is started when you try to view it, after having made a change. If you're changing business case A in one browser tab, and comparing business case B with A in another, I expect that the data for A will not be recalculated until you view that business case.

Changing this would means the comparison feature would have to poll for data (triggering and waiting for a new calculation to run), instead of expecting the data to be present already.

**Comment by ChaelKruip** [comment]
> I expect that the data for A will not be recalculated until you view that business case.

But what if you never viewed it in the first place? Or if you viewed it and afterwards removed all your technologies etc.?

**Comment by antw** [comment]
> But what if you never viewed it in the first place?

The comparison won't show you any data:

<img width="695" alt="screen shot 2016-10-06 at 11 13 38" src="https://cloud.githubusercontent.com/assets/4383/19148730/f4a64366-8bb5-11e6-9a6f-82c42be8e843.png">

> Or if you viewed it and afterwards removed all your technologies etc.?

The comparison data will be stale and won't reflect the changes made since the business case was last viewed/calculated.

The "comparison" drop-down does not trigger a recalculation of either business case; it will show the results of the most recent calculation. If changes have been made to the LES since that business case calculation, but the business case has not been viewed (in order to trigger the recalculation), then the data in the comparison is old.
