### ISSUE TITLE
Error in export of water heating technologies

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1566]
### Summary
When this [ETM scenario](https://beta-pro.energytransitionmodel.com/scenarios/598718) is exported to a [LES with one end node](https://beta-moses.energytransitionmodel.com/testing_grounds/826)  58 "households water heater electricity" are present in the technologies. The scenario however does not contain this technology for water heating.

I have not noticed similar problems with other exports from ETM to ETM-SA.

### The scenario does not contain electric water heating technologies
![image](https://cloud.githubusercontent.com/assets/19907658/20431158/d676acbe-ad98-11e6-8069-2dc72b8e72b8.png)

### The LES does contain electric water heating technologies
![image](https://cloud.githubusercontent.com/assets/19907658/20431137/bb0d6332-ad98-11e6-84e1-c9707bcf65d0.png)

**Comment by antw** [comment]
Although it is not very intuitive, this is in fact correct behaviour. The ETM scenario has power-to-heat set to 25% (126 households)

> ![screen shot 2016-11-21 at 17 33 52](https://cloud.githubusercontent.com/assets/4383/20493441/b364f49a-b010-11e6-96de-213f1fde9afc.png)

The ETM-SA scenario will respect this setting; if there is insufficient electric heating installed it will add "Households water heater electricity" technologies to compensate.

There are 68 electric heat pumps in the scenario: 126 P2H households - 68 heat pumps = 58 electric water heaters.

**See:**

* [#640 - Building P2H should be equivalent to adding a resistive heater to a buffer](https://github.com/quintel/etmoses/issues/640)
* [#626 - P2H should be possible using a heat pump instead of an electric heater](https://github.com/quintel/etmoses/issues/626)

**Comment by DorinevanderVlies** [comment]
I still have a feeling that this approach is not entirely correct. Currently the demand for hot water to me seems too high in scenario's with P2H and insufficient heat buffers.

Let's say I have 100 households with 500 kWh demand for hot water, 20% P2H, 15 heatpumps and 85 district heating.

In this case the export will give:

- 15 heat pumps
- 85 district heating
- (20-15) 5 P2H.

So the total demand is 500 x 105. This does not correspond to the real total demand.

**Comment by ChaelKruip** [comment]
> So the total demand is 500 x 105. This does not correspond to the real total demand.

I think this is a different issue. Closing this one. @DorinevanderVlies if you feel this is important, could you make an issue about the mismatch of demand between ETM and ETM-SA?
