### ISSUE TITLE
Questions regarding export of heat network

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1574]
### Summary
An external user contacted me because with a default export to ETM-SA he has significant heat deficits.

He has two questions:
- Why is the heating demand not fulfilled with the standard export from ETM to ETM-SA?
- How to reconvert to emission reduction (in ETM) after scaling up the heat sources in ETM-SA? 

To this I add the following question:
- How is the required capacity of the heat sources calculated? Based on total required heat? Or is it taken into account that usually during winter the load is higher? In that case capacity should be higher than average load and I would expect smaller heat deficits. 

### Details
This [ETM scenario](https://beta-pro.energytransitionmodel.com/scenarios/604074) is scaled to 1000 households, it has district heating with 100% biogas CHP, both for hot water and for space heating.

The export to ETM-SA gives this [LES](https://beta-moses.energytransitionmodel.com/testing_grounds/830/edit). With 2.12 CHP plants with a capacity of 1111.1 kW:

![image](https://cloud.githubusercontent.com/assets/19907658/20520048/96edc0f4-b0a5-11e6-9f2e-e5f8d6347eac.png)

The standard setting (export to ETM-SA and standard profiles) give a heat deficit during the winter months:
![image](https://cloud.githubusercontent.com/assets/19907658/20520094/beb7da16-b0a5-11e6-9441-4ff91daace15.png)

After using an aggregated profile for hot water (which is more realistic), the heat deficits can be balanced by scaling up the biogas CHP by roughly a factor 2.

**Comment by antw** [comment]
My guess is that this is simply due the differences in the way things are modelled in the ETM and ETM-SA.

* In ETM-SA there is a capacity, number of units, and an explicit demand profile which must be met for every 15-minutes (or else there is a deficit).

* In the ETM / ETEngine there's an "amount" of heat demand which must be met *during the year*. There is no profile; it must simply output 50.87PJ before the year is up. The ETM determines that – with [a capacity of 1.11MW](https://github.com/quintel/etsource/blob/b2f5cd9f8eaaae3a65bec25aa8bf3ff619637b17/nodes/households/households_collective_chp_biogas.central_producer.ad#L18) – 2.12 units are required to do this.

I *suspect* the deficit is due to the ETM assuming demand can be met constantly throughout the year, but the ETM-SA profile is *anything* but equal.

I think the correct thing to do is to manually increase the number of CHPs until demand is met; I'm not sure what else we can do.

> How to reconvert to emission reduction (in ETM) after scaling up the heat sources in ETM-SA?

I'm not sure what this means. 😕

**Comment by DorinevanderVlies** [comment]
Thanks @antw.

---

> How to reconvert to emission reduction (in ETM) after scaling up the heat sources in ETM-SA?
>> I'm not sure what this means. 😕

The question originates from the effect on the scenario (e.g. CO2 emissions), when the ETM-SA analysis shows that the capacity from ETM is not sufficient.
I think the answer to that is that the increased capacity in ETM-SA does not influence the outcome of the ETM scenario. Because the demand which is supplied is the same. This is true as long as no "must-run" source is used.

----

I can see the logic behind the calculation of the required capacity from a modelling point of view. On the other hand, from a user point of view, I think it is unsatisfactory that a standard export leads to deficits.

A possible solution to this is to make sure that with a standard profile the heat demand can be supplied by the source. @ChaelKruip what's your opinion?

**Comment by ChaelKruip** [comment]
> A possible solution to this is to make sure that with a standard profile the heat demand can be supplied by the source. @ChaelKruip what's your opinion?

What is the 'standard profile'? I think this is a bigger theme: How do we align the *energy* picture of ETM with the *load* picture of ETM-SA?
