### ISSUE TITLE
Secondary heat infrastructure costs not represented in business case

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1586]
### Description

This [LES](https://beta-moses.energytransitionmodel.com/testing_grounds/862/edit) only has technologies attached to node "1 - flat". I just added heat technologies (all district heating) to this node. No investment and O&M costs attached to these technologies.

In the heat assets tab I assigned 1000 euro per connection to all 54 connections. The lifetime is 10 years. So I would expect (1000 euro/10year lifetime *54 units = )5400 euro depreciation costs of stakeholder 1. However, there are no depreciation costs for stakeholder 1.

### Screenshots
![image](https://cloud.githubusercontent.com/assets/19907658/21180945/ad5d3c36-c1fb-11e6-9651-d5991755794e.png)

![image](https://cloud.githubusercontent.com/assets/19907658/21180810/f5ec591a-c1fa-11e6-80b4-9ef80ee87e28.png)

notifying @AlexanderWirtz

**Comment by grdw** [comment]
I'll have a look.

**Comment by grdw** [comment]
If I understand this issue correctly the `Customer Ac1` should receive depreciation costs?

**Comment by DorinevanderVlies** [comment]
Yes, indeed. Or extra outgoing costs, but this doesn't seem to be the case as well.

**Comment by grdw** [comment]
I see what's going on here. Appearantly the `number_of_units` is always 0 and I also know why. Am fixing it.

**Comment by grdw** [comment]
Ok, that was one. But there's another thing going on here. The topology also contains the `Customer AC1` but that calculation returns `NaN` for a reason. Probably because the `technical_lifetime` is not set? If you could check hat out.

**Comment by DorinevanderVlies** [comment]
I found technical lifetimes and investment costs defined as 0 for the buffer. This could be a problem. It shoudn't really be a problem right? 

Are the two LESses below working properly?

[LES with technical lifetimes and initial investment and O&M left emtpy](https://beta-moses.energytransitionmodel.com/testing_grounds/862)

[LES with technical lifetime of 30 years even when initial investment and O&M costs are non-defined (empty)](https://beta-moses.energytransitionmodel.com/testing_grounds/863)

**Comment by grdw** [comment]
> I found technical lifetimes and investment costs defined as 0 for the buffer. This could be a problem. It shoudn't really be a problem right?

No that's not the problem in this case. It's about the nodes in the electricity topology that belong to the stakeholder `Customer Ac1` (those attributes [here](https://beta-moses.energytransitionmodel.com/testing_grounds/863/edit)).

**Comment by DorinevanderVlies** [comment]
Those are indeed that nodes beloning to stakeholder 1. I have a feeling that this NAN has been an issue before, is it related to #1530?

The attributes like investment cost, technical lifetime etc are indeed empty for most nodes in this LES. My preference would be to have the option to leave them empty when they're not relevant (like in this LES). 

![image](https://cloud.githubusercontent.com/assets/19907658/21222015/1952c982-c2c0-11e6-8c16-4585661fed2c.png)

**Comment by grdw** [comment]
> [..] before, is it related to #1530?

Well, not really. The values are now correctly `null` which is fine, but you can't calculate with `null`. We could set defaults for those values but that's a bit odd. 🤔  However, I also think the correct outcome of the `topology_costs` for `Customer Ac1` should be 0 instead of `NaN`. I guess that can be easily done by setting the `technical_lifetime` default to 1 but I need to try that out.

**Comment by grdw** [comment]
Oops, I was checking out the wrong costs. It are the `TechnologyCosts` ...

**Comment by DorinevanderVlies** [comment]
So the heat infrastructure issue is solved, right? :smiley:

**Comment by grdw** [comment]
![screen shot 2016-12-15 at 14 43 27](https://cloud.githubusercontent.com/assets/2676542/21226236/dace6404-c2d4-11e6-8c67-6a6314ecc947.png)

Found it! 👍

**Comment by grdw** [comment]
*About secondary heat assets:*
I made a pull request with the fix for the secondary heat assets. 

*About technology costs:*
However, the technologies in question had to be given a `technical_lifetime` for this to work:

![screen shot 2016-12-15 at 15 53 27](https://cloud.githubusercontent.com/assets/2676542/21228589/adceb65c-c2de-11e6-91ba-835977df5010.png)

I found out that locally one of them had 0 years which is unfortunately possible to enter as a value but impossible to use for the calculation of the initial costs of the business case.
