### ISSUE TITLE
Why do my batteries not discharge during the night?

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1588]
I have a [LES](https://beta-moses.energytransitionmodel.com/testing_grounds/872) with PV and batteries attached to most nodes. I changed the market model to makes it economically beneficial to use the battery as much as possible. It is expensive to buy electricity and you get little money if you sell it to the supplier etc.

Looking at a week in June I notice that the first day the battery is charged. During the night it doesn't discharge. So the next day with excess electricity it is full.

**How come the battery does not discharge during the night?**

![image](https://cloud.githubusercontent.com/assets/19907658/21269261/5ab5a78a-c3b2-11e6-8e05-9239bf517c60.png)

**Comment by antw** [comment]
> How come the battery does not discharge during the night?

I do see some discharging during the night. Maybe it's not as much as you expect?

<img width="586" alt="screen shot 2016-12-19 at 14 34 38" src="https://cloud.githubusercontent.com/assets/4383/21316364/4d94ca16-c5f8-11e6-83a4-25df46b6af26.png">

> I changed the market model to makes it economically beneficial to use the battery as much as possible. It is expensive to buy electricity and you get little money if you sell it to the supplier etc.

There may be some confusion here. The market model has no influence on the consumption or production of electricity (or which technologies are used). This feature was discussed earlier in the development of Moses, but we decided against implementing it at the time.

**Comment by DorinevanderVlies** [comment]
> I do see some discharging during the night. Maybe it's not as much as you expect?

That's indeed the point. I would expect all the demand during the night to be supplied by the battery.
The image below shows very clearly that only a fraction of the demand is supplied by the battery. The battery capacity is much larger that the part that is currently used. The capacity with which is charges is much higher than the decharge capacity.

![image](https://cloud.githubusercontent.com/assets/19907658/21318563/0510d160-c60a-11e6-90f6-b30362733043.png)

**Comment by DorinevanderVlies** [comment]
When I look at this in more detail the batteries are not used to charge EV's.
I understand the reasoning behind this.
 
On the other might it also be an opportunity to use batteries to charge EV's. Might be a bit of a detour, but it allows to use the electricity from PV in cars that are away during the day. Especially in the summer months when the  typical demand when there is no PV available is very small.

Proposal for strategy: buffer EV's with batteries

What's your opinion @ChaelKruip?

**Comment by ChaelKruip** [comment]
> What's your opinion @ChaelKruip?

I like it! @antw would that be technically challenging as it requires two storage technologies to interact?

**Comment by antw** [comment]
> When I looked at this in more detail I noticed that the batteries are not used to charge EV's.
I understand the reasoning behind this.

Batteries can be used to fulfil the "mandatory" part of the EV load (that is, the energy needed to complete the next journey) but – as you observed – not for buffering. It is most obvious when enabling "Only buffer EVs with excess PV production":

![p2p_ev-spare-capacity_ev-local-excess-only](https://cloud.githubusercontent.com/assets/4383/21426634/e086945c-c847-11e6-8def-7abbcb4032b0.png)

> > Proposal for strategy: buffer EV's with batteries
>
> would that be technically challenging as it requires two storage technologies to interact?

It it already possible to buffer EVs using P2P batteries, but it doesn't happen in this particular LES because "Only buffer EVs if network has spare capacity" is enabled. In 3cf3dc4b it was made that capacity-constrained technologies would be computed after unconstrained technologies (see #1453).

P2P batteries are not capacity-constrained so the result *in this LES* is that batteries are given preference over EV buffering. If you turn off that strategy, you should see the desired behaviour:

| EV cap. constraint on | EV cap. constraint off |
| --- | --- |
| ![screen shot 2016-12-22 at 13 43 57](https://cloud.githubusercontent.com/assets/4383/21427533/08830364-c84d-11e6-9bf1-76d08c89e079.png) | ![screen shot 2016-12-22 at 13 44 09](https://cloud.githubusercontent.com/assets/4383/21427537/0c0aad3e-c84d-11e6-8ce9-9d3bb9f51c8d.png) |

*These screenshots are from a simplified LES on my machine, but it should remain true for the full LES on beta.*
