### ISSUE TITLE
Solar PV load does not show in "individual mode with strategies" for the year

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#1595]
[This LES](https://beta-moses.energytransitionmodel.com/testing_grounds/919)

Basic:

![etmoses](https://cloud.githubusercontent.com/assets/1303760/22253927/87c2b47e-e253-11e6-877e-552b85f09c23.png)

With strategies:

![etmoses](https://cloud.githubusercontent.com/assets/1303760/22254016/c2915984-e253-11e6-9b85-3724ea699539.png)

The same seems to go for `housholds_aggregated`...

**Comment by ChaelKruip** [comment]
Including @AlexanderWirtz @DorinevanderVlies @dennisschoenmakers

**Comment by grdw** [comment]
I took a quick peek and I can say that I can exclude this as a front-end JavaScript issue. It looks as though all the Solar PV is eaten by the Electric PV strategy but it would take me some time to figure that out.

**Comment by antw** [comment]
> It looks as though all the Solar PV is eaten by the Electric PV strategy but it would take me some time to figure that out.

Indeed, I expect this an issue in how we attribute loads to individual technologies during the calculation. EVs won't *actually* be responsible for the solar production, even though the technology charts say otherwise.

Unless this is critical, it will likely be a couple of days before I can investigate this more thoroughly.
