### ISSUE TITLE
Whole year network chart and business case do not load

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1597]
Business cases and whole year charts of LESses do not load anymore.

Not even for a very simple [LES](https://beta-moses.energytransitionmodel.com/testing_grounds/924) which contains one node and one technologie. 

Presenting one week of the electricity network works fast, so the LES itself seems ok. 

(@ChaelKruip and me had the idea that the whole year chart and business case calculations had been slowing down lately)

**Comment by antw** [comment]
The background workers were not running; these are responsible for long-running tasks like full-year calculations. They're up again, and your calculations should be fine now.

> (@ChaelKruip and me had the idea that the whole year chart and business case calculations had been slowing down lately)

Possibly because there aren't many background workers; if someone else is already calculating something in the background, yours has to wait until theirs is done. I have increased the number of workers and *hopefully* this will now be less of an issue.

**Comment by DorinevanderVlies** [comment]
Thanks!
