### ISSUE TITLE
When I click edit, all the EV have profile 10 all of a sudden?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#1603]
As reported today by @DorinevanderVlies at a demonstration. Might be a double issue.

**Comment by antw** [comment]
What is "profile 10"? Can you post some steps to reproduce, because when I look at the edit page for a LES (and try saving) I can't seem to find any *obvious* issue...

**Comment by dennisschoenmakers** [comment]
1. Go to https://beta-moses.energytransitionmodel.com/testing_grounds/970
2. Click edit LES
3. Go to technologies
4. Scroll down the list 
5. You'll see at EV's that the profile ending with '10' is always selected, despite it being different first. 

Right, @DorinevanderVlies ?

**Comment by antw** [comment]
I see: households not EVs. 😆

I sort of see what you mean. These are aggregated household technologies, but the profile selection box is providing profiles for individual homes since there are under 30 units of each technology.

<img width="820" alt="screen shot 2017-03-06 at 14 48 58" src="https://cloud.githubusercontent.com/assets/4383/23614853/5630260a-027c-11e7-9891-362146281051.png">

They have been assigned individual profiles (333, 335, 337, and 339: anonimous_base_load_8 through anonimous_base_load_10), but they're all showing as anonimous_base_load_10. I would guess that this is the default behaviour of "EditableTable", when it sees an invalid profile selection: it just defaults to the first one in the list? @grdw: Does that sound right?

*(There was a plan to remove the 30 unit restriction (#1528) – which might fix this – but it is not yet a reality as far as I know. I'm not too sure what the status of it is; work was started on the "split-between-edsn-base-load-removal" branch and #1359 was opened but not finished).*

It's also unclear to me how it was possible to create aggregated households with individual profiles... I'm guessing this is the result of a CSV import?

**Comment by dennisschoenmakers** [comment]
No, I really mean EVs. @DorinevanderVlies can you elaborate please? :-)

Sent from my iPhone

On 6 Mar 2017, at 16:05, Anthony Williams <notifications@github.com> wrote:

I see: households not EVs. 😆

I sort of see what you mean. These are aggregated household technologies,
but the profile selection box is providing profiles for individual homes
since there are under 30 units of each technology.

[image: screen shot 2017-03-06 at 14 48 58]
<https://cloud.githubusercontent.com/assets/4383/23614853/5630260a-027c-11e7-9891-362146281051.png>

They have been assigned individual profiles (333, 335, 337, and 339:
anonimous_base_load_8 through anonimous_base_load_10), but they're all
showing as anonimous_base_load_10. I would guess that this is the default
behaviour of "EditableTable", when it sees an invalid profile selection: it
just defaults to the first one in the list? @grdw <https://github.com/grdw>:
Does that sound right?

*(There was a plan to remove the 30 unit restriction (#1528
<https://github.com/quintel/etmoses/issues/1528>) – which might fix this –
but it is not yet a reality as far as I know. I'm not too sure what the
status of it is; work was started on the
"split-between-edsn-base-load-removal" branch and #1359
<https://github.com/quintel/etmoses/issues/1359> was opened but not
finished).*

It's also unclear to me how it was possible to create aggregated households
with individual profiles... I'm guessing this is the result of a CSV import?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/quintel/etmoses/issues/1603#issuecomment-284421340>,
or mute
the thread

**Comment by DorinevanderVlies** [comment]
It's indeed the households

>I sort of see what you mean. These are aggregated household technologies, but the profile selection box is providing profiles for individual homes since there are under 30 units of each technology.
>It's also unclear to me how it was possible to create aggregated households with individual profiles... I'm guessing this is the result of a CSV import?

Spot on

I've changed the technology to individual household. The problem is gone, thanks @antw

**Comment by dennisschoenmakers** [comment]
Thanks both of you! =)
