### ISSUE TITLE
LESses cannot be opened

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1610]
@jorisberkhout notified me that no LESses are loading on ETM-SA.

I checked with a couple of LESses and got the same error message for all of them:

![image](https://user-images.githubusercontent.com/19907658/35724636-b8c1c5ac-07fe-11e8-9da1-c3ba6439a808.png)

**Comment by grdw** [comment]
One of these gqueries is not working properly:

```
"electric_cars_additional_costs", 
"etmoses_electricity_base_load_demand", 
"etmoses_electricity_base_load_demand_for_buildings", 
"etmoses_hot_water_buffer_demand", 
"etmoses_number_of_buildings", 
"etmoses_space_heating_buffer_demand", 
"households_number_of_residences", 
"share_of_p2h_in_hot_water_produced_in_households"
```

**Comment by antw** [comment]
This appears to be because the queries are calculating the amount of buffer space by looking at the inputs to:

* households_useful_demand_for_hot_water_after_solar_heater_and_p2h
* households_useful_demand_for_space_heating_after_insulation_and_solar_heater

However the space/water heat producers are no longer directly connected to these nodes, therefore `INTERSECTION(GROUP(etmoses), CHILDREN(...))` returns nothing.

**Comment by antw** [comment]
Alternative queries to select the correct nodes might be:

**Space heating:**

```
INTERSECTION(G(etmoses), G(merit_household_space_heating_producers))
```

**Hot water:**

```
INTERSECTION(G(etmoses), G(merit_household_hot_water_producers))
```

**Comment by DorinevanderVlies** [comment]
Nice! Thanks @antw and @grdw

**Comment by DorinevanderVlies** [comment]
Re-opening as the same error message occurs when I try to load a LES on beta.

**Comment by antw** [comment]
Fixed by (re-)deploying the latest version.
