### ISSUE TITLE
Save and open as local energy solution gives error

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmoses#1613]
I get up to the selection of topology and market model

![image](https://user-images.githubusercontent.com/19907658/36101575-084ed43a-100a-11e8-9655-bf8ad1190cb1.png)

However, pressing "continue" leads to this error. So far for all ETM-scenario's I tried to open

![image](https://user-images.githubusercontent.com/19907658/36101633-2af39106-100a-11e8-9689-bc2dd38ffcd3.png)

**Comment by grdw** [comment]
I just tested this locally  with the most recent ETengine and ETLocal. I can verify that it is indeed broken. The thing that specifically breaks is a request for the demands, capacities, etc. about the technologies in ETEngine.

The problem lies within [this line](https://github.com/quintel/etmoses/blob/master/app/models/import/technologies/fetcher.rb#L39) of code. I manage to solve it locally on my machine. It takes some time to properly fix though, about 2-3 hours - would by my guess. 

Other than that, I'm a bit at unease about this issue. The reason is that not to long ago , ETMoses broke down aswell and was fixed again as far as I know. This issue didn't come up, which is a bit odd.

**Comment by DorinevanderVlies** [comment]
> by when would you need to have ETMoses operational again?

By the end of this week would be great
That also leaves time for pre-deploy testing

> Other than that, I'm a bit at unease about this issue. The reason is that not to long ago , ETMoses broke down aswell and was fixed again as far as I know. This issue didn't come up, which is a bit odd.

I think the different issues are about a different step in the procedure.

- https://github.com/quintel/etmoses/issues/1611. Was for the first step: getting to the selection of topology and market mode
- https://github.com/quintel/etmoses/issues/1610 was about opening an already existing LES
- This new issue is about opening a newly created LES after the market model and topology have been selected

**Comment by DorinevanderVlies** [comment]
Re-opening as the same issue is occuring

**Comment by grdw** [comment]
Related Airbrake note:

[Converter attributes are not allowed for households_flexibility_p2p_electricity](https://quintel.airbrake.io/projects/35333/groups/2150729145030563658/notices/2150729143945570242)

Will see to it.

**Comment by DorinevanderVlies** [comment]
On beta exporting to ETM-SA works fine, but on the live server I get the error that is described above

**Comment by grdw** [comment]
Seems that production is not up to date with the current changes in the master branch.

**Comment by grdw** [comment]
I deployed and it seems to be working:

![screen shot 2018-03-08 at 10 21 26](https://user-images.githubusercontent.com/2676542/37143122-7a6c6538-22ba-11e8-8d9c-592a0f3191bc.png)

**Comment by DorinevanderVlies** [comment]
Thanks @grdw !

**Comment by DorinevanderVlies** [comment]
Reopening as issue re-occurs on beta
