### ISSUE TITLE
kW_max, kW_contracted, kW_connection have to be accounted for

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#191]
This ticket is to specify what the Trello card with the same title means.

* kW_max: the maximum capacity (load) that has been realised on an end-point of the network in a given time-period (typically a month). To make this assessment, the maximum load on end-points needs to be stored for the LES for each month.

* kW_contracted: this is relevant for large consumers (industry) and relates to a payment scale. The connection is often not the limiting factor for this capacity. If the consumer surpasses the contracted capacity, it will move to a higher payment scale. To make this assessment, the maximum load on end-points needs to be stored for the LES.

* kW_connection: this is the capacity of the connection that a consumer has on the network. If we have individual houses connected to the network end-points this number is 3x25 Ampère at 230 Volts = 17.25 kW. Perhaps we can scale this number with the 'units' attribute of the base-load profile for end-points that have multiple households?

**Comment by antw** [comment]
Thanks for the explanation, @ChaelKruip. This also answers some of the questions I was going to ask about payment rules. :smiley:

> kW_contracted: this [...] relates to a payment scale.

Do we know what a "payment scale" is and how it might behave? For example, is the user going to be expected to enter values, does it come from a profile, or is it some hard-coded or computed scale? I'm imagining something like this, so correct me if I'm wrong!

| kW contracted | Price |
| ------------: | :---- |
| 0 kW - 7 kW   | 10.0  |
| 7 kW - 15 kW  | 15.0  |
| 15 kW - Inf   | 25.0  |

> Perhaps we can scale this number with the 'units' attribute of the base-load profile for end-points that have multiple households?

This seems like a code-smell to me. Coupling the code with data (hard-coding a special-case for profiles whose type is "base_load") makes the application fragile in the event that we change the data in the future. For example, we might change the "base_load" type to be called "household_load" -- but oops!... we forgot to change the code.

My preference would be to set a "number of connections" attribute on the endpoint, but unfortunately we can't do that since the endpoints are part of the topology YAML. I'll think it over and see what I can come up with. Maybe we'll *have* to infer it from the "base_load" for now.

**Comment by ChaelKruip** [comment]
> Do we know what a "payment scale" is and how it might behave? 

I think that it can be hard-coded at first. I also expect it to behave as you describe :smile: 

> My preference would be to set a "number of connections" attribute on the endpoint

I am all for an approach like that. Let's see if it is feasible!

**Comment by ChaelKruip** [comment]
Closing.
