### ISSUE TITLE
Interaction table: measurables

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#197]
Some discussion points in https://github.com/quintel/etmoses/issues/193 have led to new ideas on the 'interaction table' and its links to the LES.

In short: I think the interaction table could use an extra column for 'measured stuff'.
The table will then look like this:

| From | To | Foundation | Measure | Tariff | 
|-----|-----|-----|------|-----|
|Customer (not in co-operation) |Supplier| kWh| net consumption of kWh | 0.07 EUR/kWh| 
|Customer (not in co-operation) |System operator| kW | size of connection | 180 EUR| 
|Customer (not in co-operation) | kWh|Government| net consumption of kWh | 0.22 EUR/kWh| 

The 'measured stuff' column has some overlap with the 'foundation' column (perhaps we can remove the latter one?).

We can pre-define some measures:

* kW of connection per HH
* kWh consumed per HH
* kWh produced per HH
* kWh produced for the LES (producer)
* kW_max for HH/end-point
* investment cost of infrastructure
* maintenance cost of infrastructure
* kWh consumed by Co-operation
* kWh produced by Co-operation
* kW_max for Co-operation
* ?

Perhaps we need to specify the time-scale for these measurements as well? Capacity for fixed connections need only be measured once per year. Most stuff is measured every time-step.

I think that all transactions are yearly.

@antw @dennisschoenmakers what do you think?

**Comment by antw** [comment]
> We can pre-define some measures:

These examples appear to combine foundation and measure. If they were to be separate concepts, I'd think of combinations like this:

| Foundation | Measure |
| ---------- | ------- |
| kW of connection | per HH |
| kW of connection | endpoint(s) / stakeholder total |
| kWh consumed | per HH |
| kWh consumed | endpoint(s) / stakeholder total |
| kWh produced | per HH |
| kWh produced | endpoint(s) / stakeholder total |
| ... | ... |

We have three foundations defined – "kW of connection", "kWh produced", and "kWh consumed" – and two measures – "per HH" and "endpoint total".

Looking at [the original example table](https://github.com/quintel/etmoses/issues/197#issue-92661974), it seems like the measure makes the foundation irrelevant. Take, for example, a foundation of "kW", and a measure of "size of connection". Can I set the foundation to "kWh"? Probably not.

For me, the realisation here is that the foundations are going to be more numerous, and more specific. `kWh per household` and `stakeholder kWh` instead of just `kWh`.

> Perhaps we need to specify the time-scale for these measurements as well? Capacity for fixed connections need only be measured once per year. Most stuff is measured every time-step.

I'm not sure if this needs to be something the user can edit. In most cases, the chosen foundation/measure imply a time-scale.

The only exception (so far) seems to be `kW_max` which may be per-month, per-week, etc. But I think before we go down this road we – and particularly the client – need to think about how this data is going to be presented to the user. Does a `kW_max per month` rule result in a price graph with 12 data points, while `per week` has 52?

I suggest we leave this out *for now*, and revisit later in the sprint.

**Comment by ChaelKruip** [comment]
> We have three foundations defined – "kW of connection", "kWh produced", and "kWh consumed" – and two measures – "per HH" and "endpoint total".

I like that!

> For me, the realisation here is that the foundations are going to be more numerous, and more specific. kWh per household and stakeholder kWh instead of just kWh.

Yes!

> I suggest we leave this out for now, and revisit later in the sprint.

I agree.

**Comment by antw** [comment]
No longer required, and superseded by #219.
