### ISSUE TITLE
How to measure flexibility?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#208]
One of the 'measurables' in the LES which will be used in financial transactions is the amount of used flexibility and the potential for flexibility. We have defined these with the client:

* Used flexibility: the difference between the blue and the green curves in the load chart (at the level of the end-points). For a co-operation this is the sum of the end-points that are part of the 'Aggregator' stakeholder. NOTE: this approach implies that assignment to the 'Aggregator' needs to happen on a per-endpoint basis (see [this ticket](https://github.com/quintel/etmoses/issues/207)).

* Potential flexibility: the mean of the Used flexibility (see above) so far.

**Comment by ChaelKruip** [comment]
There is an extra refinement of the 'measuring of flex':

* The System Operator is only interested in flexibility in parts of the network where there is actually congestion expected when no flex is used (the blue curve is higher than the capacity of a network component at any point in time). This is because the S.O. is interested in preventing congestion. 

There are two suggestions for the S.O. paying the customer (or the aggregated customers in the co-operation) for their flex:

1. Pay them a fixed amount if the load did not exceed the capacity.
2. Pay them for the amount of flex used (even if that did not solve the issue). This happens with a fixed price per kWh flex provided (again, only for those end-points that are 'under' a network component that might be congested if no flex is applied.

NOTE: Now that I think about this there is another question that I have: "Does the S.O. only pay for flex in a time-step where otherwise congestion would have ensued?". That would be unfair to the customer in a way as he would be using flexible options all year round and **only** gets paid when a problem would have occurred. Perhaps it would be better to see the applied flex as an 'insurance' that the S.O. compensates the Customer for.

@dennisschoenmakers @antw @jorisberkhout what do you think?

* The Supplier might be interested in flexibility in general (to balance the demand and supply). This means that flexibility should be 'measured' for all end-points.

**Comment by antw** [comment]
> Pay them a fixed amount if the load did not exceed the capacity.

I believe that's easy enough.

> Pay them for the amount of flex used. This happens with a fixed price per kWh flex provided

If I'm reading this correctly, you're suggesting that the customer is paid for the difference between the blue and green curves (but only in cases where the blue curve exceeds capacity)?

**Comment by ChaelKruip** [comment]
> If I'm reading this correctly

Yes :smile: But I'll confirm this with our client later this week.

**Comment by antw** [comment]
>> If I'm reading this correctly
>
> Yes :smile: But I'll confirm this with our client later this week.

... which is problematic because:

1. The green curve may include storage. The implication is that we'd have to compute the LES with flexibility on and storage off in order to determine the effects of flex without being affected by storage (otherwise you don't know which of the two is responsible for a change in load).

2. It means we need to calculate the network at least twice (flex off and flex on) *before* we can do the market model. Without cached, calculated network graphs, the performance is going to be dreadful for larger networks.

  The market model currently expects to operate on a single calculated LES, so it would need to be changed to accept *multiple* networks, in order to compare the differences.

**Comment by ChaelKruip** [comment]
> The green curve may include storage.

This is not a problem! Flexibility includes storage as well as load management options. Sorry for sloppy use of the words. Perhaps we should no longer distinguish between 'storage' and 'load management' so much: it's both 'flexibility'.

> It means we need to calculate the network at least twice

We already do that right? Or is there a very smart way to get the 'blue curve' (no flex options) without actually calculating the load?

**Comment by antw** [comment]
> > It means we need to calculate the network at least twice
>
> We already do that right?

We do, but only when the user *wants* both, and the results of the calculation are not cached or stored on the server for future use (for example, by the market model). It works like this:

1. User loads LES page.
2. Browser requests the "blue-curve" network.
3. Server calculates "blue-curve" network and sends back the results.
4. Browser shows the network diagram and charts.
5. User enables a storage/flexibility option. Browser requests the "green-curve" chart.
6. Server calculates "green-curve" network and sends back the results.
7. Browser updates the network diagram and charts.

When the market model needs both, it has to compute both before it can calculate the market model interactions:

1. User views market model.
2. Server computes blue-curve network.
3. Server computes green-curve network.
4. Server computes market model, and sends the results to the browser.

If calculating the LES takes 5 seconds, that's 10 seconds of set-up time (blue+green networks) before we even get to calculating the market model.

Anyway, that's not really an issue; just something to be aware of.

--

> I'll confirm this with our client later this week.

I'll wait until you've heard before I make any changes to the market model.

**Comment by ChaelKruip** [comment]
> I'll confirm this with our client later this week.

Confirmed.

**Comment by antw** [comment]
In order to calculate "flexibility realised" or "flexibility potential", we need to compare two calculated networks to see the difference in load. At this moment in time, the measure would look at the differences between an all-strategies-off ("blue line") network and an all-strategies-on network.

In light of #376, which will include the author's choice of strategies when calculating a business case, I don't think this assumption is true anymore. Instead, I think the measure should compare an all-off network with the *author's-choice-of-strategies* network.

@ChaelKruip Does this sound reasonable to you?

**Comment by ChaelKruip** [comment]
> @ChaelKruip Does this sound reasonable to you?

That is exactly what I had in mind. :+1:

**Comment by antw** [comment]
Thanks. The measure was implemented some time ago; this is a trivial change. Hope to have it on beta shortly.

**Comment by ChaelKruip** [comment]
@antw can this be closed?
