### ISSUE TITLE
Flexibility strategies should become available on a technology level

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#212]
The idea is to have check-boxes for the following 'strategies':

- [x] Storage in EV prioritising local PV production
- [ ] Storage in batteries prioritising local PV production
- [ ] Conversion of local PV excess using P2H
- [ ] Conversion of local PV excess using P2G
- [ ] Buffering of local PV excess in EV
- [ ] Buffering of local PV excess in space heating HP
- [ ] Buffering of local PV excess in hot water HP
- [ ] Postponing of individual base-load 
- [ ] Saving of aggregated base-load
- [x] capping of solar PV + slider to set maximum amount of capping allowed

This way, the user can compare all combinations of these options.

@antw does the current implementation of storage and load management allow such an interface?

**Comment by antw** [comment]
> Storage in EV prioritising local PV production

Is there a reason behind saying "local **PV** production" specifically, rather than just calling it "local production"? I suspect, as the only production technology so far implemented, it is being used as a synonym for "production".

> capping of solar PV + slider to set maximum amount of capping allowed

Capping of solar PV doesn't support a user-defined maximum at this stage: it simply tries not to overproduce when there isn't demand for all the energy. What values would this slider allow the user to choose?

> does the current implementation of storage and load management allow such an interface?

All storage and load management behaviours can be turned on and off. Currently this is decided with [the `:storage` and `:flexibility` options in the TestingGroundController](https://github.com/quintel/etmoses/blob/master/app/controllers/testing_grounds_controller.rb#L66-L67). The base `Storage` class [then looks at these options to determine how to behave](https://github.com/quintel/etmoses/blob/master/app/models/network/storage.rb#L8-L10). `disabled?` should return `false` when the special behaviour is to be turned on, and `true` when it is to be turned off.

If, for example, you wanted to turn on and off storage in batteries, you'd need to change the [Network::Battery](https://github.com/quintel/etmoses/blob/master/app/models/network/battery.rb) class to have something like:

```ruby
class Battery < Storage
  extend ProfileScaled

  def self.disabled?(options)
    ! options[:batteries]
  end
end # Battery
```

* Storage in EV prioritising local PV production – [Network::ElectricVehicle](https://github.com/quintel/etmoses/blob/562d61bd2eaca038fbda46ea0ae45114fd16d99c/app/models/network/electric_vehicle.rb)
* Storage in batteries prioritising local PV production – [Network::Battery](https://github.com/quintel/etmoses/blob/562d61bd2eaca038fbda46ea0ae45114fd16d99c/app/models/network/battery.rb)
* Conversion of local PV excess using P2H – [Network::Buffer](https://github.com/quintel/etmoses/blob/562d61bd2eaca038fbda46ea0ae45114fd16d99c/app/models/network/buffer.rb)
* Conversion of local PV excess using P2G – [Network::Siphon](https://github.com/quintel/etmoses/blob/562d61bd2eaca038fbda46ea0ae45114fd16d99c/app/models/network/siphon.rb)
* Buffering of local PV excess in EV – [Network::ElectricVehicle](https://github.com/quintel/etmoses/blob/562d61bd2eaca038fbda46ea0ae45114fd16d99c/app/models/network/electric_vehicle.rb)
* Postponing of individual base-load – [Network::DeferrableConsumer](https://github.com/quintel/etmoses/blob/562d61bd2eaca038fbda46ea0ae45114fd16d99c/app/models/network/deferrable_consumer.rb)
* Saving of aggregated base-load – [Network::OptionalConsumer](https://github.com/quintel/etmoses/blob/562d61bd2eaca038fbda46ea0ae45114fd16d99c/app/models/network/optional_consumer.rb)
* Capping of solar PV  – [Network::ConservingProducer](https://github.com/quintel/etmoses/blob/562d61bd2eaca038fbda46ea0ae45114fd16d99c/app/models/network/conserving_producer.rb)

> * Buffering of local PV excess in space heating HP
> * Buffering of local PV excess in hot water HP

These are both implemented by the same technology class – [Network::PreemptiveConsumer](https://github.com/quintel/etmoses/blob/562d61bd2eaca038fbda46ea0ae45114fd16d99c/app/models/network/preemptive_consumer.rb). Therefore they may either both be on or off. Is it necessary to be able to set each independently?

**Comment by ChaelKruip** [comment]
> I suspect, as the only production technology so far implemented, it is being used as a synonym for "production"

It is important to distinguish between volatile and dispatchable here. If we also introduce (volatile) wind turbines in the LES, the rules can be the same. For dispatchable producers, the strategies will be completely different as they follow demand (rather than solar irradiation or windiness).

> What values would this slider allow the user to choose?

Between 0% and 100% of the installed capacity. If set to 0%, there is no room for capping. If set to 100% all production can be capped (as is currently the case I understand from your comment).

> If, for example, you wanted to turn on and off storage in batteries, you'd need to change the Network::Battery class 

Is this something that @grdw can start doing?

> Is it necessary to be able to set each independently?

No. I think it is fine for now to treat them together.
