### ISSUE TITLE
A financial summary should be given of all stakeholders

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#213]
The market model is defined by transactions of stakeholders to other stakeholders, based on measurables in the LES and a tariff per measured quantity. This result in yearly transactions in EUR. The idea is to summarise the result of these transactions as a 'balancing sheet' like this:

|From\To|Customer|Aggregator|System Operator|Supplier|Producer|Government|Total incoming|
|---|---|---|---|---|---|---|---|
|**Customer**|Investments|||||||
|**Aggregator**||Investments||||||
|**System Operator**|||Investments|||||
|**Supplier**||||Investments||||
|**Producer**|||||Investments|||
|**Government**||||||Investments||
|Total outgoing|||||||

**Comment by ChaelKruip** [comment]
We could include a dropdown menu to select other (saved) LES's to compare to and possibly a second selection box to choose the format for comparison (%, absolute numbers, bother numbers etc.)

**Comment by grdw** [comment]
![screen shot 2015-07-21 at 11 51 14 am](https://cloud.githubusercontent.com/assets/2676542/8797889/cf711040-2f9e-11e5-9ec3-368bc8c12257.png)

This is how it looks right now with a single interaction between customer and customer.

**Comment by ChaelKruip** [comment]
Very cool! EUR would be a currency better suited for the Netherlands though ;)

**Comment by grdw** [comment]
I'm still puzzled how the tariff and all that is calculated and what actually is in the `markets` branch. @antw maybe you can sort of give me a quick summary of what exactly is build and how this would relate to the thing I'm seeing right here.

**Comment by antw** [comment]
Building a market model – and getting the computed prices out the other end – is still a bit of a work-in-progress. As is everything else between those two steps. :innocent: 

There already exists a [Market.build](https://github.com/quintel/etmoses/blob/fdd01e5f83e8024cba46dde953e4cba1ef9e2324/app/models/market.rb#L9-L42) method to construct the market model – but this, too, is incomplete. I'm (supposedly :anguished:) off for a week starting Friday, so I shall make it a priority tomorrow to get the market model inputs and outputs finished and clearly documented.

The idea is to look at the computed network and assign a price to various things there. The simplest possible example might be that a `Retailer` stakeholder wants to charge `Customers` €0.10 per kilowatt-hour of energy they consume. We would define this as a `relation` (or "interaction") measuring `:kwh_produced`, and a tariff of 0.1.

`Customers` are all of the households and buildings in the network (the "endpoints", or the nodes at the bottom of the network), so it's quite easy to look at how much energy they consume over the year and charge a price.

```
consumed = 0.0

for each endpoint
  for each point-in-time
    consumed += endpoint.consumed_at(frame)

price = consumed * 0.1
```

It's probably going to end up more complicated than this, since tariffs are not always simple numbers – they may change depending on the value being measured (10¢/kWh below 10kWh, 20¢/kWh above 10kWh), or they may be based on price curves. The things being measured can also be more complex than a simple method call. However, I don't think you need to be concerned about these things right now – this stuff is on me.

I'm hoping that the API will be super-simple and look something like this:

```
market = Market.build(MarketModel.first, TestingGround.first)
market.prices # => [ ... ]
```

... where `Market#prices` returns you an array containing the stakeholder interactions and how much they're charging, but at the moment it's all a bit abstract and unfinished.

**Comment by grdw** [comment]
````ruby
market = Market.build(MarketModel.first, TestingGround.first)
market.prices # => [ ... ]
````

This sounds pretty cool :+1: 

> but at the moment it's all a bit abstract and unfinished.

Okay, I get it. I'll focus my attention on something else in the mean time. 

However, as we would say in Holland: good busy.

**Comment by ChaelKruip** [comment]
Can we close this @grdw?

**Comment by grdw** [comment]
Yes
