### ISSUE TITLE
Which "Measures" for market models do we need

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#219]
This is an attempt to gather all info about the 'measures' we will need to realise in order to calculate the relevant business cases for our market models. We may decide not to include some of the measures described below, or perhaps we later think of others later so this list is not definite.

I think of a 'measure' as the quantification of some property in the LES that can serve as the basis for a transaction. So, the number of kWh's of electricity consumed over the year by the 'Customer' stakeholder would be a simple example.

When thinking about measures, I realised that most of them are related to either the 'Customers' or the 'Co-operation' stakeholders. Both these stakeholders are actually groups of end-points of the topology including all attached technologies and base_loads. So, most of the measures happen on the end-nodes. Unless specified differently, each measure applies to both 'Customers' and the 'Co-operation'. Within the group of connections that is the 'Customer' or the 'Co-operation', the loads can be summed.

Measures fall in roughly four categories: capacity, commodity, flexibility and outages. 

# Capacity-related measures

- [x] The number of base_load profiles (this is how we determine how many 'user connections' there are to the network. Note that an end-point of the network can have many 'user connections' (the 'units' of the base_load).
- [ ] The yearly maximum peak of the sum of all (for the selected stakeholder) load on the lowest level of the network (this is basically, the 'kW_gecontracteerd')
- [x] The monthly maximum peak load (the 'kW_max')
- [x] The instantaneous load (i.e. a vector containing 35,040 points)
- [ ] Depreciation cost of all transformers in LES (later also cables): i.e. installation costs divided by its economic lifetime

# Commodity-related measures

- [x] kWh consumed
- [x] kWh produced. NOTE: At the moment we assume that all production at the lowest level is volatile (either wind or solar) or from discharging batteries (P2P and EV) which we also count as renewable
 - [ ] kWh produced for those who produce under *x* (e.g. 10,000) kWh on average (per connection) OPTIONAL
- [x] kWh produced by Producer (mix of installed plants determined by Merit Order) which is equal to the net load on the highest node of the network (HV)

NOTE: The following condition is in effect for these measures: no flow of energy (kWh) is possible through a transformer that is congested or has been congested in the past **three hours**. This means that all connection under a congested transformer cannot consume or produce energy. This holds even if the sub-net is capable of transporting that energy (the reason is that the 50Hz signal disappears when transformers break down and this signal is needed by all electrical technologies considered here).

# Flexibility-related measures

- [x] kWh of flexibility realised (difference between blue and green curves)
- [x] kW of 'potential' flexibility (this is the yearly average of the realised kWh flex above)
- [ ] kWh of realised flex at moments when blue > capacity of trafo and green < cap. This measure is very specific for how/when the System Operator wants to use flexibility. The SO is only willing to pay (extra) for flexibility if that would solve a congestion event which would occur if the flexibility were not realised.

# Outage/Congestion-related measures

- [ ] kWh of outage events of transformers that I live under divided by the number of affected connections. This one is very tricky. It basically means that whenever a trafo is congested, you go down to the lowest level and see which connections are affected. Every connection that is affected gets a compensation which scales with the capacity of the transformer that broke down, divided by the number of affected connection and multiplied by the duration of the event (3 hours for now).

- [ ] Times that the “kWh of flex at moments when blue > cap and green < cap” is used per year times the number of connections (IF > 1, get a fixed EUR Per HH)

# General thoughts

The fact that most measures are relevant for at least two stakeholders (Customers and Co-operations) suggests to me that we could reduce the number of possible 'measures' by having a column in the transaction table for the stakeholder to which the measure applies:

|From|To|Measure|Stakeholder to which the measure applies|Tariff (EUR/measured unit)|
|---|---|---|---|---|
|Customer|Supplier|kWh consumed|Customer|0.22|

**Comment by ChaelKruip** [comment]
@antw could you please give an estimate of time required (in days) for each of the above measures? This will help @dennisschoenmakers and myself to create a workable project-backlog tomorrow afternoon (after lunch 13:00). Thanks!

**Comment by antw** [comment]
@ChaelKruip A lot of these seem like a combination of "foundation" and "measure" ([previously mentioned here](https://github.com/quintel/etmoses/issues/197#issuecomment-118090454)). The descriptions suggest to me that you've decided you'd like the two concepts combined; is that a fair assessment?

--

With the usual caveat that these are *guesstimates*, based on the information I have so far.

#### Capacity-related measures

> * The number of base_load profiles (this is how we determine how many 'user connections' there are to the network. Note that an end-point of the network can have many 'user connections' (the 'units' of the base_load).
> * Depreciation cost of all transformers in LES (later also cables): i.e. installation costs divided by its economic lifetime

I assume that the "number of base_load profiles" measure would be used to assign a fixed-price per-household?

Calculation of depreciation costs assume that these costs have already been set somewhere in the network (I would guess as part of the topology YAML).

**2h each.**

> * The monthly maximum peak load (the 'kW_max')
> * The instantaneous load (i.e. a vector containing 35,040 points)

These capacity measures will return arrays of values, instead of a single numeric value for the entire year. My assumption so far is that calculating the price of these rules goes something like this:

`Value_1` × `Tariff` + `Value_2` × `Tariff` + ... + `Value_N` × `Tariff`

Is this your understanding also? **2h each if so.**

"Instantaneous load" appears to be the only measurable which could have a time-curve-based tariff?

>  The yearly maximum peak of the sum of all (for the selected stakeholder) load on the lowest level of the network (this is basically, the 'kW_gecontracteerd')

I've re-read this several times and I'm not getting it. :tired_face: It sounds like this is the same as kW_max, except that the "max-load" period is the entire year, instead of 1 month? #191 suggests that the main distinction is in the tariff, which increases when certain "threshold" capacities are exceeded.

#### Commodity-related measures

> * kWh consumed
> * kWh produced. NOTE: At the moment we assume that all production at the lowest level is volatile (either wind or solar) or from discharging batteries (P2P and EV) which we also count as renewable
> * kWh produced for those who produce under x (e.g. 10,000) kWh on average (per connection) OPTIONAL

**2h each.**

Is is significant to the measure to classify end-point production as "volatile"?

> * kWh produced by Producer (mix of installed plants determined by Merit Order) which is equal to the net load on the highest node of the network (HV)

I have a hard time estimating this. It depends on whether we have to get data from ETEngine in order to set up the Merit Order (with the participants, load profiles, and so on). I would suggest this is **a couple of days**, but it's hard to be precise.

#### Flexibility-related measures

> * kWh of flexibility realised (difference between blue and green curves)
> * kW of 'potential' flexibility (this is the yearly average of the realised kWh flex above)
> * kWh of realised flex at moments when blue > capacity of trafo and green < cap. This measure is very specific for how/when the System Operator wants to use flexibility. The SO is only willing to pay (extra) for flexibility if that would solve a congestion event which would occur if the flexibility were not realised.

This is troublesome due to the need to provide calculated copies of both the blue and green networks to the measure. It's *especially* troublesome since I think we promised it for *this* sprint? ("Flexibility needs to be quantified for consumers").

In my mind this is **2-3 days** to create the measures, and change the payment rule system to accept multiple networks. This needs to be done in a way that doesn't wreck performance in market models which don't use these flexibility measures.

#### Outage/Congestion-related measures

> * kWh of outage events of transformers that I live under divided by the number of affected connections. This one is very tricky. It basically means that whenever a trafo is congested, you go down to the lowest level and see which connections are affected. Every connection that is affected gets a compensation which scales with the capacity of the transformer that broke down, divided by the number of affected connection and multiplied by the duration of the event (3 hours for now).

_**Days**_. We need to support blackouts in the network calculation first.

> * Times that the “kWh of flex at moments when blue > cap and green < cap” is used per year times the number of connections (IF > 1, get a fixed EUR Per HH)

This has the same "blocker" as the flexibility measures: needing both blue and green networks. Once that is in place, this measure is **probably 4h**.

**Comment by ChaelKruip** [comment]
> The descriptions suggest to me that you've decided you'd like the two concepts combined

Yes. I think it makes more sense to combine them and use the 'stakeholder to which the measure is applied' as a separate thing.

**Comment by ChaelKruip** [comment]
Thanks for the estimates! I'll respond to your questions later today :smile:

**Comment by antw** [comment]
> Yes. I think it makes more sense to combine them

Fair enough. This is easier for me also, so it's win-win. :smiley:

>  The number of base_load profiles (this is how we determine how many 'user connections' there are to the network. Note that an end-point of the network can have many 'user connections' (the 'units' of the base_load).

Do `base_load_buildings` technologies also count as a discrete connections, like a household `base_load`?

**Comment by antw** [comment]
>  kWh produced by Producer (mix of installed plants determined by Merit Order) which is equal to the net load on the highest node of the network (HV)

I realise in hindsight that this doesn't appear to be seeking integration with the merit order, but is just the production of the top-level node?

If so, this is no additional work over the "kWh produced" measure. The same "kWh produced" measure can be used with endpoints (to determine LES production) and the top-level node (to determine the producers production).

**Comment by ChaelKruip** [comment]
> I realise in hindsight that this doesn't appear to be seeking integration with the merit order, but is just the production of the top-level node?

Yes. But we will have to couple the MO to ETMoses to get a price curve and to calculate CO2-emissions and renewability for the LES (possibly next sprint, possibly later on).

**Comment by ChaelKruip** [comment]
> The number of base_load profiles (this is how we determine how many 'user connections' there are to the network. Note that an end-point of the network can have many 'user connections' (the 'units' of the base_load).

We will have to refine this a bit. The client wants to measure the number of connections of a 'type' which differ by capacity of the connection. I think adding capacity and units to end-points should provide the needed measurable quantity.

**Comment by ChaelKruip** [comment]
Because this issue is becoming a bit lengthy, I'll be making separate issues for the measures that are still needed or are not behaving as expected.

**Comment by ChaelKruip** [comment]
Closing this. See https://github.com/quintel/etmoses/issues/363 for current status.
