### ISSUE TITLE
Questions about load management

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#222]
These questions have come up during discussions between @grdw and myself. They will help us to test and improve the current implementation of load management strategies:

* Is there a fixed charging/discharging capacity for P2P (similar to EV)? Or does it use a maximum capacity only?

Which would be the appropriate behaviour @jorisberkhout?

* Are 'PreemptiveConsumers' always heat pumps? EV can also work 'preemptively right?

* Is it true that the 'buffering strategy' for EV yields identical results to the 'storage strategy' for EV?

From the discussion in [this ticket](https://github.com/quintel/etmoses/issues/174) and my own recollection, I would expect buffering in EV (and HP) to take place based on availability of the network (i.e., 'space' or lack of congestion) rather than availability of PV production. In other words, if there is no local (PV) production, I would expect the following:

-- Storage strategy for EV enabled: EV only charges when mandatory (to make the next trip)
-- Buffering strategy for EV enabled: EV starts charging as soon as returned from trip (if the network allows it)

* Is it true that 'saving', 'postponing' and 'capping' are only applied IF there is congestion on a transformer? (it should)

* Right now, the network is not calculated for congestion events every time a strategy has been applied right?

So, if I would select 'capping' and 'postponing', they are both activated based on the initial (blue curve) load and do not take into account the effect of the one that is applied first.

**Comment by antw** [comment]
> Is there a fixed charging/discharging capacity for P2P (similar to EV)? Or does it use a maximum capacity only?

They may charge, or discharge, any amount up to (but not exceeding) the user-defined capacity for the battery.

> Are 'PreemptiveConsumers' always heat pumps? EV can also work 'preemptively right?

Electric vehicles may take excess production from the LES just like a `PreemptiveConsumer`. If load management is turned on, it will also respect the capacity limits of the network. The load stored in the EV may be discharged (like a P2P battery), or used by the EV when disconnected.

However, electric vehicles are implemented separately (in an [ElectricVehicle class](https://github.com/quintel/etmoses/blob/ba067a3675ec472472c0da5a10a5dc6e89b55753/app/models/network/electric_vehicle.rb)) due to the extra features which they must support (disconnection, and the ability to discharge back into the network).

> I would expect buffering in EV (and HP) to take place based on availability of the network (i.e., 'space' or lack of congestion) rather than availability of PV production. In other words, if there is no local (PV) production, I would expect the following:
>
> -- Storage strategy for EV enabled: EV only charges when mandatory (to make the next trip)

Correct. If there is no excess production from PV, the EV will charge only when the profile instructs it to do so. It will take this energy from the grid since there is no PV supply available.

> -- Buffering strategy for EV enabled: EV starts charging as soon as returned from trip (if the network allows it)

No. If there is no excess solar PV production, there is nothing to buffer.

> Is it true that the 'buffering strategy' for EV yields identical results to the 'storage strategy' for EV?

I should be clear about this (once and for all :grinning:): there are no "strategy" classes anywhere in the Network namespace. There is no ElectricVehicle**Storage**Strategy, nor an ElectricVehicle**Buffering**Strategy. Instead, we have a base "Technology" class, and a number of subclasses which implement custom behaviour those which require it.

If storage is turned on, EVs are represented as an [ElectricVehicle class](https://github.com/quintel/etmoses/blob/ba067a3675ec472472c0da5a10a5dc6e89b55753/app/models/network/electric_vehicle.rb), which implements features like load buffering, disconnection, and eventually #131. If you also turn on load management, the EV will reduce its buffering in times of network constraint.

When storage is turned off, the [Disableable module](https://github.com/quintel/etmoses/blob/ba067a3675ec472472c0da5a10a5dc6e89b55753/app/models/network/electric_vehicle.rb) turns it into an ordinary Technology class. In this situation, it will load only when the profile says to do so, will not discharge back into the network, and will not care about network constraints. It is, in effect, an ordinary consumption technology.

> Is it true that 'saving', 'postponing' and 'capping' are only applied IF there is congestion on a transformer? (it should)

Yes, yes, and no. Capping will cause a solar PV technology to limit its production in the event that this energy would be returned to the grid. For example, if technologies in the LES want only 20kW, but the solar array can output 30kW, the behaviour is thus:

* Load management turned off: 20kW is used by the consumption technologies, 10kW is passed to the grid.
* Load management turned on: PV produces only the 20kW wanted by the consumption technologies.

Another example [may be found here](https://gist.github.com/antw/e9f94ed3d7cb84cce67a#file-04-capping-md).

Restricting *production* based on capacity constraints requires either some very hacky code ([briefly discussed here](https://github.com/quintel/etmoses/issues/174#issuecomment-113197545)), or a better calculator (subnet awareness).

> Right now, the network is not calculated for congestion events every time a strategy has been applied right? So, if I would select 'capping' and 'postponing', they are both activated based on the initial (blue curve) load and do not take into account the effect of the one that is applied first.

I'm not sure what's being asked here. Can you provide an example?

**Comment by ChaelKruip** [comment]
> They may charge, or discharge, any amount up to (but not exceeding) the user-defined capacity for the battery.

I think we have an (understandable) nomenclature mixup here: 
* capacity is a **rate** [kW] at which the battery can charge or discharge. 
* volume is the amount of energy [kWh] that fits in the battery.

I asked about the first (the rate) but I think you answered about the second (volume) :smile:.
So I wanted to know if the capacity (rate) is fixed or variable...

> If load management is turned on, it will also respect the capacity limits of the network.

> No. If there is no excess solar PV production, there is nothing to buffer.

:worried: I think we have a misunderstanding here... The buffering strategies for both EV and heat pumps were as follows in my mind (and those of the client):

* If the network allows it, start buffering (heat for HPs and electricity for EV). This buffering is not restricted to local production (currently only solar which should get priority) but can also include electricity from the rest of the grid. @antw can you give an estimate of how complex/time-consuming it would be to incorporate this?

@grdw please take note!

> Capping will cause a solar PV technology to limit its production in the event that this energy would be returned to the grid.

I think this will do for the moment but we should improve this once the calculator is better. We can still limit the amount of capping with a slider right?

> Can you provide an example?

Say the user selects the following two options from the interface as described in https://github.com/quintel/etmoses/issues/212:
* Postponing of individual base-load
* Saving of aggregated base-load

Does the calculator execute the first 'strategy', then re-calculate the effects on the load (including possible preventing of congestions) and then execute the second strategy?

Or does the calculator execute the two strategies (rather behaviours of technologies) right after each other and only then re-calculates the effects on the load (the green curve)?

**Comment by antw** [comment]
> I asked about the first (the rate) but I think you answered about the second (volume) :smile:.
> So I wanted to know if the capacity (rate) is fixed or variable...

I don't think there's a mix-up: the amount by which a P2P battery may charge, or discharge, in each time-step is between zero and the **capacity** (not volume) of the technology.

> I think we have a misunderstanding here... The buffering strategies for both EV and heat pumps were as follows in my mind (and those of the client):
>
> If the network allows it, start buffering (heat for HPs and electricity for EV). This buffering is not restricted to local production

[#118](https://github.com/quintel/etmoses/issues/118#issue-76374952) and [#66](https://github.com/quintel/etmoses/issues/66) both describe the spare EV volume being used to store *excess* energy. EV will always pull from the grid, if necessary, when its profile requires more energy than is presently stored.

> @antw can you give an estimate of how complex/time-consuming it would be to incorporate this?

It's hard to say. We would need to add a third "type" of consumption to the network, which would have knock-on effects for all technologies. Like other changes to the calculator, I'd prefer to try to tackle this at the same time as subnet awareness, *unless* it is particularly urgent or important.

> I think this will do for the moment but we should improve this once the calculator is better. We can still limit the amount of capping with a slider right?

Not presently. The idea [only came up recently](https://github.com/quintel/etmoses/issues/212#issue-93780189) (as far as I know), so wasn't part of the implementation. I do not think it will be particularly hard, especially if the capping percentage is an attribute of the technology instead of being global.

> Does the calculator execute the first 'strategy', then re-calculate the effects on the load (including possible preventing of congestions) and then execute the second strategy?

If I understand correctly, you're asking if the first strategy will affect the outcome of the second strategy? If so: yes.

There is a [pre-determined order in which they are calculated](https://github.com/quintel/etmoses/blob/master/app/models/calculation/context.rb#L58-L65). Technologies at the "top" will affect those beneath them:

* "Static" (normal) technologies
* Saving
* Capping
* EV
* Pre-emption ("flexibility buffering")
* Deferrables ("flexibility postponing")
* P2P batteries
* P2H
* P2G

**Comment by ChaelKruip** [comment]
Closing.
