### ISSUE TITLE
To what extend is saving and postponing currently supported?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#228]
@grdw is working on allowing the user to activate flexibility options per technology. One of the questions that came up is 'how are the flexible and inflexible part of the base-load profiles currently used?'.

To clarify, the expected behaviour for aggregated base-load (EDSN) profiles is as follows:

If the 'saving' strategy is selected in the front-end, the inflexible part of the base-load profile is used a mandatory load. The flexible part can be 'saved' if there is a congestion-event somewhere higher up in the network. This means that if a part of the network is congested, we should look at all the end-points that are underneath the problem and reduce ('save') the flexible part of their base-load sufficiently to solve the issue.

For individual base-load profiles, the behaviour is similar but instead of reducing ('saving') the flexible part of the load to the needed extent, the flexible load is postponed to the next time-step. If it would not result in congestion, the postponed load is put on the grid. If there is not enough 'room' on the network to accommodate the postponed load, it is postponed for another time-step. Postponing can only happen a maximum number of time-steps (3 hours = 12 steps is the current limit).

@antw does this conform with your expectations on the matter? Can you give us some insights on what still needs to be done to allow the behaviour described above?

**Comment by antw** [comment]
> @antw does this conform with your expectations on the matter?

The Network module supports the described technology behaviours, but still needs to be told to use them.

You're correct that postponing has [a hard-coded limit of 12 frames/steps](https://github.com/quintel/etmoses/blob/e2a1c1189330c140c9192e8d8471c3e0e91d88a2/app/models/network/deferrable_consumer.rb#L102), which equates to three hours in most LES'. This value could be changed – or even be provided by the user – if desired.

> Can you give us some insights on what still needs to be done to allow the behaviour described above?

For individual base-load profiles (no separate flexible and inflexible components), the technology should `behavior` needs to be "deferrable_consumer". I think the best option would be to have separate technologies for "combined" and "aggregated" base loads, but I don't know how feasible this is. Perhaps something like "large_units_base_load" and "small_units_base_load"?

For separate flexible and inflexible base-loads, I think there is a bit more work needed. The Network simulation needs to see these as two separate technologies: one for the flexible part, and one for the inflexible. I would do that somewhere in [TreeToGraph](https://github.com/quintel/etmoses/blob/e2a1c1189330c140c9192e8d8471c3e0e91d88a2/app/models/tree_to_graph.rb#L47). The combined base load technology needs to be split into two: one with the flexible profile and a "behavior" attribute set to `optional_consumer`; and one with the inflexible profile, and a behavior of `nil`.

I would very much like to keep the names of technologies and profiles out of the *code*. Perhaps the behavior could be specified with the `LoadCurveComponent` instance:

```ruby
class LoadCurveComponent
  def behavior
    case curve_type
      when 'flex'     then :optional_consumer
      when 'combined' then :deferrable_consumer
      # "else nil" is implied
    end
  end
end
```

(BTW: the default load profile component "type" should probably be `nil` rather than `"flex"`).

Let me know if anything is unclear. I can take this on myself (tomorrow) if you want?
