### ISSUE TITLE
Discussion: Electric vehicle behaviour

### ISSUE THREAD

**Issue by antw** [quintel/etmoses#234]
Following on from #222, "Questions about load management":

>> I think we have a misunderstanding here... The buffering strategies for both EV and heat pumps were as follows in my mind (and those of the client):
>>
>> If the network allows it, start buffering (heat for HPs and electricity for EV). This buffering is not restricted to local production
>
>#118 and #66 both describe the spare EV volume being used to store excess energy. EV will always pull from the grid, if necessary, when its profile requires more energy than is presently stored.

My interpretation of the above is that there are three ways in which an electric vehicle may behave:

* **Storage and load management disabled**: The EV will charge only as much as is required for its next journey. The load is *mandatory* and may be taken from the grid is there is insufficient local production. The spare capacity of the battery remains unused.

* **Storage enabled, load management disabled**: The EV will charge to meet the needs of its next journey. This load is mandatory and may come from the grid.

  The remaining volume of the battery may be used like a P2P battery: storing and discharging energy as required. This "spare" volume may be charged using excess production from within the LES, *or* energy the grid, and may exceed the capacity of parent transformers.

* **Storage enabled, load management enabled**: As above, except that the "spare" volume will not charge if doing so will exceed the capacity constraints of parent transformers.

However...

> In other words, if there is no local (PV) production, I would expect the following:
>
> -- Storage strategy for EV enabled: EV only charges when mandatory (to make the next trip)
> -- Buffering strategy for EV enabled: EV starts charging as soon as returned from trip (if the network allows it)

This suggests that there are only *two* EV behaviours:

* **Storage**: described above as "Storage and load management disabled"
* **Storage and buffering**: described above as "Storage enabled, load management enabled"

Could someone please clarify which is correct? As of today, EV will be able to charge its spare volume using the grid, but I need to figure out what other changes I still need to make...

**Comment by ChaelKruip** [comment]
@antw thanks for pointing out these contradicting and confusing descriptions. I'll do my best to clarify.

I think there are four possible combinations in total (the three you have mentioned above plus "Storage disable, load management enabled"). I expect the behaviour to be as follows:

* **Storage and load management disabled:** exactly as you describe

* **Storage enabled, load management disabled:** The EV will charge to meet the needs of its next journey. This load is mandatory and may come from the grid (even if it exceeds the capacity of parent transformers).

The remaining volume of the battery may be used like a P2P battery: storing and discharging energy as required. This "spare" volume may be charged using excess production from within the LES **only**. The EV discharges when local (behind the connection) demand is larger than production again. It does not discharge more than the mandatory minimum fraction of the tank (as given by the profile) allows.

NOTE: Once we have 'subnet awareness' we might be able to discharge the possible extra charge in the EV *also* if neighbouring nodes (one level up for instance) have demand.

* **Storage disabled, load management enabled:** 
The EV will charge to meet the needs of its next journey. This load is mandatory and may come from the grid (even if it exceeds the capacity of parent transformers).

**If the network allows it** (if it does not lead to congestion of any parent transformers) the charging is done as soon as possible after the vehicle returns from the trip. Both local production (priority) and electricity from the grid can be used. Because it is not yet known how full the battery should be for the next trip (that is only encoded in the profile later on), the EV should load to 100%. Because of this, https://github.com/quintel/etmoses/issues/131 becomes more relevant again.

The EV only discharges by making a trip.

This 'buffering' strategy has as its main purpose to prevent transformer congestion. It tries to do so by 'preemptively' charging whenever the network has some spare capacity. In this sense, it tries to never end up in the 'mandatory charging' regime.

* **Storage enabled, load management enabled:** I have no idea what the behaviour should be. I think the behaviour should be equal to the one above.

**Comment by ChaelKruip** [comment]
To prevent confusion (sorry again) I think we should stop referring to 'storage' and 'load management' to refer to the strategies described above. 

I think "Prioritise use of local (solar PV) production" and "Buffering for EV" are better terms.

**Comment by ChaelKruip** [comment]
Including @jorisberkhout @grdw

**Comment by antw** [comment]
Thanks @ChaelKruip, that's very helpful. The changes needed are very small.

> To prevent confusion (sorry again) I think we should stop referring to 'storage' and 'load management' to refer to the strategies described above.

:+1: I avoided using the term "buffering" in the past because we already had a technology called a "[Buffer](https://github.com/quintel/etmoses/blob/ae2013ec9275e96bcb65b948a06215d6085a85b7/app/models/network/buffer.rb)", which serves as our implementation of power-to-heat. I'm going to change the name of that technology, and will refer to "storage" and "buffering" from now on.

**Comment by ChaelKruip** [comment]
> Thanks @ChaelKruip, that's very helpful. The changes needed are very small.

:smile: :+1:
