### ISSUE TITLE
The wholesome load management issue

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#245]
**Trying to make sense of it all**

There are still some strategies which are currently not doing the right thing.

Those are:
- [x] **Saving of aggregated base-load**
- [ ] **Postponing of individual base-load**
   - [ ] #249 
- [x] **Buffering of local PV excess in heat pumps**
- [x] **Buffering of local PV excess in EV**
   - [x] Question #247 

Including #251

**Comment by antw** [comment]
> * Saving of aggregated base-load

This is implemented as OptionalConsumer. As per [my comment in #246](https://github.com/quintel/etmoses/issues/246#issuecomment-125635625), we have yet to split the base load into two separate technologies in the network calculation.

> * Postponing of individual base-load
> * Buffering of local PV excess in EV
> * Buffering of local PV excess in heat pumps

All three have been implemented for some time (2+ months). I was making some adjustments to these last week, so I know for sure that they work. The front-end checkboxes need to be enabled, but the network technology classes otherwise work just fine.

Postponing → [DeferrableConsumer](https://github.com/quintel/etmoses/blob/a8dd8146afb361328226d11a5221010b357a9eb5/app/models/network/technologies/deferrable_consumer.rb)
EV buffering → [ElectricVehicle](https://github.com/quintel/etmoses/blob/a8dd8146afb361328226d11a5221010b357a9eb5/app/models/network/technologies/electric_vehicle.rb)
Heat pump buffering → [Buffer](https://github.com/quintel/etmoses/blob/a8dd8146afb361328226d11a5221010b357a9eb5/app/models/network/technologies/buffer.rb)

**Comment by grdw** [comment]
Ah okay. Chael and I were talking about this a lot. And he made it sound like there was still something needed to be implemented.
