### ISSUE TITLE
Updating documentation about new features

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#255]
Copied from trello card.

@antw @ChaelKruip what is the usual place documentation is written?

Do we use the general github wiki?

**Comment by antw** [comment]
I've started using the [ETMoses GitHub wiki](https://github.com/quintel/etmoses/wiki) for "plain language" descriptions of the technical aspects of the project. It doesn't have much at the moment, though.

Information aimed at end-users (customers) tends to go in the [documentation repository](https://github.com/quintel/documentation). Personally, I think *project-specific* docs for end-users should also go in the project wiki – rather than the documentation repository – but that's not my call to make.

**Comment by grdw** [comment]
> Personally, I think project-specific docs for end-users should also go in the project wiki – rather than the documentation repository – but that's not my call to make.

I agree.

**Comment by ChaelKruip** [comment]
> @antw @ChaelKruip what is the usual place documentation is written?

I've only written user documentation in the documentation repo (as @antw mentioned above). I agree with @antw that technical documentation should go in the project wiki. 

What I would like to do in the coming weeks is update/extend the user documentation and incorporate it into the front-end.

**Comment by ChaelKruip** [comment]
> Personally, I think project-specific docs for end-users should also go in the project wiki – rather than the documentation repository – but that's not my call to make.

I agree but have not been practicing it :blush: I'll correct my mistakes ASAP
