### ISSUE TITLE
Technology functions could be more intuitive/physical

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#276]
This is a bit of a vague issue so bear with me :smile: 

@grdw and myself are having some trouble understanding the workings of some of the methods associated with technology types. For example, the [production_at method](https://github.com/quintel/etmoses/blob/master/app/models/network/technologies/buffer.rb#L22-L29) in `buffer.rb` is quite abstract to the uninitiated (me :stuck_out_tongue: ). I'll give an example of what I would expect to find in such methods. If the code would reflect this more physical description a bit more, that would help me to validate the behaviour and to assist @grdw again in extending/improving it. I think it could also improve chances of outsiders adding to the code at some point.

Specifically, I would expect methods in a 'technology class' to refer to (some of) the following physical entities:
* Maximum Input Capacity [kW]: the amount of energy that can be converted per unit of time
* Maximum Output Capacity [kW]: the amount of energy that can be outputted per unit of time
* Number of units [number]: self-explanatory
* Storage volume [kWh]: the energy that can be stored in the tank or battery
* Time-step [h]: 1 if hourly profiles, 0.25 if quarterly data (or equivalently, the `frames_per_hour` which is the reciprocal)
* Load [kW]: the effect on the network

In my mind, production of electricity (e.g., solar PV) in time-step 't' would typically conform to the following formula:
```
Production(t) [kWh] = Output-Capacity(t) [kW] * Number-of-units * Time-step [h]
```
where Output-Capacity(t) can be between 0 and Maximum Output Capacity. The load [kW] would then be equal to Output-Capacity(t).

For consuming technologies (e.g., heat pumps), the consumption of electricity would follow a similar formula:
```
Consumption(t) [kWh] = Input-Capacity(t) [kW] * Number-of-units * Time-step [h]
```
where Input-Capacity(t) can be between 0 and Maximum Input Capacity. The load [kW] would then be equal to Input-Capacity(t).

Although I believe that the methods actually work this way, I find it difficult to 'see' that and therefore I have difficulties assisting @grdw in writing specs et cetera. @antw do you see merit in a more physical formulation of some of the methods in ETMoses or is the current level of abstraction necessary?

**Comment by ChaelKruip** [comment]
Including @dennisschoenmakers @grdw

**Comment by antw** [comment]
Many of the methods exist in one form or another already:

* **Maximum Input Capacity [kW] / Maximum Output Capacity [kW]**: [Technology#capacity](https://github.com/quintel/etmoses/blob/6eebc9a9e0b58e257d27cfda935a78e9692aba37/app/models/network/technologies/generic.rb#L76-L78)
  Currently input and output capacities are assumed to be the same.

* **Number of units [number]**: Technology#units

* **Storage volume [kWh]**: [Technology#volume](https://github.com/quintel/etmoses/blob/6eebc9a9e0b58e257d27cfda935a78e9692aba37/app/models/network/technologies/generic.rb#L80-L100)
  The `volume` returns an odd-looking value: "kilowatts per frame" which is intended to neatly handle the conversion between kW loads and kWh volumes. You could get the kWh value by running `technology.installed.volume` or `technology.volume * technology.profile.resolution`.

* **Time-step [h]**: Profile#resolution (`technology.profile.resolution`)

* **Load [kW]**: Technology#load_at

Perhaps part of the confusion is because `production_at` and `*_consumption_at` methods return values in kW rather than – as you seem to expect – kWh. These methods describe the *load* placed on the network in each frame. Perhaps there is merit in renaming these so as to be less ambiguous?

These methods are part of the calculation process and should not be taken literally. If you want to query the actual load of a technology after the LES has been calculated, please call `Technology#load_at`. A positive value indicates consumption, and negative is production.

**Comment by ChaelKruip** [comment]
@antw thanks for the clarifications!

 > Perhaps there is merit in renaming these so as to be less ambiguous?

Yes please!

**Comment by antw** [comment]
Also: in writing tests, I think I'd encourage not looking directly at the technologies except in very low-level unit tests. They act like strategies and are meant to work *with* the calculator (`PullConsumption` and `TechnologyPath`). Instead, build a small network (@grdw has [already done something like this](https://github.com/quintel/etmoses/blob/master/spec/controllers/testing_grounds_load_management_controller_spec.rb)), compute the LES, and look at the resulting load *on the nodes*.

Case in point: If you have an LES with one-hour per time-step, a battery which currently has 2kWh stored, but there is nothing which wants to consume that energy, what is the expected behaviour? The battery should not charge or discharge, and the node to which it belongs will have a load of 0.0. Indeed, if you call `node.load_at` you'll see that the load was zero.

But if you ask the battery what it's consumption and production was, it's going to show you something different:

* `production_at`: 2.0
* `mandatory_consumption_at`: 0.0
* `conditional_consumption_at`: 2.0

This translates as: "I have 2kW available for discharge (*production_at*), but if nothing wants it, please give it back (*conditional_consumption_at*)".

The real story is a little more complicated, since the battery may want to charge if it isn't already full, and the production and consumption of a real battery will be limited by its capacity, but hopefully you get the general idea.

>  For example, the production_at method in buffer.rb is quite abstract to the uninitiated (me :stuck_out_tongue: ).

Buffer is a particularly odd case and I agree it's confusing. I think the new one (with availability profiles) will very closely resemble the ElectricVehicle and the current Buffer can be thrown away.

**Comment by ChaelKruip** [comment]
Closing.
