### ISSUE TITLE
Could load colours be improved?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#279]
Now the difference is sometimes hard to spot:

![image](https://cloud.githubusercontent.com/assets/104830/9380470/ad8d2c08-4730-11e5-9192-9466e643158d.png)

Especially when the green is *behind* the blue:

![image](https://cloud.githubusercontent.com/assets/104830/9380474/b5577eac-4730-11e5-8346-ad6c65a99dff.png)

Perhaps we could use more 'complementary colours' such as:

![image](https://cloud.githubusercontent.com/assets/104830/9380463/a30c2c84-4730-11e5-8944-90bf941c4647.png)

**Comment by antw** [comment]
I think blue/orange is a no-go since many colourblind people can't see much difference between the two. I have removed the blue shading when the green "strategies" line is shown; is this better?

<img width="273" alt="screen shot 2015-08-20 at 14 16 11" src="https://cloud.githubusercontent.com/assets/4383/9384124/0b92bcd6-4746-11e5-98a1-36322a1f9349.png">

I think there's still room for improvement, but this is at least a bit more readable.

**Comment by ChaelKruip** [comment]
> is this better?

Yes. Better indeed. Let's pick this up at some later time. Putting on-hold for now.
