### ISSUE TITLE
For some LESs EV storage is not behaving as expected

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#280]
For [this LES](http://beta.moses.et-model.com/testing_grounds/198), the number of EV and solar PV panels is such that I would expect to see the effects of the 'storage in EV' strategy. But in all but one day, the results are equal blue and green curves.

**Comment by antw** [comment]
Enabling EV storage but not buffering means the EV charges from local excesses only ([per #234](https://github.com/quintel/etmoses/issues/234#issuecomment-123210565)). Enable buffering to take energy from the grid when there is available network capacity, or add more solar panels to charge the cars.

[See this example](http://beta.moses.et-model.com/testing_grounds/202): Zoom in on Household 1 on "5th Feb – 11 Feb" for a particularly stark example. I increased the number of PV panels from 26 to 64.

**Comment by ChaelKruip** [comment]
But how can it be that if I connect the same number of PV and EV to a connection in [a LES with another topology (the default)](http://beta.moses.et-model.com/testing_grounds/201) I get completely different behaviour?
These technologies
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9383173/1bf6e524-4747-11e5-9dd7-2e928e7b874b.png)
lead to
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9383179/285bbe5c-4747-11e5-9ee5-c54f41380e76.png)

For reference: the original connection has:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9383201/5e4e4f34-4747-11e5-97c4-d53b22fdd6c8.png)
with no result:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9383207/6f6449fe-4747-11e5-83e4-382412c229a7.png)

**Comment by ChaelKruip** [comment]
Are the different constraints in the topology to blame? But that would be weird as the technologies share a connection in both cases!

**Comment by antw** [comment]
The two networks are not equivalent. Your "default topology" network contains only the three technologies (base load, PV, and EV) on one node. The original example includes technologies on the other household nodes.

The difference is almost certainly caused by interactions with those technologies in the *other* nodes. It may be that the excess solar PV from "Household 1" is consumed by higher-priority technologies in "Household 2" (e.g. the base load).

Take a look at [LES 203](http://beta.moses.et-model.com/testing_grounds/203) – I removed all the technologies from the other nodes; the load graph now looks identical to the one from the default testing ground.

**Comment by ChaelKruip** [comment]
>  I removed all the technologies from the other nodes; the load graph now looks identical to the one from the default testing ground.

I see. Thanks for clarifying and sorry for my confusion.

**Comment by antw** [comment]
> Thanks for clarifying and sorry for my confusion.

:grin:

**Comment by ChaelKruip** [comment]
> :grin:

I guess I deserved that :stuck_out_tongue:
