### ISSUE TITLE
P2G and P2H do not show up in ETMoses although they are included in scaled scenario

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#287]
In the case of P2G this is likely due to scaling of the slider caps (max = 100 for a normal scenario). Perhaps we can allow a scaled scenario to have at least 2 P2H installations? @antw do we have an elegant way of limiting the scaling of the max slider setting?

In the case of P2H I don't see why they don't show up... The number of units in ETE seem to be correct.

**Comment by ChaelKruip** [comment]
Moving to February Deploy

**Comment by jorisberkhout** [comment]
Moving to 'Storage' milestone.

**Comment by jorisberkhout** [comment]
Moving to Deploy milestone.

**Comment by jorisberkhout** [comment]
@ChaelKruip , looking at this issue again, I think this is not deploy critical. If you agree, let's remove the milestone.

**Comment by ChaelKruip** [comment]
> If you agree, let's remove the milestone.

Agree

**Comment by antw** [comment]
This appears to be resolved. Both P2H and P2G technologies do appear in an LES, provided the original ETM scenario has some installed.

One thing I did notice is that the number of P2G units is quite low. In a scenario scaled to 3000 households you can only install at most 4 P2G. This is because the full-scale scenario [has a hard cap of 10000 units](https://github.com/quintel/etsource/blob/master/inputs/flexibility/energy/number_of_energy_flexibility_p2g_electricity.ad#L6).

![screen shot 2016-05-03 at 14 46 41](https://cloud.githubusercontent.com/assets/4383/14985112/e0c9db48-113d-11e6-888f-8ebca891b48a.png)

I'll close this because there seems to be no problem in ETMoses.
