### ISSUE TITLE
Deprecated profiles should not be automatically chosen for new scenarios

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#288]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9438819/c2329c86-4a61-11e5-8211-44a5e5408349.png)

**Comment by antw** [comment]
A quick and easy solution is to remove "Household" from the permitted technologies list when editing the profile. However, if a user goes back and edits this old LES, they won't be able to reselect these older profiles and a different profile will likely be selected in the drop-down.

Ideally, we would add a boolean `autoselect` column to the `technology_profiles` table (that defines the permitted technologies list) which determines if the profile can be chosen automatically, or only if the user manually selects it.

**Comment by ChaelKruip** [comment]
> Ideally, we would add a boolean autoselect column 

If not too difficult I would prefer this as well.

**Comment by grdw** [comment]
I deployed a fix for this on beta.

Though it now doesn't show the `deprecated` profiles in the select box once somebody has those in their LES. I'll look into this.

**Comment by grdw** [comment]
Hmm. I'm just seeing that the `technology_profiles`-associations are gone for deprecated household profiles? I'll close this. Re-open if this is not the intention or if something is not working.

**Comment by antw** [comment]
> I'm just seeing that the technology_profiles-associations are gone for deprecated household profiles?

I deleted them last week in a migration. Many of the old profiles weren't just deprecated, they didn't work with the latest implementation of heat pumps (use+availability) or base loads (flex+inflex).

I think perhaps we need a more considered approach to the difference between "deprecated" and "not working". Instead of deprecating broken profiles, *in the future* we should prefer to upload newer versions of them, as this will prevent older LES' from becoming obsolete. I appreciate that wasn't possible on this occasion due to time constraints and the addition of new types of profiles.

I would also still prefer an explicit `deprecated` column or something similar; [checking if the profile key contains the `deprecated` substring](https://github.com/quintel/etmoses/blob/5c020cccf2ed50516eafda8a84ef990997972c0c/app/models/load_profile.rb#L22-L24) seems pretty fragile and not "user discoverable". If `deprecated` is `true`, it shouldn't appear in the drop-down for new testing grounds, and should only appear when editing if the profile was *already* selected.
