### ISSUE TITLE
If creating business case fails, the user should get a proper warning

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#307]
Now you see:
![beta_moses_et-model_com_testing_grounds_209_business_cases](https://cloud.githubusercontent.com/assets/1303760/9467576/079dcb84-4b3d-11e5-8c4a-1d9ad46d1773.png)

**Comment by ChaelKruip** [comment]
For [this scenario](http://beta.moses.et-model.com/testing_grounds/209) I got an error message when making a business case with Market Model 3. After changing the MM in the database to '8', the [business case overview](http://beta.moses.et-model.com/testing_grounds/209/business_cases/1) works fine! Even when I set the MM to '3' in the database! :confused:

**Comment by grdw** [comment]
I also noticed that it sometimes takes quite a while to calculate a business case. It might be that the server just timed out?

**Comment by antw** [comment]
> I also noticed that it sometimes takes quite a while to calculate a business case. It might be that the server just timed out?

I found business cases to be reasonably fast, but what slows everything down is the need to calculate the network loads first. Since we're not storing the network loads anywhere we have to do that before we can calculate the business case. This is on my radar to fix.

On the testing_grounds/show page we show a "please wait..." message while the loads are being calculated, and then show the topology when it's ready.

**Comment by grdw** [comment]
Still needs to be implemented eventhough the whole process is in a background job.

**Comment by ChaelKruip** [comment]
@grdw can we close this?

**Comment by grdw** [comment]
I'm closing this for now. Usually something really serious is broken when it doesn't calculate in which case an issue should be made. The user however doesn't really receive any 'correct feedback' if it didn't calculate. Except for the fact that the business case isn't available. Which is enough for the fact that the error message is usually way to technical for a user to understand.
