### ISSUE TITLE
No transactions happen although there is electricity consumption

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#315]
In [this LES](http://beta.moses.et-model.com/testing_grounds/215/business_cases/2), I have used the 'simple market' market model and a minimalistic setup of one household, one building and one solar panel. There is consumption on the HV net:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9490411/edf73d0e-4be7-11e5-937d-f150fb7cc4f5.png)
yet the financial summary table only shows zero's:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9490420/005fabde-4be8-11e5-8dc0-406d8fde8e49.png)

**Comment by antw** [comment]
There are four interactions defined in this market model:
  
* **customer** pays **supplier** for `kWh`
* **customer** pays **government** for `kWh`
* **customer** pays **system operator** for `kW_contracted`
* **supplier** pays **producer** for `kWh`

I see two problems with this business case:

1. **customer** isn't a stakeholder of any node in the topology. **system operator** is the stakeholder for all nodes except the HV network.
2. The `kW_contracted` measure isn't implemented.

The solutions to this are:

1. Either add an extra node beneath the MV-LV Trafos owned by the **customer** and connect the technologies to these. [Here's my version which does this](http://beta.moses.et-model.com/testing_grounds/223/business_cases/8) ([LES](http://beta.moses.et-model.com/testing_grounds/223)). Or, we should add support for a node to have multiple stakeholders.

  Multiple stakeholders seems like a more elegant solution, since it makes sense that the costs associated with a node may be paid by different people, e.g. operating costs are paid by the S/O, kWh by the customer.

2. To implement `kW_contracted` there needs to be an explanation of what it is, how it should work, and what data the user will have to provide to configure it. My understanding is that it uses a payment scale ([with steps which increase the price as certain criteria are reached](https://github.com/quintel/etmoses/issues/191#issuecomment-117575397)) but that's all I know at this stage...

**Comment by ChaelKruip** [comment]
> customer isn't a stakeholder of any node in the topology

How silly of me! Thanks for pointing that out.

> Multiple stakeholders seems like a more elegant solution

Yes and no. I am worried about how we then assign cost. Is the customer paying for the O&M cost or the SO?

> To implement `kW_contracted` there needs to be an explanation of what it is

I'll make a ticket for that.

**Comment by antw** [comment]
> Yes and no. I am worried about how we then assign cost. Is the customer paying for the O&M cost or the SO?

I agree this needs a bit more thought and experimentation. However, I think this specific example isn't a problem: the customer would only pay the operating costs if you explicitly set up a payment rule to that effect. Instead, the model is likely to be:

* **customer** → **supplier** (`kWh_consumed`)
* **system operator** → **???** (`operating_costs`)

In this way, you can have two stakeholders responsible for different costs on same node.

The stakeholder is not automatically responsible for paying the operating costs of a node: without an interaction we wouldn't know who they are be paying. Perhaps it *can* be made automatic, if desired, but you're right that we wouldn't be able to pursue multiple stakeholders per node if we do this.
