### ISSUE TITLE
When you've removed all technologies, you can't add a new one.

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#348]
The first question that should arise here: why would you do this? 

Therefor, will fix this when time is on our side.

**Comment by JeroenvdLogt** [comment]
I agree that this is of less priority than other issues. 
Why a user would do this is because the wanted situation can be completely different than after automatic assiging by ET Moses. (slighlty different configuration per "streng van trafo's ". For nation wide cases this is not applicable but for some specific usecases it is.

**Comment by grdw** [comment]
Will be solved with the new interface #605
