### ISSUE TITLE
How shall we call the options that users can choose for the behaviour of technologies?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#349]
Currently, the user is asked to "Pick a strategy" (see https://github.com/quintel/etmoses/issues/337#issuecomment-137450841)

@antw suggests to use "Choose network features" as an alternative

I feel "strategies" is an accurate description for what the user can choose there because it deals with *how* to use the technologies in order to attain some goal but perhaps my mind is warped too much by exposure to ETMoses to think as a normal user though...

I am curious to hear your opinions @jorisberkhout @grdw @dennisschoenmakers @AlexanderWirtz!

**Comment by antw** [comment]
We're [bikeshedding](https://en.wikipedia.org/wiki/Parkinson%27s_law_of_triviality) pretty hard here. :stuck_out_tongue:

* **Choose technology behaviour**
* Select technology features
* Customise technology behaviour  _(bonus points for that option having *two* words which have different British and American English spellings)_
* Choose network features

I dislike "strategies" for being a technical term when a more general one can do the job just as well. The application could be pretty overwhelming for an ordinary user (i.e. people who haven't had frequent meetings with us); the less new stuff we throw at them, the more attention they'll be able to give to the main features. We need to hold their hands, guide them through the process, and use plain English (or Dutch) so that the application is approachable and easy-to-use. If it's too difficult, they'll give up and move on.

The word "strategies", specifically, isn't going to cause a user to give up, but they might when we use "strategies" and "nodes" and "edges", and go on to say "graph" – but not when referring to a chart. Then they saw a load chart with a *negative* number, needed to understand the difference between storage and buffering in electric vehicles, was forced to learn YAML to edit the topology, and, and...

I don't care *that* much about the wording of this button; it's the overall user experience we need to be mindful of.

* See "[Don't make me think!](https://books.google.co.uk/books?id=QlduAgAAQBAJ&lpg=PP1&pg=PA11#v=onepage&q&f=false)"

**Comment by ChaelKruip** [comment]
> We're bikeshedding pretty hard here.

Haha, indeed. 

I opened this issue half for laughs but I really appreciate the points that @antw is making here. Perhaps we can have a fresh mind (Rob Terwel?) look over ETMoses soon and let him point out everything that he doesn't intuitively get?

**Comment by grdw** [comment]
Is "strategies" really a technical term? I don't feel that way, but I wouldn't mind if it's left out due to better alternatives.

**Comment by ChaelKruip** [comment]
I say we go with "Customise technology behaviour".
Re-open this if you feel strongly otherwise.
