### ISSUE TITLE
Calculate business case in background job

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#359]
In the current 'ajax' #358 situation. The market model and topology can be editied, but the business case has to change accordingly. Recalculating the business case costs a lot of time. 

@ChaelKruip Chael suggested to move the freeform rules to the market model. Which is fine with me.
This way we can remove the business case tab from the edit screen and calculate once the user is on the LES-page.

**Comment by antw** [comment]
To take this a bit further... it would be nice to also do the network calculation in a background job. Currently the LES loads with a "please wait..." message while an XHR request is sent to Moses for the load data.

This XHR request hits `testing_grounds/:id/data` where the loads are calculated in the Rails process. This is an *okay* solution provided we have enough processes, but moving this to a background worker – and having the front-end poll to see when the calculation is finished – would be a better solution.

Something like:

```
GET testing_grounds/1/data
{ pending: true }

... time passes ...

GET testing_grounds/1/data
{ graph: {,...}, technologies: {,...} }
```

> Recalculating the business case costs a lot of time.

Mostly because it has to calculate the network first. It's going to get even worse when the flexibility measures get hooked up (#330). :cry: 

We shall really have to get some form of caching sorted for the network once the major issues are out of the way.

**Comment by grdw** [comment]
> To take this a bit further... it would be nice to also do the network calculation in a background job. 

Do you have any preference for a background processor? 

Resque / DelayedJob / Sidekiq / ActiveJob ?

**Comment by grdw** [comment]
> and having the front-end poll 

This is in my experience still a tricky one. Without using `setInterval` how could this be done nicely?

**Comment by antw** [comment]
> Do you have any preference for a background processor? Resque / DelayedJob / Sidekiq / ActiveJob ?

*Maybe* Resque? In truth I don't have a huge amount of experience with any of them; so if you have a preference, I'm happy with whatever you choose.

> Without using setInterval how could this be done nicely?

WebSocket, but that feels like overkill. `setInterval`/`setTimeout` is probably how I'd have done it:

```javascript
function fetchLESData(callback) {
  $.ajax(...).success(function(data) {
    if (data.pending) {
      // Maybe return something other than 200 OK?
      window.setTimeout(function() { fetchLESData(callback) }, 1000);
    } else {
      callback(data);
    }
  })
}
```
