### ISSUE TITLE
Technologies without profiles should not inherit defaults from previously selected technologies

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#409]
I had a heat pump. Now the P2H unit has the HP defaults...
![etmoses](https://cloud.githubusercontent.com/assets/1303760/9905233/09d766f0-5c84-11e5-8093-bea720ff1091.png)

**Comment by grdw** [comment]
Discussed this with @ChaelKruip . Closing.

**Comment by grdw** [comment]
I'll check why some technologies are responding weird like Power-to-heat

**Comment by grdw** [comment]
Allright, this problem is very simple. The defaults are attached to the `profile` options. Since `Power-to-gas` doesn't have any profiles it can't read the defaults. 

My solution would be is to hide `Power to gas` from the database for now. Or we could limit the visibility for Technologies without load profiles.

**Comment by grdw** [comment]
> Allright, this problem is very simple. The defaults are attached as data-attributes in the HTML, to the profile options. Since Power-to-gas doesn't have any profiles it also can't read the defaults.

I managed to turn the defaults blank if a technology doesn't have a set of load profiles.

**Comment by grdw** [comment]
@ChaelKruip fixed, deployed and all! :dancers:

**Comment by ChaelKruip** [comment]
:+1:
