### ISSUE TITLE
Capacities in technology table should be 'electrical'.

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#426]
For heat pumps, the capacity shown now is the heat capacity. It would be more intuitive for the user to see the electrical (input) capacity in the table as this is what the load will be on the network. 

This necessitates that the COP is taken into account in the methods of ETMoses where load and heat production are calculated. 

```
heat_output_capacity [kW] = electrical_input_capacity [kW] * COP
```

**Comment by ChaelKruip** [comment]
Also see  https://github.com/quintel/etmoses/issues/334

**Comment by ChaelKruip** [comment]
This also means that the default HP capacities in the front-end should be adjusted to be:
```
electrical_input_capacity [kW] = heat_output_capacity [kW] / COP
```

**Comment by antw** [comment]
The COP changes are ready to go, albeit without this request. In order to represent the electrical share of heat pumps, it isn't enough to divide the capacity by COP; the volume also has to be altered. Here's an example:

If we have a heat pump with a capacity of 10kW, volume of 2.32kWh, and a COP of 4.0, then the *electrical* capacity is 2.5kW with the remaining 7.5kW coming from other ambient heat. To put it another way: if we fill the tank completely, 25% of the energy in the tank (0.58kWh) comes from electricity, and the remaining amount (1.74kWh) comes from ambient heat.

The use/availability profiles are scaled by the *volume* attribute; if we don't reduce the volume, the network calculation will try to fill the buffer using only electrical energy and the (now reduced) capacity will be insufficient to do so. #434 describes what happens when capacity is too low to fill the tank.

We need to reduce the volume so that we are simulating the electrical part of the technology, and ignore the ambient heat part. This is what I have implemented, and the behaviour is as you'd expect:

**Before**

<img width="550" alt="before" src="https://cloud.githubusercontent.com/assets/4383/10087401/962609b2-630b-11e5-9f30-d159a546e332.png">

**After**

<img width="544" alt="after" src="https://cloud.githubusercontent.com/assets/4383/10087405/9af2d3a8-630b-11e5-9adc-039e114c04ad.png">

**My question is:** are you sure you want to show only the electrical capacity in the technology table? If so, I think that means we should also only show the electrical share of the volume, for consistency and to avoid creating awkward per-attribute exceptions in the code.

**Comment by ChaelKruip** [comment]
> are you sure you want to show only the electrical capacity in the technology table?

Yes.

>  I think that means we should also only show the electrical share of the volume

As discussed with @antw, we will show the heat energy volume.
