### ISSUE TITLE
Buffering with heath pump

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#434]
![buffering heatpump](https://cloud.githubusercontent.com/assets/7781037/10052013/d6c6eee2-6224-11e5-94a6-b9a767ce3b1d.JPG)
I created a node with 31 households (EDSN 1a and 2200 kWh) plus 31 heatpumps 1.63 kW and 100 kWh (just for testing purposes) plus 1 PV installation of - 47.3 kW. The cable (node of 31 households is a child of cable node) has a capacity of 51 kW. 

When I apply buffering in heatpumps it looks like the pump buffers whenever there is no congestion. Only I don't see a reduction when there is congestion on the 51 kW cable. Is there an explenation or is this a bug?

**Comment by antw** [comment]
The heat pumps in this LES have been given custom values for their capacity and volume; the defaults are 10kW and 2.32kWh respectively. The heat pumps in your LES have values of 1.63kW and 1000kWh). If you want to increase the volume of the heat pump, you also have to increase the capacity to compensate, and vice versa.

What's happening in this LES is that the availability profile tells the heat pump "the tank needs to be 6% full at the end of this 15 minute period"). To fill the tank with 60kWh in 15 minutes would require the heat pump to have a capacity of 240kW. Instead, because the capacity of the HP has been set to 1.63kW, they're effectively running at full capacity but are falling short of fulfilling demand by a huge margin. That's why, if you remove the P2H and base load technologies, [the load appears to plateau](https://cloud.githubusercontent.com/assets/4383/10071880/163cf7de-62b5-11e5-8c26-38235ff537f4.png).


[Take a look at my version of your LES here](http://beta.moses.et-model.com/testing_grounds/284) – in which I have reverted the heat pumps back to their original values – to see buffering in action.

<img width="547" alt="screen shot 2015-09-24 at 11 59 15" src="https://cloud.githubusercontent.com/assets/4383/10071754/232d2b18-62b4-11e5-8f13-9b0b44a3c5ab.png">

My understanding is we'll lock one or both of these attributes in the future, to prevent errors such as these.
