### ISSUE TITLE
Business case fails to calculate

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#449]
![screen shot 2015-09-25 at 11 26 28 am](https://cloud.githubusercontent.com/assets/2676542/10097286/5ab4edfe-6378-11e5-8f59-d20269ad1f52.png)

@antw could you maybe explain what this error message means?

**Comment by antw** [comment]
It means there are two (or more) interactions between the same two stakeholders using the same "measure". I actually think this should be permitted, but will require some changes in the Market module before that can happen.

**Comment by antw** [comment]
This comes from our graph library, Turbine, where it would normally make no sense to have multiple edges of the same type between two nodes. For example, in a social graph, if you had:

```
[Person A] –friend–> [Person B]
```

... trying to add a second `friend` edge between `[A]` and `[B]` is at best redundant, and at worst going to result in errors.

The market module is based on a graph because, originally, we wanted to set up relationships such as:

```
[Producer] –kwh_consumed–> [Supplier]
                           [Supplier] –kwh_consumed–> [Customer]
```

This would have allowed the producer to charge the supplier for energy consumed by the customer. Since we added the "applied stakeholder" field, this is not as useful a feature as it once was. It's likely I'll remove the graph structure in favour of something simpler, and in doing so will eliminate the restriction.
