### ISSUE TITLE
QUESTION: is kWh measure superfluous?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#453]
As we already have 'kWh consumed' and 'kWh produced' it might be confusing to also support 'kWh':
![screen shot 2015-09-25 at 13 38 42](https://cloud.githubusercontent.com/assets/1303760/10099541/dcc05164-638a-11e5-8313-4ad887d8db71.png)

To be honest, I don't know what it does exactly...

**Comment by antw** [comment]
I meant to post about this a few days ago and forgot. :blush:

[The KWh measure](https://github.com/quintel/etmoses/blob/de599537eca17f2ae897c33f8ad7f6d074c74958/app/models/market/measures/kwh.rb) is a base class used by KWhProduced and KWhConsumed. If used, it would charge the payer for kWh consumed and refund for kWh produced. I have removed it from the front-end since you can achieve this behaviour more reliably by adding separate "kWh produced" and "kWh consumed" interactions.

**Comment by ChaelKruip** [comment]
:+1:
