### ISSUE TITLE
When changing a technology into household, some things seem to go wrong

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#471]
* The individual profiles are selected even when the group is larger than 30:
![cursor_and_etmoses](https://cloud.githubusercontent.com/assets/1303760/10104464/0bdb97aa-63aa-11e5-8e26-58d46a849cb5.png)
* Some lines containing houses do not want to change (don't allow other options to be selected)

**Comment by grdw** [comment]
It has to do with 'soft' refreshing. Whenever you 'soft' refresh the base load changes into a battery. This is due to the fact that the browser remembers `base_load_edsn` and than tries to find it in a select box without `base_load_edsn` so it assumes the first technology is `base_load_edsn` which is `battery`

**Comment by antw** [comment]
As a temporary fix, I have reverted 680debc5 which is where this issue first arises. The issue I'm seeing is that `$(this).data('type')` always returns the original `type` even after the user has changed it. The result is that any "Household" technology present when the page loads cannot be changed to any other type of technology.

**Comment by ChaelKruip** [comment]
I think the trouble started with the feature that groups of households larger than 30 should get aggregated profiles, whereas smaller groups should get individual profiles. A new technology (`base_load_edsn`) was created which is selected when the group is larger than 30. But this new technology does not occur as a separate option in the selection menu in the front-end (as, to the user, it should look like 'households').

The issue I'm seeing at the moment, however, is that changing technologies does no longer update the capacity (although profiles and volumes are updated correctly).

**Comment by antw** [comment]
> The issue I'm seeing at the moment, however, is that changing technologies does no longer update the capacity (although profiles and volumes are updated correctly).

That's not related to `base_load` or `_edsn`, but because the relevant attribute is now called `electrical_capacity` instead of `capacity`. I have updated the JS.

However, the default heat pump capacity in the database is still 10.0 (it doesn't account for COP, nor can it as the COP comes from ETEngine). The coefficient-of-performance implementation is already feeling very hacky to me; it'll do in the very short-term but I think I'll have to rethink it...

**Comment by ChaelKruip** [comment]
> However, the default heat pump capacity in the database is still 10.0 

Would things break if we would change it to the electrical capacity?

> The coefficient-of-performance implementation is already feeling very hacky to me; it'll do in the very short-term but I think I'll have to rethink it...

Sounds good to me. I think we need a robust and generic way to treat both input and output capacity (and the COP/efficiency that is their ratio). Ideally, these values are all taken from ETE as they are present there and consistent.

**Comment by antw** [comment]
> Would things break if we would change it to the electrical capacity?

Yes, but since the technology won't have a COP defined (since it comes from ETEngine) We would also need to reduce the default volume by the same proportion to compensate. I think I can come up with a better fix for this tomorrow, but would this be good enough for the next 24-48 hours?

**Comment by ChaelKruip** [comment]
> would this be good enough for the next 24-48 hours?

Yes. Let's talk about a better solution next week. For now this will do thanks.

**Comment by grdw** [comment]
Continued at: https://github.com/quintel/etmoses/issues/496
