### ISSUE TITLE
Business case stops loading before being updated

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#479]
When changing a strategy, the business case output shows a 'loading message'. At some point, the loading message is replaced by the business case overview table but the values have not updated yet. After another 10 seconds or so, the values do change to their correct updated value.

It would be more logical if the 'loading message' shows until the updated values are available.

**Comment by antw** [comment]
I'm not sure what's going on with the business case calculation, actually. It seems that since b64bef01 a new job is created every time the front-end polls to see if the market model has been calculated. The reason for that is that a `job_id` now isn't set until the job starts executing – rather than as soon as you submit the request. It may be many seconds before the job starts (depending on the number of workers). This could be the reason you see this behaviour.

I should have caught this when reviewing the pull request. :anguished: 

I have reverted the offending part of the commit. Would be good for @grdw to take a look at https://github.com/quintel/etmoses/commit/49d8c3b4d9d98a4a436e6397cc32f16b767d0c7e to make sure there aren't any unintended side-effects (I doubt there will be).

**Comment by ChaelKruip** [comment]
Thanks @antw!

**Comment by grdw** [comment]
It was like this 49d8c3b before I changed it to the never-ending-job-spawning line of code... don't really know what was causing me to think that this would actually work.
