### ISSUE TITLE
BUG: When comparing market model, the income is incorrectly shown with a minus sign

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#484]
<img width="1315" alt="etmoses" src="https://cloud.githubusercontent.com/assets/1303760/10124903/cd844f8c-6562-11e5-92df-bb5bc4b3ba8e.png">

Weirdly, the cooperation does not have the erroneous minus sign!

**Comment by antw** [comment]
The number in in brackets apparently shows the *difference* in price between the current business case and the comparison case. Is that what you're referring to?

| 20150907_kWpeak value | 20150922_complex_market value | Δ |
| --------------------:| -------------------------:| -------------------:|
| €998,332.65 | €15,436.32 | €982,896.32 | 

*(I would expect the number in brackets to simply be the price in the other LES rather than the difference, but that's just me...)*

**Comment by ChaelKruip** [comment]
It should just show the values indeed. Not the difference.
