### ISSUE TITLE
Household groups larger than 30 should get an aggregated profile

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#500]
Right now, the table still shows the individual profiles if you change another technology (with units > 30) to households.

**Comment by grdw** [comment]
Fixed with: https://github.com/quintel/etmoses/commit/d4576bd53df49b8d77b7fc8dbb76d03804107d14

**Comment by ChaelKruip** [comment]
:+1:

**Comment by antw** [comment]
> Fixed with: d4576bd

* [Use data attribute instead of val()](https://github.com/quintel/etmoses/commit/680debc53973355b553155bdfae857907af0a259)
* [Revert "Use data attribute instead of val()"](https://github.com/quintel/etmoses/commit/07500b1d868a4c623233b54c9cf8c29048cc732e)
* [Use data attribute instead of val()](https://github.com/quintel/etmoses/commit/f77d851b16f40eb6b3406b89d0ab8c12b2efbb51)
* [Fixing edsn bug](https://github.com/quintel/etmoses/commit/d4576bd53df49b8d77b7fc8dbb76d03804107d14)

"[Snip snap snip snap!](https://www.youtube.com/watch?v=OmGgV-2JNnM)" :grinning:
