### ISSUE TITLE
Suggestion: change default behaviour of electric vehicles to something more stupid

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#504]
Similar to #503, the default behaviour of EV should become more stupid IMO. I this case, I think the current default ("load at the latest time possible and only enough for the trip") is not only too smart but also not very realistic. 

My suggested 'stupid default' would be: "load at full capacity when you return from a trip and don't discharge until you drive again."

This is how most people use their EV. Just plug it in when your arrive.

Other than with heat pumps, the availability (which is incorporated in the single profile for EV) still is very useful: it tells the EV how much it can discharge back to the network without jeopardising its next trip which is relevant for the 'Storage of excess PV production' strategy.

@dennisschoenmakers @jorisberkhout @AlexanderWirtz @antw I'm interested in your thoughts on this.

**Comment by antw** [comment]
> My suggested 'stupid default' would be: "load at full capacity when you return from a trip and don't discharge until you drive again."

Charge *when the network has spare capacity* without discharging, is the behaviour you get when you choose:

* Buffering of electricity in PV: **on**
* Storage in EV prioritising local PV: **off**

**Comment by ChaelKruip** [comment]
> Charge when the network has spare capacity without discharging, is the behaviour you get when you choose:

Correct, I am suggesting to start 'buffering' but without any concern for network capacity as the default.

**Comment by antw** [comment]
> I am suggesting to start 'buffering' but without any concern for network capacity as the default.

Understood. :+1:

This is a pretty simple change if you choose to go ahead with it.

**Comment by ChaelKruip** [comment]
assigning @antw

**Comment by ChaelKruip** [comment]
> This is a pretty simple change if you choose to go ahead with it.

Yes please! :+1: 
This one fell off the radar it seems. Ecofys asked me about it today and I didn't know if we did it already.

@antw how much time would this roughly take?

**Comment by antw** [comment]
> how much time would this roughly take?

~1 day. How soon is it needed?

**Comment by ChaelKruip** [comment]
> How soon is it needed?

First thing after the deploy I would say...

**Comment by dennisschoenmakers** [comment]
> @dennisschoenmakers @jorisberkhout @AlexanderWirtz @antw I'm interested in your thoughts on this.

Agree 100% with 100% of all the participants!

**Comment by AlexanderWirtz** [comment]
agree

**Comment by antw** [comment]
> I am suggesting to start 'buffering' but without any concern for network capacity as the default.

Just to clarify a bit further: do you want this new default to *also replace* the current "Buffering of electricity in EV", or to be *in addition* to it? Here are the combinations of strategies supported by EVs:

| Strategy            | Respect net capacity? | Use grid? | Discharge surplus? |
|--------------------:|:---------------------:|:---------:|:------------------:|
| All off (default)   | No                    | No        | No                 |
| Buffering           | Yes                   | Yes       | No                 |
| Storage             | Yes                   | No        | Yes                |
| Buffering + Storage | Yes                   | Yes       | Yes                |
| :zap: New default?  | No                    | Yes       | No                 |

* **Respect net capacity**: Do not exceed the capacity of the network, unless you *have to* in order to charge to the minimum required amount (for driving).

* **Use grid:** May take energy from the grid to charge. When disabled, will only charge using excesses from within the LES (solar PV). Grid energy may always be used to charge to the minimum required amount.

* **Discharge surplus:** Effectively "storage". Surplus energy stored in the battery, which is not required for driving, may be discharged back into the LES for use by other technologies.

--

What I'm not clear on is whether the old "Buffering" strategy should also be removed when we switch to the new default.

The distinction between the new default and "Buffering" is quite small and, I think, necessitates renaming the current version to something like  "Prevent EVs from exceeding network capacity". However, this feels a bit off since we have other techs which also don't exceed network capacity, but don't say so in their strategy names.

**Comment by ChaelKruip** [comment]
> Just to clarify a bit further

Thanks for doing that @antw!

> What I'm not clear on is whether the old "Buffering" strategy should also be removed when we switch to the new default.

I think we should keep the current 'buffering' strategy.

> The distinction between the new default and "Buffering" is quite small and, I think, necessitates renaming the current version to something like "Prevent EVs from exceeding network capacity".

I agree. I would suggest to rename it to "Only buffer EVs if network has spare capacity".

We might even keep the current behaviour as yet another strategy called: "Wait as long as possible with charging EVs". It won't solve a lot of network problems though :wink:

**Comment by antw** [comment]
I have two versions of this ready-to-go.

1. The first is as described in this issue: make default EVs "dumb", and rename the existing buffering strategy to "Only buffer EVs if network has spare capacity".

  However, I'm not a fan of this due to the radical change in EV behaviour when enabling storage...

  |                           | Default behaviour | Storage behaviour |
  |---------------------------|-------------------|-------------------|
  | Respect network capacity? | No                | Yes               |
  | Use grid?                 | Yes               | No                |
  | Discharge surplus         | No                | Yes               |

  ... not only does it enable discharging surpluses, but also constrains the EV to not break network capacity and only use PV excess. The strategy name does not make this clear to the visitor, and I don't think most would expect this to happen. The only selling point is that it closely matches the way P2P battery storage works.

2. The alternative is to make default EVs "dumb", and *replace* the two EV strategies with three others:

  * Only buffer EVs if network has spare capacity
  * Only buffer EVs with excess PV production
  * Storage in electric vehicles

  These do as you would expect, and can be enabled in any combination. A migration has been written to convert old LESes to use the new strategies.

Are there any objections to the second option? It's slightly more complex for the visitor, but I also think the choices are clearer and do exactly what they'd expect (and nothing more).

**Comment by antw** [comment]
Discussed with @ChaelKruip, and we're going to merge the second option so that it may be evaluated further. We can roll it back on beta quite easily if it isn't liked.
