### ISSUE TITLE
An existing LES should not need to re-calculate when viewed

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#508]
This is a general issue.

It takes a long time to load a LES while the calculation is already done. 

We could save the calculation to the database in order to save time. Don't quiet know what the limitations are database wise and when it comes to `$.ajax`. So I'll have to look into that first.

- [ ] Researching options for storing large amounts of data to the database
- [ ] Researching limitations of browsers

**Comment by grdw** [comment]
*If* we were to store it in the database. The thing would be, to store the 35040 points per end-point in `MEDIUMBLOB` type columns. Thing is though, if you have 200 end-points - it will still be slow.

The other options are: 

- Redis (using `ENDPOINT_KEY_NAME => [ 35040 values ]`)
- Writing to file (this seems really slow mentally but maybe in practice it's really fast)

**Comment by antw** [comment]
I put some thought into this recently, but I will start by saying these ideas are off the top of my head. I have some experience of building simple caching systems, but this task will be tricky because of the amount of data we need to store at once, and the way in which we need to access it.

### Requirements

* We need to store at least two versions of the computed network: the “blue-line” and “green-line” loads.

* The blue-line and green-line loads should be separate, since the blue-line load rarely needs to be recalculated. The green-line load, however, may be frequently recalculated as a user plays with the “technology behaviour” settings in the front-end.

* The cache should be available with a Ruby API to fetch the data. For example:

  ```ruby
  cache = NetworkCache.for(TestingGround.first, strategies)
  cache.node('HV Network’).load
  ```

  This will allow us to extend the API at a later date with the nice-to-haves.

* Ideally the API should load the minimal amount of data needed to fulfil the request. The previous example should load the “HV Network” load only. This probably means storing each node load in a separate file/cache-key/etc.

* It should be possible to disable the cache for development and testing purposes, and get a fully-recalculated network each time.

#### Nice-to-have

Not needed in the initial version, but considerations for the future:

* Store the loads of individual *technologies* to be shown in a chart.

* Store the “storage” amounts of individual technologies, so that we may visualise how much is stored in a battery or heat-tank at each moment in time.

### Cache Expiry

* Green-line loads need to be expired and recalculated when a user changes the technology behaviour settings.

* Blue- and green-line loads need to be expired when the user changes the technology mix.

* Editing a topology should expire all caches for all LES’ using that topology.

* **All** caches should be expired when performing a deploy to staging or production.

### Storage

Storing the data in MySQL is probably not the best approach. Dumping everything into a DB column will be quite limiting, and RDBMS’ were’t really designed for this use-case.

Possibilities I see are:

* Store computed networks in Memcache. Memcache settings will need to be customised to increase the available space, and special care will be needed so as not to exceed the 1MB-per-object limit (I believe it may be possible to change this?).

* Store computed networks in Redis.

* Save the loads to file(s) on disk.

My favourite of these options is the third. We would serialise each node load (which is just an array of numbers) using [MessagePack](http://msgpack.org/index.html). MessagePack was used [to perform caching of large dataset objects in ETEngine](https://github.com/quintel/etengine/blob/master/app/models/etsource/atlas_loader.rb#L25-L118), and is extremely fast (a quick test suggests we can serialise a load curve to MsgPack format and save to disk in less than 0.1 ms). The OS and file-system will cache the contents of frequently-accessed files in memory. Perhaps there is a suitable hybrid approach of serialising with MessagePack and storing in Memcache? Saving to disk is definitely easier though.

--

It would also be nice for the front-end to also have a nice API for dealing with the networks:

```javascript
network = new Network(id, strategies);

network.loadFor("HV Network")
  .success(function(loads) {
    // Goes to the server to retrieve the load, or fetches it from
    // the "network" object if it has been loaded previously.
  })
  .error(function(err) {
    // ...
  });
```

The less we have to deal with arrays and hashes and raw HTTP requests, the better.

--

I think a useful first step would be to test and benchmark the various options. How quickly can each one serialise and de-serialise a single load curve? How about 30 curves?

Then you would document your results in this issue and propose your preferred solution. I don't want to burden you with too much bureaucracy, but caching is deceptively hard, so it would be good to design and discuss a solution before getting too deep into the implementation. :laughing:

**Comment by grdw** [comment]
> I think a useful first step would be to test and benchmark the various options. How quickly can each one serialise and de-serialise a single load curve? How about 30 curves?

I'll write a tiny script that will do this. `Benchmark` is my friend.

> so it would be good to design and discuss a solution before getting too deep into the implementation. 

I agree :+1: 

> The OS and file-system will cache the contents of frequently-accessed files in memory. Perhaps there is a suitable hybrid approach of serialising with MessagePack and storing in Memcache? 

Perhaps there is. I'll look into it with the script.

**Comment by antw** [comment]
> `Benchmark` is my friend.

[evanphx/benchmark-ips](https://github.com/evanphx/benchmark-ips) is pretty sweet.

**Comment by grdw** [comment]
> evanphx/benchmark-ips is pretty sweet.

Nice! :smile:

**Comment by ChaelKruip** [comment]
> Store the loads of individual technologies to be shown in a chart.

Yes, and it would also be very nice to store loads of stakeholders at various parts in the network to be shown in a chart

> Editing a topology should expire all caches for all LES’ using that topology.

Doesn't this depend on the operation? Loads will not change if names or costs are changed for instance. Only if capacities are updated should it be necessary to re-calculate right?

**Comment by grdw** [comment]
Results of benchmarking

Contents of script

````
           big-redis      0.102  (± 0.0%) i/s -      1.000  in   9.766620s
       big-memcached      0.068  (± 0.0%) i/s -      1.000  in  14.622987s
            big-file      0.100  (± 0.0%) i/s -      1.000  in  10.028063s
        mp-big-redis      0.360  (± 0.0%) i/s -      2.000  in   5.563542s
    mp-big-memcached      0.362  (± 0.0%) i/s -      2.000  in   5.520575s
         mp-big-file      0.310  (± 0.0%) i/s -      2.000  in   6.449823s
        bp-big-redis      0.349  (± 0.0%) i/s -      2.000  in   5.731799s
    bp-big-memcached      0.352  (± 0.0%) i/s -      2.000  in   5.685069s
         bp-big-file      0.299  (± 0.0%) i/s -      2.000  in   6.699207s

Comparison:
    mp-big-memcached:        0.4 i/s
        mp-big-redis:        0.4 i/s - 1.01x slower
    bp-big-memcached:        0.4 i/s - 1.03x slower
        bp-big-redis:        0.3 i/s - 1.04x slower
         mp-big-file:        0.3 i/s - 1.17x slower
         bp-big-file:        0.3 i/s - 1.21x slower
           big-redis:        0.1 i/s - 3.54x slower
            big-file:        0.1 i/s - 3.63x slower
       big-memcached:        0.1 i/s - 5.30x slower
````

It's a bit of tie between `MessagePack`-memcache or `MessagePack`-redis.

**Comment by antw** [comment]
> Yes, and it would also be very nice to store loads of stakeholders at various parts in the network to be shown in a chart

I'm not sure if we need to *cache* that; we might be able to pull all the individual loads out of the cache, recreate the network (without having to recalculate) and compute the stakeholder loads. We should only cache 

> Doesn't this depend on the operation? Loads will not change if names or costs are changed for instance. Only if capacities are updated should it be necessary to re-calculate right?

Indeed. Changes to the capacity, layout, or component names are the only operations which would warrant a cache expiry (and the last two may be prohibited, per #511).

However, for a first version expiring on *any* topology change is okay. We can concern ourselves with the little optimisations when we have the basics nailed. :smiley:

> Results of benchmarking

Can you explain the naming conventions? I'm not sure of the difference between mp-big-memcache and bp-big-memcached, and big-memcache, ...

**Comment by grdw** [comment]
> I'm not sure of the difference between mp-big-memcache and bp-big-memcached, and big-memcache, ...

Oh yes - sorry

`big` - means 200 curves
`mp` - means `to_msgpack / MessagePack.unpack`
`bp` - means `pack("d*") / unpack("d*")`

**Comment by antw** [comment]
Could you put the script in a Gist? 2.5 seconds to store 200 curves seems a bit disappointing; still *way* better than recalculating, but I was hoping it would be faster. :disappointed:

**Comment by grdw** [comment]
Yes: https://gist.github.com/grdw/5c03be7090a9b65c5c76

**Comment by antw** [comment]
> Yes: https://gist.github.com/grdw/5c03be7090a9b65c5c76

Thanks. [I made some changes](https://gist.github.com/antw/8cc5e0ac2b8fe056116c).

* With benchmark/ips you don't need to wrap the contents of each `report` block with `n.times`. Whereas the normal benchmark library tells us “it takes *n* seconds to execute this block”, benchmark/ips reports “you can execute this block *n* times per second (reported as ‘i/s’)”.

* The raw file and Redis versions (`big-file` and `big-redis`) simply returned a string without casting the values back to `Array[Float]`. The non-MessagePack version looks very uncompetitive for our use-case after casting the values back to floats.

* When benchmarking, you want to be testing the minimal amount of code possible. The original version created a new load curve in each benchmark iteration. If creating the random curve takes much longer than storing it in a cache, the numbers end up looking similar to one another. Instead, one random curve is created before the benchmark and reused in each test.

  | Test           | Before   | After     |
  | -------------: | -------: | --------: |
  | memcached+msg  | 57.1 i/s | 308.9 i/s |
  | redis+msg:     | 56.9 i/s | 293.4 i/s |
  | file+msg:      | 54.5 i/s | 291.7 i/s |
  | redis:         | 17.0 i/s |  23.2 i/s |
  | file:          | 16.9 i/s |  22.6 i/s |
  | memcached:     | 11.9 i/s |  14.1 i/s |

* I separated the read and write benchmarks to be separate. Putting them together is fair if we expect their use to be split 50/50, but it's likely that reads will be far more frequent.

### Write Benchmarks

```
                   redis     12.473  (± 8.0%) i/s -     63.000
               memcached     21.524  (± 4.6%) i/s -    108.000
                    file     24.040  (± 4.2%) i/s -    120.000
               redis+msg    772.103  (± 4.3%) i/s -      3.900k
           memcached+msg    777.646  (± 2.8%) i/s -      3.952k
                file+msg    760.444  (±39.6%) i/s -      2.646k

    Comparison:
           memcached+msg:      777.6 i/s
               redis+msg:      772.1 i/s - 1.01x slower
                file+msg:      760.4 i/s - 1.02x slower
                    file:       24.0 i/s - 32.35x slower
               memcached:       21.5 i/s - 36.13x slower
                   redis:       12.5 i/s - 62.35x slower
```

### Read Benchmarks

```
                   redis      5.055  (± 0.0%) i/s -     26.000
               memcached     43.282  (± 4.6%) i/s -    220.000
                    file     42.003  (± 4.8%) i/s -    210.000
               redis+msg    427.486  (±18.2%) i/s -      1.978k
           memcached+msg    499.135  (± 6.2%) i/s -      2.499k
                file+msg    642.729  (± 6.1%) i/s -      3.250k

    Comparison:
                file+msg:      642.7 i/s
           memcached+msg:      499.1 i/s - 1.29x slower
               redis+msg:      427.5 i/s - 1.50x slower
               memcached:       43.3 i/s - 14.85x slower
                    file:       42.0 i/s - 15.30x slower
                   redis:        5.1 i/s - 127.14x slower
```

**Comment by grdw** [comment]
The data from the benchmarking +

> but it's likely that reads will be far more frequent.

Concludes that `file+msg` is a winner.

**Comment by ChaelKruip** [comment]
Can this be closed @grdw?

**Comment by grdw** [comment]
Yes
