### ISSUE TITLE
Default topology and market model shouldn't lead to private LESS 

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#516]
![image](https://cloud.githubusercontent.com/assets/104830/10361422/535b25c0-6da8-11e5-830e-e3590feacc9f.png)

**Comment by ChaelKruip** [comment]
I think the defaults should be public. Assigning to @grdw

**Comment by grdw** [comment]
They are both public. However because there are now more than ~60 topologies with the name `Default topology` you can't be sure that the `Default topology` is actually the `Default Topology`. The same problem exists for market models. There is an issue for this problem that's already fixed. Will deploy it after the demo.

**Comment by ChaelKruip** [comment]
>  Will deploy it after the demo.

:+1:

**Comment by grdw** [comment]
I deployed it. Also renamed the Default clone's with a query.
