### ISSUE TITLE
Importing gas technologies

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#555]
Will fill out this issue when more is clear.

**Comment by ChaelKruip** [comment]
> when more is clear.

Let me clarify: just as with PV, EV and four types of heat pumps, we need to 'import' the number of some gas-fuelled space heating and hot water technologies from the ETM into ETMoses. The following technologies are relevant:

* households_space_heater_network_gas
* households_space_heater_combined_network_gas
* households_space_heater_micro_chp_network_gas (import but don't show to user yet because this needs some extra consideration, see https://github.com/quintel/etmoses/issues/556)
* households_water_heater_network_gas
* households_water_heater_combined_network_gas
* households_water_heater_micro_chp_network_gas (import but don't show to user yet because this needs some extra consideration, see https://github.com/quintel/etmoses/issues/556)
* households_water_heater_fuel_cell_chp_network_gas (import but don't show to user yet because this needs some extra consideration, see https://github.com/quintel/etmoses/issues/556)

**Comment by grdw** [comment]
> The following technologies are relevant:

Thanks for the technologies. :smile:  I put them in a migration and they're in the database. And set visible to false for the three technologies you just specified. 

I'm guessing that this is not the only thing that needs to happen? :sweat_smile:

**Comment by ChaelKruip** [comment]
> I'm guessing that this is not the only thing that needs to happen?

They need to show up in the technology matrix as well... Later, they need to be coupled to the heat demand but that is not part of this ticket :smile:

**Comment by grdw** [comment]
> They need to show up in the technology matrix as well

That happens automatically with all the visible technologies :+1:

**Comment by ChaelKruip** [comment]
Can we close this @grdw ?

**Comment by grdw** [comment]
Yes
