### ISSUE TITLE
Do we need extra functionality to include fuel cells and micro-CHPs?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#556]
In https://github.com/quintel/etmoses/pull/518 we discuss importing of gas-consuming space heating and hot water technologies into ETMoses. Micro-CHPs and fuel cells are among those but with an extra twist: whenever they make heat, they also produce electricity.

Does this pose a problem for ETMoses? If so, we need to allocate time next year to include these technologies.

NOTE: We can look at them from two sides: 
* as heating technologies that have electricity as a by-product (which I suggest we do as I think it may simplify things)
* as **dispatchable** electricity producers with heat as a by-product

**Comment by antw** [comment]
> Does this pose a problem for ETMoses?

Maybe, yes. Since we only have the one carrier at the moment, load is always simple consumption or production without any side-effects. We also know how much production is available at the *beginning* of the calculation (we know how much a solar PV produces, or how much is stored in a battery), but this feature would require production to change mid-calculation depending on the gas-load of the cell of CHP.

I'm not 100% sure what the effect of that would be, but I'll try to include it in my planning for gas technologies.

> If so, we need to allocate time next year to include these technologies.

Are these techs wanted in Moses *now*, and if so, how do you think they should behave if we *can't* support electricity as a by-product in the short-term? Is the plan to include them only if we can implement the by-product, or would it be acceptable to only model the gas part?

**Comment by ChaelKruip** [comment]
> Are these techs wanted in Moses now

(Very) nice to have I would say but people will understand that these technologies are more complex because they produce two carriers.

> Is the plan to include them only if we can implement the by-product

I think so yes. Without the electricity production these technologies are just very inefficient heating devices...

**Comment by ChaelKruip** [comment]
Closing this for now.
