### ISSUE TITLE
The profile matrix and the buffer

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#566]
There needs to be an optional buffer per end-point which has a profile upon which you can attach certain technologies.

````
                       HP
                     /
        LV1 --- BUFFER --- GB
      /              \
HV ---                 P2H
      \
        LV2 ...
````

This also has to change in the front-end.

**Comment by ChaelKruip** [comment]
> There needs to be a global buffer

I think every household should have it's own buffers (one for space heating and one for hot water). Just as with base-load and other technologies, the buffer can have a profile and a 'units'.

**Comment by grdw** [comment]
> There needs to be a global buffer

Had to pick my words a bit better here.

**Comment by antw** [comment]
(I've started on the `Network` implementation of this already).

@ChaelKruip Does each house needs it's own *buffer* or its own *demand profile*? I had assumed that each technology has it's own buffer (as they do now) rather than feeding into a shared buffer.

**Comment by ChaelKruip** [comment]
> @ChaelKruip Does each house needs it's own buffer or its own demand profile? I had assumed that each technology has its own buffer (as they do now) rather than feeding into a shared one.

Sorry if I have been unclear about this. Each household needs it's own buffers (one for space heating and one for hot water). I think it makes sense to assign the hot water and space heating demand profiles (which we now assign to the technologies directly as 'use profiles') to the buffers instead. We than can associate the technologies (heat pumps, P2H, gas-boilers etc.) to the buffers as @grdw has drawn above.

I think some of the confusion might have arisen from the concept of a 'household' which actually has no real meaning in ETMoses. The only physical things are the end-points of the network which could represent a single house or a whole group of them. The 'thing' that comes closest to what we could call a 'household' is the base_load profile that represents the base-load of a single household. Coupling technologies to a buffer would be the first time we actually start 'associating' things in the technology matrix with each other.

Note that because hot water and space heating are such different types of demand, we have modeled the technologies separately. So, a LES with 100 houses where everyone has a heat pump, might get 200 heat pumps in ETMoses (one for hot water, one for space heating). I don't anticipate we will have technologies that will be 'coupled' to both the hot water and the space heating buffer.

**Comment by grdw** [comment]
*What I think should happen design wise*
![20151027-profile-matrix-new](https://cloud.githubusercontent.com/assets/2676542/10789829/1438bc76-7d80-11e5-88cf-26664b9bc214.png)

- The yellow columns need to be toggled on and off.

*I thought about column and end-node filters:*
![screen shot 2015-10-28 at 2 28 38 pm](https://cloud.githubusercontent.com/assets/2676542/10789869/4ce52992-7d80-11e5-832b-be4de99dfdaf.png)

- The grey part needs to be scrollable. Mainly because of the fact that the table can get quite wide through all the things somebody can change.
- The green line is where I would like to introduce the 'buffer' column. This mainly because of the 'topology' order.

````
Endpoint -> Buffer -> Technology
````

This does pop-up a few questions:

- Are there multiple types of buffers or just one buffer with multiple profiles?
- Can a single household have more than one buffer?

**Comment by antw** [comment]
> Can a single household have more than one buffer?

Yes. A household will likely have separate "buffers" for space heating and hot water. Ideally the implementation should be flexible enough to support other buffers also (not hard-coded to just those two). *(the `Network` stuff I'm working on should have no problems with multiple buffers on the same endpoint).*

In the back-end, I'm avoiding calling these *buffers*, since they're more complicated than just load-buffering. The name I'm using at the moment is `Composite`, i.e. a technology which is *composed* of one or more smaller technologies. The aim is that the same concept can handle these large cases (hot water demand supplied by several techs) and also hybrid technologies (those which are made up of separate electricity and gas components).

--

Personally, I think the table metaphor is getting to the point of being overstretched. In light of #573 – which describes the need to edit more attributes than are currently shown in the table – it might be time to explore other ideas. For example:

```
▶ Households 1
▶ Households 2
▼ Households 3

  "Basic" Technologies
  --------------------

  Tech One:
  Profile: [ Something | v ]  Capacity: [ 0.5 ]  Units: [ 3 ]   [ Advanced options... ]  [ Remove ]

  Tech Two:
  Profile: [ Something | v ]  Capacity: [ 0.2 ]  Units: [ 7 ]   [ Advanced options... ]  [ Remove ]

  [ Add new technology ]

  Hot water
  -------------

  Profile: [ Something | v ]  Buffering volume: [ 10.0 ]  Demand: [ 3454.0 ]  Units: [ 4 ]

  Hot water tech one:
  Profile: [ Something | v ]  Capacity: [ 0.2 ]  [ Advanced options... ]  [ Remove ]

  Hot water tech two:
  Profile: [ Something | v ]  Capacity: [ 0.4 ]  [ Advanced options... ]  [ Remove ]

  [ Add new technology ]
```

Clicking "advanced options" gives you all the other editable attributes:

```
  Tech One:
  Profile: [ Something | v ]  Capacity: [ 0.5 ]  Units: [ 3 ]   [ Hide advanced options... ]
  Coefficient of performance: [ 4.5 ]  Cost per unit: [ 443.2 ] etc ...
```

If it makes things easier, I'd support moving installed technologies (`technology_profile`) out of the `testing_grounds` table and making each one a separate row in a new `installed_technologies` table.

**Comment by grdw** [comment]
> Personally, I think the table metaphor is getting to the point of being overstretched.

I agree. Also like your take with the expandable boxes.

Maybe if the input/select boxes were side-by-side?

```
▶ Households 1
▶ Households 2
▼ Households 3

  "Basic" Technologies
  --------------------

  Tech One:
  Profile:     [ Something | v ]                                      [ Remove ]
  Capacity:    [ 0.5 ]  
  Units:       [ 3 ]   
  [ Advanced options... ]

  Tech Two (with advanced options open):
  Profile:           [ Something | v ]    Technical Lifetime [ 0 ]    [ Remove ]
  Capacity:          [ 0.2 ]              Technical Lifetime [ 0 ]
  Units:             [ 7 ]                Technical Lifetime [ 0 ]
  Technical Lifetime [ 0 ]                Technical Lifetime [ 0 ]  

  [ Add new technology ]

  Hot water
  -------------
  ....

```

**Comment by antw** [comment]
> Maybe if the input/select boxes were side-by-side?

:+1:

**Comment by grdw** [comment]
![screen shot 2015-10-30 at 5 23 46 pm](https://cloud.githubusercontent.com/assets/2676542/10851363/02648334-7f2b-11e5-9d1b-727317a0cb11.png)
