### ISSUE TITLE
Investment and O&M costs for components of gas-infrastructure should be researched

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#574]
At this point we will not explicitly model the gas-infrastructure (topology) as with electricity but we should still know a bit more about the cost of the gas infrastructure to be able to assess 'avoided costs' if we build an all-electric street in ETMoses. Or the cost of removal ('amoveren') of existing infrastructure if we would go to all-electric in existing streets.

I think it would be very useful to know:

*  The typical costs associated with building gas-infrastructure for a house and a street
*  The typical costs associated with removing gas-infrastructure for a house and a street
*  The typical costs associated with operating and maintaining gas-infrastructure for a house and a street

**Comment by ChaelKruip** [comment]
@JeroenvdLogt do you think you could find numbers for these topics?

**Comment by jorisberkhout** [comment]
We recently researched these parameters for a different project and found the following costs; all costs are costs per connection (i.e. house) and include a proportional part of costs of the gas infrastructure that is shared with other connections.

| Parameter | Costs |  Comment |
| :--- | :--- | :--- |
| Typical cost of construction | € 766.95 | Based on *Rekenmodel maximumprijs en aansluitbijdrage warmte (ACM, 2015)*; weighted average of the *eenmalige aansluitvergoeding* for a G6 connection |
| Typical cost of removal | € 766.95 | The majority of the cost for construction and removal of gas infrastructure are labour costs and costs of equipment; the costs of the pipelines themselves are marginal compared to these and we assumed that the costs of removal are therefore equal to the costs of construction |
| Typical O&M costs | € 62.00 / year | Based on *Rapportage winsten regionale netbeheerders elektriciteit en gas 2008-2013 (ACM, 2015)*; total annual O&M costs divided by number of connections |

Do these make sense to you, @JeroenvdLogt ?

**Comment by ChaelKruip** [comment]
@JeroenvdLogt it would be more useful if we would have some typical numbers for extreme and average situations:

* Densely populated region (city)
* Sparsely populated region (countryside)
* Something in between?

**Comment by dennisschoenmakers** [comment]
> @JeroenvdLogt it would be more useful if we would have some typical numbers for extreme and average situations:

Densely populated region (city)
Sparsely populated region (countryside)
Something in between?

I know that some models (references available on request through a private message) use the building density ('woningdichtheid') to scale 'typical' costs. We could perhaps include a 'building density' parameter in the topology?

Some numbers to give you an idea:
* Woningdichtheid Nederland gemiddeld: 224 
* Woningdichtheid Amsterdam: 2419

Sources: [Ois](http://www.ois.amsterdam.nl/media/Amsterdam%20in%20cijfers%202014/files/assets/basic-html/page443.html) en [CBS](http://www.cbs.nl/NR/rdonlyres/68092452-2D41-416C-B5D5-C77737DBDE80/0/demografischekerncijfers2014.pdf)

**Comment by JeroenvdLogt** [comment]
I discussed this point within Alliander and with Dennis on the phone. For the short period is okay to only use good guesses of cost of gasconnection and gastransport per house. 

According to the tariff experts at Alliander Regulering the connection tarriffs and transport tarrifs are a good representation of the average cost for gas infrastructure & connection. Local situtations can differ (a lot). In dicussion with Dennis we agreed to set the default cost for now on the tariffs and let the user  be free to change the number. At monday we will discuss how the gasinfrastructure can be modelled in more detail.

According to internal experts there is a great anology to electricty infrastructure. There is extra high pressure (GTS), high pressure (DSO) and low pressure (DSO). I will allready do effort to collect the required data ("boekwaardes", "material cost" "maintenance cost"). The only difference is that compression of low pressure to high pressure at (GOS: gas ontvangst station) is not incorperated in the infrastructure yet. This means that surpluses at low pressure can not be transported to other regions. Technically there are solutions for this but these cost money. 

So to conclude I will give the tarrifs in a seperate comment and will put effort in getting data about other cost parameters. Monday we can discuss this point.

**Comment by JeroenvdLogt** [comment]
Tarriffs --> average cost: to realize a new gasconnection
![aansluit tarieven gas](https://cloud.githubusercontent.com/assets/7781037/10943266/05204350-8314-11e5-855c-a943085bcf07.JPG)

https://www.liander.nl/consument/aansluitingen/tarieven/?ref=8323

**Comment by JeroenvdLogt** [comment]
Tarrifs-->average cost: to remove olde gasconnection
![tarieven verwijderen gasaansluiting](https://cloud.githubusercontent.com/assets/7781037/10943337/47064fee-8314-11e5-85c8-d1cfad8da052.JPG)

https://www.liander.nl/consument/aansluitingen/tarieven/?ref=8452

**Comment by JeroenvdLogt** [comment]
Tarrifs-->average cost: to (dis)connect to main pipe in street.
![in-uitbedrijfstelling gas](https://cloud.githubusercontent.com/assets/7781037/10943435/af0d5132-8314-11e5-948d-7bf61fef0f91.JPG)

https://www.liander.nl/sites/default/files/Tarieven_IBS_en_UBS_gas_2015.pdf

**Comment by JeroenvdLogt** [comment]
Tarriffs --> average daily and monthly cost to enable gastransport (systemcost or also called cost for infrastructure)

"Periodieke tarieven
De totale periodieke netwerkkosten noemen we ook wel het capaciteitstarief. Dit is de som van

De afzonderlijke periodieke tarieven voor de aansluiting.
- Het transport van de energie.
- De meetdiensten per aansluiting.
- De leverancier brengt dit tarief als één bedrag in rekening. 
De hoogte van de capaciteitstarieven zijn weergegeven in onderstaande tabel. "

![image](https://cloud.githubusercontent.com/assets/7781037/10943579/3e5bbacc-8315-11e5-85c4-2e4d741e99a5.png)

https://www.liander.nl/consument/aansluitingen/tarieven/?ref=8470

**Comment by JeroenvdLogt** [comment]
Is this usefull information for now @ChaelKruip?

**Comment by ChaelKruip** [comment]
> Is this usefull information for now @ChaelKruip?

Yes. Thanks a lot!

One other point that came up in recent discussion with John Kerkhoven is the cost of 'reviving' old infrastructure using a coating or by fitting a new hose inside the existing pipes. Do you have any ideas on what costs are relevant for such operations?

**Comment by JeroenvdLogt** [comment]
I found this text in the (kwaliteits- en capaciteitsdocument) from Enexis for now. I wel continue further research. 

https://www.enexis.nl/Documents/kwaliteit-en-capaciteit/enexis-kwaliteit-en-capaciteit-gas-2014-2023-deel-a.pdf

"Op het gebied van innovatie werkt Enexis momenteel aan de volgende onderwerpen in de gasvoorziening:
 Doorontwikkelen en onderzoeken van sleufloze renovatie voor gasleidingen. Door het toepassen
van deze technieken kan met hetzelfde personeel sneller gasleidingen worden vervangen terwijl het
minder overlast voor omwonenden veroorzaakt. Pipebursten is reeds geimplementeerd en wordt verder geoptimaliseerd in samenwerking met de aannemers. Ook Cured-In-Place-Pipe Relining (beter bekend als kousmethode) zal worden geimplementeerd. Daarnaast worden nieuwe technieken nauw gevolgd. Pipebursting
 Bij het vervangen van gashoofdleidingen worden de aansluitleidingen van de oude op de nieuwe hoofdleiding overgezet. Er worden proefprojecten uitgevoerd met een nieuwe werkmethode waar het niet langer nodig is de gasdoorvoer te onderbreken. Hiermee kan zowel een productiviteitsverbetering en stijging van de klanttevredenheid behaald worden.
 Renoveren van stijgleidingen met een kousmethode. In plaats van het vervangen van stijgleidingen wordt onderzocht of deze gerenoveerd kunnen worden door het plaatsen van een kous aan de binnenkant. In proefprojecten zal onderzocht worden of het behalve kostenefficient is, maar ook productiviteitsverbetering opleverd."

**Comment by JeroenvdLogt** [comment]
http://www.trenchless-pipelining.com/

"TRENCHLESS PIPE LINING COMPANY STOPS BACKUPS & LEAKS PERMANENTLY COSTING 60% LESS THAN EXCAVATION!

From outside your property we open the pipe, clean out the rust, scale and roots, and then install a new “pipe liner” or sleeve which has been saturated with a special self-hardening epoxy resin. The liner contains a balloon which is inflated for 3 hours while the resin becomes rock-hard. Then the balloon is removed and a video inspection is performed to ensure correct installation. The pipe is put back into use within 1 day.

Benefits Of Trenchless Pipe Lining (a.k.a. Cured In Place Pipe, CIPP)
No Excavation Required 
– no permitting and no inspections required Less expensive – pipe relining costs about 70% less than excavation Save Your Floor Tile/Marble/Wood – it’s usually impossible to find matching floor surfaces that were installed decades ago. Clean, No sewer bacteria in your home – since the drain is not being cut into pieces inside your residence, there is no need to sanitize the property afterwards Stay in your residence 
– pipe relining is done from outside, so you can stay in your residence 
Speed 
– pipe lining takes 1 day, not 3 weeks as for pipe replacement by excavation Environmentally friendly – pipe replacement by excavation means tons of waste concrete and pipe have to be disposed of in landfills

How Much Does Trenchless Pipe Lining Cost?
For residential purposes, from $150-$200 per linear foot of lining. It varies by pipe diameter, installation complexity, and customer attitude. For Commercial purposes, $175-$225 per linear foot. Commercial installation would be high-rise buildings, factories, shopping malls etc. These installations are more complex since pipe downtime, even for just 4 hours, usually has an enormous impact on tenants and can cause much economic impact for any loss of use of pipe. Note also, every trenchless pipe lining company will have a minimum charge in order to mobilize their expensive equipment and trained crew.

How Strong Is The Pipe Lining?
The pipe liner is a fabric tube made of polyester which is then “wet out” with a 2-part epoxy resin which is mixed together in a certain proportion. In about 30 minutes resin heats up by itself to 180 degrees Fahrenheit due to an exothermic chemical reaction and becomes rock hard.

The resulting new inner pipe liner is so strong that it is a stand-alone pipe, not needing the old exterior pipe for structural integrity. The liner is designed to go under load bearing footers, roads, driveways etc.

SEWER PROBLEMS? TRENCHLESS SEWER RELINING MAY BE THE ANSWER
Trenchless sewer pipe relining or pipe lining saves homeowners money when compared to traditional sewer line replacement methods where the entire pipe is dug up and landscaping and concrete or asphalt has to be replaced.  Trenchless technology makes it possible to replace the old sewer pipe with a brand new one without digging it up.

How Does Trechless Sewer Pipe Lining Work?
The process for completing pipe relining requires highly advanced equipment.  First a hydro-jetting machine is used to completely remove and types of blockages including tree roots.  This is a very sophisticated process because we are removing accumulations from a fragile pipe with damaging the pipe even more. That is why it is so important to use an experienced trenchless sewer pipe lining expert like us.

CIPP Trenchless Sewer Replacement
Once the inside surface of the old sewer pipe is completely clean an epoxy liner is pulled into the pipe.  A internal bladder is then inflated inside the liner to provide a shape for the epoxy to cure around.  That is why trenchless relining or pipe lining is called Cured In Place Pipe.  The epoxy hardens and a brand new sewer pipe is formed.  The lining material is a polyester felt tube and the resin is made up of odorless epoxy which is approved by the FDA, EPA, NSF, IAPMO and a slew of other regulatory entities.

Getting an Estimate for Trenchless Sewer Pipe Replacement
We are currently offering a no cost estimate for people who are considering trenchless relining.  If you have a written estimate from another contractor we would be happy to analyze it with you and see if we can do something better for you.  As a premier provider of trenchless sewer replacement we will do whatever we can to earn your business.

We also have a service available where we can provide you with a video camera inspection of your sewer line.  The video camera inspection is the best way for a homeowner to actually see inside the sewer line.  It is easiest to understand why the sewer line needs to be replaced if you can see the broken pipe for yourself.  This type of inspection also eliminates the possibility of an unscrupulous contractor trying to sell you something you don’t need.  Call us today to arrange an inspection or to get an estimate for trenchless sewer replacement using pipe lining."

**Comment by ChaelKruip** [comment]
@JeroenvdLogt can you add all relevant information in this ticket to the [documentation](https://github.com/quintel/documentation/blob/master/etmoses/average_cost_of_gas_infrastructure.md)? Than we can close this issue.

**Comment by jorisberkhout** [comment]
The documentation on the gas infrastructure has been moved to https://github.com/quintel/etmoses/wiki/gas-infrastructure.

Linking to https://github.com/quintel/etmoses/issues/893.

**Comment by ChaelKruip** [comment]
@jorisberkhout  can you give this a push in the right direction?

**Comment by jorisberkhout** [comment]
I believe this issue has been superseded by https://github.com/quintel/etmoses/issues/1112 and https://github.com/quintel/etmoses/issues/1191. Also the gas network documentation was given a push in the right direction by @ChaelKruip and me.

Closing this issue.
