### ISSUE TITLE
Download of available electric storage volume in P2P and EV

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#664]
This is a request from Ecofys. The idea is that they would like to know how much (potential) flexibility remains in the LES as a whole after all strategies have been used.

I think that this should not be very complex:

* Add up the used volume of all EV batteries and P2P units for the current time-step
* Add up the un-used volume of all EV batteries and P2P units for the current time-step
* write them to CSV file

So, the user would be able to download a CSV file with 35040 rows and two columns:

|Used volume (kWh)|Free volume (kWh)|
|---|---|
|value_1|value_2|
|...|...|

Ecofys would like to have this feature before the start of the next year... 

@antw what is your estimate for time needed?

**Comment by antw** [comment]
> @antw what is your estimate for time needed?

A couple of hours, I think.

**Comment by antw** [comment]
FYI @jorisberkhout This is done.

One small caveat is that the "Storage in batteries" strategy needs to be turned on (of course) in order to get useful values in the CSV. If it's turned off, then the CSV will just contain zeroes since nothing is – or can be – stored in the batteries.

![screen-shot-2016-01-12-at-13 31 48](https://cloud.githubusercontent.com/assets/4383/12264830/461b726e-b931-11e5-84df-cfeb05556392.png)

**Comment by jorisberkhout** [comment]
Thanks, @antw !
