### ISSUE TITLE
Improvement: move 'add' button to the end-point area

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#683]
![etmoses](https://cloud.githubusercontent.com/assets/1303760/11748688/bbed18c4-a029-11e5-9be5-adf638bd6d52.png)

* This would make it clear to which end-point something is added
* It would help the user to find the button in the first place

**Comment by grdw** [comment]
A question. When you hit the add button, in your situation, will the newly created technology append to the bottom or the top of the list? It sounds really counter-intuitive to add it to the top of the list. Than again adding it to the bottom would be stupid when you have a really large list of technologies (because than you can't see what you added).

I don't know yet about this one. I get the point, but it has some other 'downsides'.

**Comment by grdw** [comment]
![screen shot 2015-12-11 at 5 18 08 pm](https://cloud.githubusercontent.com/assets/2676542/11748953/2d2c5940-a02b-11e5-87d2-b47342c23bdf.png)

Maybe some more margin makes it easier for the eye?

**Comment by ChaelKruip** [comment]
> It sounds really counter-intuitive to add it to the top of the list.

I kindly disagree. I think it makes sense to keep the stuff you are adding and editing on the screen. It would feel like 'pushing new technologies on a stack' which for me is not counter-intuitive... 

What do you think @antw @dennisschoenmakers?

**Comment by grdw** [comment]
Completly setting the technology select box to the right:
![screen shot 2015-12-14 at 3 00 37 pm](https://cloud.githubusercontent.com/assets/2676542/11782776/79c9426e-a273-11e5-967b-c3a9ef60f0cc.png)

OR

Setting it a little to the right relative to the header (which causes some irregularities in line)
![screen shot 2015-12-14 at 3 00 42 pm](https://cloud.githubusercontent.com/assets/2676542/11782777/79eb703c-a273-11e5-83eb-6a9b9d944f1e.png)
