### ISSUE TITLE
Migrate technologies table to individual .ad/.yml files

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#700]
I don't have a clear view of how we are to implement this, but it sounds that at a certain point in time there will be too many columns in the technologies database making it a rather unpleasant overview. Also having to constantly update the database manually by hand is not really want I want to see people doing.

**Comment by ChaelKruip** [comment]
I think this is an excellent idea! It will also allow us to take the data-research workflow to the next level and will improve transparency considerably.

**Comment by antw** [comment]
Funnily enough (or not-so-funny depending on your perspective), this is exactly what early versions of Moses did. We changed it so that technologies are defined in the database. :disappointed: 

I approve of moving back to a file-based approach. The `technologies` table is getting a bit messy, and while we could clean that up by splitting it into a couple of separate tables, I think YAML or `.ad` is a better solution.

`.ad` would be nice, but we'd have to budget some time to extract the `ActiveDocument` code from Atlas into a separate Gem first. If we don't have time for that, YAML is fine also.

**Comment by grdw** [comment]
> what early versions of Moses did

Oeps... 

> If we don't have time for that, YAML is fine also.

I think YAML is fine. But I think we're not the users that will change the `technologies` all that much. I think @ChaelKruip might have a stronger opinion about this.
