### ISSUE TITLE
When saving 'as', the name should not be the same as the current LES

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#707]
Now it is possible to 'save as' with the same name which will lead to confusion.

**Comment by grdw** [comment]
What would be prefered? The same as the topologies: (calling it `<name> - Clone #<x>`)?

**Comment by ChaelKruip** [comment]
@JeroenvdLogt can you explain what you find confusing about the current situation?

![etmoses](https://cloud.githubusercontent.com/assets/1303760/11952020/bc31408e-a895-11e5-9483-b6584daeb57c.png)

**Comment by ChaelKruip** [comment]
> What would be prefered?

I think it would be better to warn the user with a pop-up saying "Please choose a new name for your LES"

**Comment by grdw** [comment]
That's also possible. We could also choose for something a little more subtle. We could track on a LES which LES is the original source. That way we can sort of say in a tiny sub-header "This LES is copied from <original LES name>"

**Comment by JeroenvdLogt** [comment]
What is most important in opinion is that the user can keep track of the versions. My problem was (few weeks or more ago) that after changes in the LES the LES was saved as clone instead of under the same name. I cannot remember if this was my own fault or a temperory  bug in ET-Moses. 

To conclude, I think the most convenient solution woudl be:
Save the LES under the same name unless the user choose to save as. During save as user should be obliged by ET-Moses to choose another name (no cloning in the background without notice of the user).

I hope this will help. Otherwise you can call me.

**Comment by ChaelKruip** [comment]
> I hope this will help. 

Very clear! Thanks!

**Comment by grdw** [comment]
The easiest way to achieve is this is with a simple prompt pop-up that asks for a new name. 

![screen shot 2016-01-14 at 12 02 47 pm](https://cloud.githubusercontent.com/assets/2676542/12322802/be8176c8-bab6-11e5-8d5a-8201ebe59372.png)

'Annuleren'  and blanking the title will discontinue the saving process.

**Comment by grdw** [comment]
![screen shot 2016-01-14 at 1 32 30 pm](https://cloud.githubusercontent.com/assets/2676542/12324505/49887cb0-bac3-11e5-8fbd-01deec558784.png)

Turned in it to someting a little more stylish.

**Comment by JeroenvdLogt** [comment]
Great! I will test it..
