### ISSUE TITLE
Is there something like a Gas Merit-Order?

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#714]
I am making a new marketmodel and was wandering. What if I choose to make a transaction for kWh gas consumption based on merit-order price. Is this the merit-order of electricity or of gas?

**Comment by JeroenvdLogt** [comment]
BTW I like the fact that transactions for gas are based on kWh. It made me realize again the relative low prices for gas compared to electricity.

**Comment by ChaelKruip** [comment]
>  Is this the merit-order of electricity or of gas?

Electricity. Perhaps it is weird to base a gas transaction on the electricity price but I can imagine that there actually can be scenario's where there is a strong correlation between gas price and electricity price because the gas plants are price-setting.

Contrary to the electricity price, the price of gas is determined more by international influences. It is next to impossible to model this within the scope of ETMoses.
