### ISSUE TITLE
neighborhood battery

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#732]
When making a LES I can choose a neighborhood battery. Can I also choose a neigborhood battery flex strategy. Or is the effect of the neighborhood allready incorperated in the null scenario without flex?

**Comment by antw** [comment]
The neighbourhood battery is turned on by enabling the "Storage in batteries prioritising local PV production" strategy.

**Comment by JeroenvdLogt** [comment]
As far as I am aware neighorhood battery consist of a battery with adjustable percentage available for congestion. But congestion is not only caused by solar PV, not every surplus of PV energy leads to congestion and saving surplus of PV energy in the morning can result in a full battery at peak times in the afternoon (which will result in congestion). 

I thought that it would be possible to choose a strategy congestion managment (loading if no congestion exist and unloading if there is congetion -- like buffering in EV but then with possibility to unload).

**Comment by antw** [comment]
The neighbourhood battery will react to *any* congestion, not just that caused by solar PV; I believe that "prioritising solar PV" simply means that batteries will try to store excess production from solar PV technologies. For the neighbourhood battery, the strategy simply acts as an on/off switch. I suppose we could separate strategy for enabling the neighbourhood battery to distinguish it from other P2P batteries?

> I thought that it would be possible to choose a strategy congestion managment (loading if no congestion exist and unloading if there is congetion -- like buffering in EV but then with possibility to unload).

We have [some documentation here](https://github.com/quintel/documentation/blob/master/etmoses/buurtbatterij.md) which describes how it works, along with a couple of examples.

**Comment by JeroenvdLogt** [comment]
Thank you for your reaction. Now I understand how the neighborhood battery works. This is indeed what we need for calculations. It's a quite sophisticated piece of modelling, compliments for that!

**Comment by ChaelKruip** [comment]
:+1:
