### ISSUE TITLE
Load chart should show components of load 

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#74]
Currently the load chart only shows the total load on a network component. It would be very informative to be able to see how this load is composed by technology:
![20141209_topology_interface_v1_key](https://cloud.githubusercontent.com/assets/1303760/7255009/d2c7f41a-e846-11e4-89ee-6a36f6cc38a6.png)

To be able to do this, the end-points (and the load calculation) of the network need to be able to deal with loads per technology. So, it will no longer suffice to initialise the end-points with just a single load value. In stead, an array of loads (and their respective technologies) needs to be communicated.

@grdw can you explore the feasibility of this?

**Comment by grdw** [comment]
This is a possibility: http://bl.ocks.org/mbostock/3885211

**Comment by ChaelKruip** [comment]
> This is a possibility: http://bl.ocks.org/mbostock/3885211

I like that it gives a cleaner (no overlapping curves) subdivision of the load. I don't think it is perfect though because it does not show the **shapes** of the different contributions (except the bottom one). This could make it difficult to see which of the various technologies is actually peaking at a given point.

**Comment by antw** [comment]
The library we're using for the current chart, NVD3, [supports a chart like that](http://nvd3.org/examples/stackedArea.html). I don't think it can be used with the "view finder" (the smaller chart which allows you to zoom in), but that may not be a big deal since higher-resolution charts are currently supported only by using the `<select>` to choose a week.

--

My feeling is that this issue should probably go on-hold for now; there are two problems which will make it difficult:

1. Large testing grounds already involve transferring a *lot* of data from the Rails app to the user's browser. The Lochem scenario, which has 200+ network connections, and 35,040 loads for each connection (one for every 15 minutes in the year), already takes several seconds just to convert the data to JSON for transmission to the browser. This is not surprising since we have to send the network structure and 7 million loads. The JSON response for the Lochem scenario is 95MB (26MB compressed)! Sending technology loads might increase this by an order of magnitude. :scream: 

  It would be better to wait until we are caching the results of the calculation, that way we can send the technologies loads only when the user really needs them.

2. While the loads for "simple" technologies are easy to determine without calculating the entire network – most are a function of their capacity and their load curve – some, such as storage, are more complicated. These are only known after the network has been calculated. The way you access this data is subject to change while I work on the new flow calculator.

--

I think this should wait at least until the new network calculation is ready to avoid waisting effort on something which is likely to change. *Ideally*, we'd schedule a "caching" task for the next sprint, and revisit then...

**Comment by ChaelKruip** [comment]
Thanks for your comments @antw. Putting this issue on-hold for now.

**Comment by grdw** [comment]
Can this be closed?
