### ISSUE TITLE
Importing 'set' attributes that are statically defined in ETmoses from ETengine

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#740]
*In order for this to become something 'physically correct' and 'code wise correct' I'd suggest to look at this per attribute per technology (in order for me to not completely lose it).*

# General

#### THE GOAL!!!!
The main thing we are trying to solve is that there are numbers defined in ETMoses (mainly in the technologies table) which we want to fetch from ETEngine (in a heavenly utopia world). However because of certain interpretations of labels for certain numbers in ETMoses - which differ from ETEngine - there's now a great deal of confusion.

There's great confusion about the use of the word `capacity` in ETMoses. This in combination with `coefficient_of_performance` and `carrier_capacity`. In the current setup I understand that those terms are being used, since we only use the `carrier_capacity` for the calculation of the [load](https://github.com/quintel/etmoses/blob/master/app/models/calculation/technology_load.rb#L105).

However in order to not cause any confusion and to fetch the actual numbers from et-engine, I'd suggest to rename `carrier_capacity` to `input_capacity` and to rename `capacity` to `output_capacity`. However some of them must be editable for some technologies. And others are not supposed to be editable because it wouldn't make any sense.

The thing is where I would stir towards, is a more dynamic layout (a layout per technology) and to do this hand-in-hand with the "YAML-migration" of technologies (the technologies that are defined in the database not the technologies that are defined in `app/models/network/technologies` - may I also suggest to rename that folder to `behaviors` - because that makes much more sense in relation to the column where those files are based on). The thing the YAML-export might allow us to, is to give other people the power of controlling the actual technology and not to write a database migration everytime something changes. 

#### Technologies YAML

How would this look like?

For instance the content of a `households_solar_pv_solar_radiation.yml` might look like this:

````yaml
key: households_solar_pv_solar_radiation
name: "Residential PV panel"
export_to: households_solar_pv_solar_radiation_market_penetration
carrier: electricity
behavior: conserving
visible: true
composite: false
expandable: true
technology_specific_attributes:
- profile
- demand
- output_capacity
- volume
-
````

The `technology_specific_attributes` would contain all attributes which are outside of the defaults (where the defaults are `units`, `technical_lifetime`, `o_and_m_*`). The only thing that the adding or removing of the attribute in `technology_specific_attributes` would imply is wether or not the attribute is visible in the front-end (nothing more nothing less). 

But I think we can do more interesting things with let's say `hybrid_heat_pumps` (`households_space_heater_hybrid_heatpump_air_water_electricity.yml`):

````yaml
key: households_space_heater_hybrid_heatpump_air_water_electricity
name: "Hybrid heat pump space heating"
carriers:
- carrier: electricity
  behavior: hhp_electricity
  ....
- carrier: gas
  behavior: hhp_gas
  ....
....
````

Also `buffers` will be much more flexible and there will be no need for the `composites` table because it would be solved by a somewhat similar structure as the hybrid heat pump (but with `composites` as key not `carriers`). 

#### The numbers in relation to the yaml migration

In order for this not to become completely chaotic and to solve one of the major struggling points `input_capacity` and `output_capacity`, there has to be a clear definition of what those two things mean for each technology and how that relates to ETEngine. Ofcourse here's where you ought to just add them to the yml file in question, but that's not all that there's to it (as told by @ChaelKruip). For some cases the `output_capacity` or `input_capacity` is directly taken from ETEngine and nothing more has to be done. In other cases these numbers have to be calculated from numbers taken from ETEngine.

I'm still wondering how the calculation of elements would become a nice solution. My first thought might be an `eval` type construction where the person in question adds the following to the yml file:

````yaml
technology_specific_attributes:
- output_capacity
- coefficient_of_performance

calculated_attributes:
  input_capacity: "output_capacity / coefficient_of_performance"
````
Also we could specify it manually in the `app/models/installed_technology.rb`. 

Overview table of the origin of capacities:

| Technology | Input capacity | Output capacity |
| --------------- | ------------------- | --------------------- |
| base_load | N/A | N/A  }
| base_load_buildings | N/A | N/A |
| base_load_edsn | N/A | N/A |
| buffer_space_heating | ? | ? |
| buffer_water_heating | ? | ? |
| congestion_battery | ? | ? |
| energy_flexibility_p2g_electricity |
| generic | N/A | N/A |
| households_flexibility_p2h_electricity | FROM ET-ENGINE (NEEDS TO BE CALCULATED ETMOSES) | N/A |
| households_flexibility_p2p_electricity | FROM ET-ENGINE (NEEDS TO BE CALCULATED ETMOSES) | N/A |
| households_solar_pv_solar_radiation | N/A | DIRECTLY FROM ET-ENGINE |
| households_space_heater_combined_network_gas | N/A | N/A |
| households_space_heater_heatpump_air_water_electricity | FROM ET-ENGINE (NEEDS TO BE CALCULATED ETMOSES) ('input_capacity' / 'cop') | N/A |
| households_space_heater_heatpump_ground_water_electricity | FROM ET-ENGINE (NEEDS TO BE CALCULATED ETMOSES) ('input_capacity' / 'cop') | N/A | 
| households_space_heater_hybrid_heatpump_air_water_electricity | N/A | N/A |
| households_space_heater_hybrid_heatpump_air_water_electricity_electricity | N/A | N/A |
| households_space_heater_hybrid_heatpump_air_water_electricity_gas | N/A | N/A |
| households_space_heater_micro_chp_network_gas | N/A | N/A |
| households_space_heater_network_gas | N/A | N/A |
| households_water_heater_combined_network_gas | N/A | N/A |
| households_water_heater_fuel_cell_chp_network_gas | N/A | N/A |
| households_water_heater_heatpump_air_water_electricity | FROM ET-ENGINE (NEEDS TO BE CALCULATED ETMOSES) ('input_capacity' / 'cop') | N/A
| households_water_heater_heatpump_ground_water_electricity | FROM ET-ENGINE (NEEDS TO BE CALCULATED ETMOSES) ('input_capacity' / 'cop') | N/A
| households_water_heater_hybrid_heatpump_air_water_electricity | N/A | N/A |
| households_water_heater_hybrid_heatpump_air_water_electricity_electricity | N/A | N/A |
| households_water_heater_hybrid_heatpump_air_water_electricity_gas | N/A | N/A |
| households_water_heater_micro_chp_network_gas | N/A | N/A |
| households_water_heater_network_gas | N/A | N/A |
| transport_car_using_electricity | DIRECTLY FROM ET-ENGINE | N/A |

* Table is still under construction

--

After this there will be almost no static numbers left in ETMoses except for the `buffers` and the `congestion_battery`. In the ideal circumstances we want *all* numbers to be derrived from ETEngine but since there are technologies specified in ETMoses which are not going to be used in ETModel (and since we "can't" make that happen) we have to keep them in ETMoses. 

To be continued ....

**Comment by grdw** [comment]
@ChaelKruip and @antw could you maybe have a readthrough of some of this and say whatever comes to mind. :+1:  thanks.

**Comment by ChaelKruip** [comment]
> since we only use the carrier_capacity for the calculation of the load.

I don't think this is true for solar PV and P2P or other technologies that *output* electricity on the grid (which is negative load).

> Table is still under construction

I think there is much more information available/known than currently in the table. @grdw talk to me how you want to validate your data. Shall I show you how to get the correct numbers from the ETM-backend? Or would you rather have me fill in the above table?

**Comment by grdw** [comment]
I see that there's a question for an estimate on all the relevant tagged issues which have to do with 'wrong' numbers. Before I can start with this issue I would like some simple feedback from someone technical - preferably @antw - before starting with a more 'solid' fix. Patching all the existing one's is simply not going to do it. It could be possible but it's not really maintainable for the future.

**Comment by antw** [comment]
I like a lot of the ideas here and definitely thing we should move technologies back to YAML.

#### Carriers, etc.

I especially like the approach suggested for `hybrid_heat_pumps`, with a `carriers` array. Maybe this might be renamed `components` (other suggestions welcome) in case we one day we need to model a technology using *two* electrical components, or two gas components, etc. We kind of do this already with base loads, which have separate flexible and inflexible parts using the same carrier.

I think this should applied to *all* technologies, even those that only have one carrier. It's a bit more verbose, but I think it's worth being consistent. For example:

```yaml
key: households_solar_pv_solar_radiation
name: "Residential PV panel"
export_to: households_solar_pv_solar_radiation_market_penetration
visible: true
composite: false
expandable: true
components:
- carrier: electricity
  behavior: conserving
technology_specific_attributes:
- profile
- demand
- output_capacity
- volume
```

#### YAML and Ruby classes

> * Moving all existing technologies (and the existing attribute only) to yaml files - 30 minutes
> * Replacing the technologies in the code (integration) - 180 minutes (hopefully less)

What might this look like in Ruby? I think I would like to see a proper Technology class (with [Virtus](https://github.com/solnic/virtus)?) which reads these YAML files and provides a nice API, rather than it being an array of hashes (one per technology). If we had a proper class and tests, I think 1-2 days is the bare minimum I'd expect this to take. I think as much as a week – to *really* get this right – would not be unreasonable.

Atlas' [ActiveDocument](https://github.com/quintel/atlas/blob/2dd7c1b743c88e4bd786e71e22c7a5d42608e7ee/lib/atlas/active_document.rb) is overkill (and doesn't read YAML), but that's the *sort* of thing I think we should aim for. [Atlas::Edge](https://github.com/quintel/atlas/blob/2dd7c1b743c88e4bd786e71e22c7a5d42608e7ee/lib/atlas/edge.rb) is probably a good example.

```ruby
tech = Technology.find(:households_space_heater_hybrid_heatpump)

tech.key                   # => :households_space_heater_hybrid_heatpump
tech.visible?              # => true
tech.components            # => [Technology::Component, Technology::Component, ...]
tech.importable_attributes # => [Import::Attribute, Import::Attribute, ...]
```

#### Dynamic attributes

> I'm still wondering how the calculation of elements would become a nice solution. My first thought might be an eval type construction where the person in question adds the following to the yml file:
>
> ```yaml
> technology_specific_attributes:
> - output_capacity
> - coefficient_of_performance
> 
> calculated_attributes:
>   input_capacity: "output_capacity / coefficient_of_performance"
> ```

I think this is the only thing I disagree with. We already have the `Import::*Attribute` classes which know how to import and calculate attributes (e.g. [DemandAttribute](https://github.com/quintel/etmoses/blob/0867f9b885430b35233969d1cebcf569ce128437/app/models/import/demand_attribute.rb)). I would prefer that the technology specific attributes simply name which "things" we want imported, and map those names to an appropriate Attribute class to do the job.

If we had a `DefaultAttribute` class which takes a value from ETEngine, and imports it without any changes, the map might look a bit like this:

```
output_capacity            -> DefaultAttribute
coefficient_of_performance -> DefaultAttribute
input_capacity             -> InputCapacityAttribute
demand                     -> DemandAttribute
# etc
```

This has the advantage of reusing existing code, being easier to test, and reduces the chances of bugs being introduced through calculations in the YAML.

Import::Attribute would need some work, but something like this?

```ruby
InputCapacityAttribute =
  Attribute.new('input_capacity') do |value, data, attribute|
    attribute.future(data, 'output_capacity') /
    attribute.future(data, 'coefficient_of_performance')
  end
```

```yaml
# ...
composite: false
expandable: true
technology_specific_attributes:
- demand
- input_capacity
- output_capacity
```

#### Nitpicks

* Instead of `technology_specific_attributes` maybe consider `importable_attributes`? "technology specific" is a bit redundant, and doesn't explain *what* the attributes are.

* > may I also suggest to rename that folder to behaviors

  In time, yes I agree with this.

* >  I'd suggest to rename carrier_capacity to input_capacity and to rename capacity to output_capacity.

  One "gotcha" is that technologies in the network calculation do not currently support separate input and output capacities, so these names would be misleading. To be honest, I'm not really sure what to do about the capacity attributes. For example, heating technologies do have an electricity input capacity, but they don't have an electricity *output* capacity. They do, however, have a *heat* output capacity.

  There also exist real-world technologies which have different capacities on each component. For example, the hybrid heat-pump has an input capacity of 4.9kW on the electric component, and 15kW on the gas component. The current solution to this was to represent each component as a separate technology. It would be nice not to have to resort to this in the YAML.

**Comment by grdw** [comment]
@antw thanks for reading through. Some comments on comments:

> I especially like the approach suggested for hybrid_heat_pumps, with a carriers array. Maybe this might be renamed components 

Yes :+1: sounds good to me. Maybe @ChaelKruip has a better word?

> Import::Attribute would need some work, but something like this?

That's way better than an ev(~~i~~)al solution! 

I agree with the nitpicks.

**Comment by ChaelKruip** [comment]
> Maybe @ChaelKruip has a better word?

I like components!

Thanks @grdw @antw for your nice ideas!

**Comment by grdw** [comment]
The previous previous friday I looked into [active_hash](https://github.com/zilkey/active_hash) and found it to be quiet useful for what we are trying to achieve here.

**Comment by grdw** [comment]
I just found out that there's still a stale branch on my local machine with a WIP for this issue. It's not really finished though but it's well under way. What should I do with this: https://github.com/quintel/etmoses/tree/issues/%23740-export-technologies-to-yaml-files ?

**Comment by grdw** [comment]
Prep. for this issue: https://github.com/quintel/etmoses/pull/942. Nothing to harmful.

**Comment by ChaelKruip** [comment]
Can we close this @grdw?

**Comment by grdw** [comment]
![Yes we can](http://blend-allaboutwine.com/wp-content/uploads/2014/12/Blend_All_About_Wine_Madeira_Vintners_Yes_We_Can.jpg)
