### ISSUE TITLE
Business case appears BEFORE load has finished

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#751]
I find this suspicious at the least...

**Comment by grdw** [comment]
> I find this suspicious at the least...

I'll take some time to research this but somehow I have no hard time believing that the business case finishes first. Are the numbers correct or is that also wrong? Maybe we can validate that together because I still don't have a clue what sums up to what - in relation with the load calculation - and how that sums up in total with the investment costs.

**Comment by grdw** [comment]
Allright quick peak tells me that the business case is always done before the LES is done. On production / staging / local. I'll try to see if that's what needs to be expected or if that's not correct. 

We validated a simple EV profile and it turns out that the number is correct. It does spawn some other issues - like what to show first and what to show next and in what order.

**Comment by ChaelKruip** [comment]
> Allright quick peak tells me that the business case is always done before the LES is done.

Do you mean that the application *shows* the business case before the load? Or do you mean that the calculation of the business case finishes before the load has been calculation? That would point to a serious bug because the business case depends on the load in a causal way.

If this is only a visualisation issue it is not urgent.

**Comment by grdw** [comment]
> Do you mean that the application shows the business case before the load?

yes.
