### ISSUE TITLE
Default load (no strategies) should not include effects of HHPs

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#753]
Right now you cannot see what would happen to the load IF strategy "switch to gas if congested" would be absent:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/12973836/d21845ae-d0af-11e5-84d7-04530add70dc.png)

**Comment by antw** [comment]
If "switch to gas" is not chosen, what is the preferred behaviour?

1. Use the electricity component, but still *do not exceed* network capacity, and disable the gas part.
2. Use the electricity component, *exceeding* network capacity if necessary, and disable the gas part.
3. Turn off both components and use other technologies to fulfil demand.

**Comment by ChaelKruip** [comment]
> If "switch to gas" is not chosen, what is the preferred behaviour?

None of the above :laughing: 

4. Use the electricity component *as much a possible* even if it exceeds the network capacity. Now for the exceptions. Do **not** use the electricity if:
  * Capacity of the buffer is insufficient to fulfil demand
  * The energy stored in the buffer (kWh) plus what the electrcity-part can do is insufficient to fulfil demand
  * The 'binary' profile dictates that the electricity part should be shut off

**Comment by antw** [comment]
> Do not use the electricity if:
>
> 1. Capacity of the buffer is insufficient to fulfil demand
> 2. The energy stored in the buffer (kWh) plus what the electrcity-part can do is insufficient to fulfil demand
> 3. The 'binary' profile dictates that the electricity part should be shut off

(2) and (3) turn out to be very simple, but I don't think I'll be able to satisfy (1). The capacity of a buffer dictates the amount of energy which can be taken from the storage (tank?) to satisfy demand. For example:

* We have a full buffer with a capacity of 10kW,
* An attached technology whose capacity is 15kW
* And demand of 20kW

... the buffer "produces" 10kW from storage, and the technology runs at 10kW, satisfying demand.

* We have an *empty* buffer with a capacity of 10kW
* An attached technology whose capacity is 15kW
* And demand of 20kW

The technology will run at 15kW in order to satisfy as much demand as possible. As I understand it, you propose to disable the tech completely because buffer capacity (10kW) is less than demand (20kW)?

**Comment by antw** [comment]
> Do not use the electricity if:
>
> 1. Capacity of the buffer is insufficient to fulfil demand
> 2. The energy stored in the buffer (kWh) plus what the electrcity-part can do is insufficient to fulfil demand
> 3. The 'binary' profile dictates that the electricity part should be shut off

f24a2d9 disables the HHP congestion strategy by default, with (2) and (3) done. I'll see what I can do about (1) tomorrow morning.

[Moses Beta LES-436](https://beta-moses.energytransitionmodel.com/testing_grounds/436)

![screen shot 2016-02-29 at 19 44 20](https://cloud.githubusercontent.com/assets/4383/13406709/d9d060a8-df1c-11e5-8f47-fd31ad9004ce.png)

**Comment by ChaelKruip** [comment]
> f24a2d9 disables the HHP congestion strategy by default, with (2) and (3) done. I'll see what I can do about (1) tomorrow morning.

:+1:
