### ISSUE TITLE
It should be possible to run the load calculations for time-intervals

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#802]
Performance is the main reasons why this is a much wanted feature:

Most of the time, people will zoom in on a particular time-interval (say a week) and play with the various strategies and technologies. Calculating the whole year makes this process frustratingly slow. This will become more so if we add load-per-technology and a smarter load calculation (subnet awareness).

## Short-term requirements

For the current sprint, it suffices if the user can use the current year/week selector to choose the period of calculation. 

When you first open the overview page something like this would show:
![etmoses](https://cloud.githubusercontent.com/assets/1303760/13143615/662d80b6-d645-11e5-8c1c-fe3189c8b34c.png)

### Calculating the whole year

If you select the 'whole year' option, the whole year is calculated and the app works as it currently does (zooming in on a week works the same).

### Calculating a week

If you select a specific week, the load is only calculated for that week. All other weeks are not available (yet) until you select them to be the time-interval for calculation.

Business cases are not available until you calculate the whole year.

### Behaviour upon editing

If you edit an aspect of the LES, the load is recalculated for the currently selected time-interval (even if you previously calculated the whole year, the current week is re-calculated if you are in week-mode).

### Initial conditions

Calculating for shorter time-periods raises the question: what is the state of buffers and storage devices? They typically depend on the past so what happened before?

I propose to make the following assumption: EV, P2P and buffers are half-full to begin with. This is assuming the least about the past and leaves flexibility open in two directions.

@jorisberkhout @dennisschoenmakers @AlexanderWirtz do you think this is a good starting point as well?

## Long-term requirements

After discussion with @dennisschoenmakers I've realised that in the future time-intervals of different duration and (a single point, a day, a month) or multiple intervals (a series of days spread over the year etc.) might become relevant to show as well. It would be good if this is kept in mind when re-designing the load calculation. Perhaps the load function could be given an array of start/stop times as an argument?

**Comment by AlexanderWirtz** [comment]
I like it

**Comment by grdw** [comment]
> If you select the 'whole year' option, the whole year is calculated and the app works as it currently does (zooming in on a week works the same).

It shouldn't in my opinion. I think there should be something shown to the user. If we could calculate the *whole topology* in a certain resolution that would save time I would guess (if it's possilble). I think that calculating something on a per node basis might also be a possibility but I can't say for sure due to the questions that are also still present at #828. 

If I get it correctly this is what happens (@antw please hit me if I explain it badly):

A topology:

````
       C
      /
A --B
      \
       D
````

It first sums up all profiles for the technologies at C and D. Than it moves around bits, calculate pieces based on the strategies applied and than it sums up C & D to form B and sums B with no other (because there's no sibling) to form A.

However if that's the case you can't really do it on a per node basis. You could fetch the load from an end-point (like C or D). But not from points higher up the topology (like A and B) without calculating the nodes underneath.

**Comment by ChaelKruip** [comment]
> It shouldn't in my opinion. I think there should be something shown to the user.

Sorry if I misunderstand you here @grdw but what do you mean with 'It'? I agree that there should be something shown to the user (as is currently the case :smile: )

> However if that's the case you can't really do it on a per node basis. 

To clarify: my idea is not to do the load calculation on a 'per node' basis as I agree this will not work. I propose to calculate the load for all nodes but for a limited number of time-steps (one week) optionally.

**Comment by antw** [comment]
> It first sums up all profiles for the technologies at C and D. Than it moves around bits, calculate pieces based on the strategies applied and than it sums up C & D to form B and sums B with no other (because there's no sibling) to form A.

To add to what @ChaelKruip said: this is how early versions of the calculator worked, but it's not really the case anymore. Storage and flexibility put an end to that. :disappointed: 

We have two types of consumption load in the network calculation: "mandatory" and "conditional".

A mandatory load does not depend on anything outside of the endpoint; it describes a load which *must* be placed on the network. There are lots of examples of these, but the simplest is an inflexible base load. This is the energy required by a household and is non-negotiable. If there is not enough excess (from solar PV) the energy will come from the grid, and if it exceeds the capacity of a transformer... so be it. Since these loads are not optional, we could calculate them for each node without having to compute the whole network.

The second type of load – "conditional" – cannot be calculated for just one endpoint. These loads depend on criteria being met at the network level. These include:

* Availability of excess energy (from solar PV)
* Available network (transformer) capacity

As both of those can be affected by loads created by *other* endpoints, it's not possible to fully calculate any node without calculating them all. To use the example from above:

```
        C
       /
A -- B
       \
        D
```

Say `[C]` has a large solar PV array and P2P batteries installed, and `[D]` has a "Household" base-load. If we were to calculate `[C]` on its own, the decision might be to take all that excess solar energy and store it in the batteries. However, if you calculate the whole network, the decision would be to use the energy to satisfy the base load on `[D]` and then store whatever remains in the battery.

Therefore, it is (sadly) not possible to calculate on a per-node basis.

--

> I propose to make the following assumption: EV, P2P and buffers are half-full to begin with. This is assuming the least about the past and leaves flexibility open in two directions.

Ideally we might do a low-resolution calculation of the entire LES – for example, with each frame representing six hours instead of fifteen minutes – and use that as the starting point for the higher-resolution weekly calculations. However that's beyond the scope (and time budget :wink:) of this task.

I think starting half-full makes more sense than starting empty; it will avoid the buffering-induced load spike at the start of the time period.

**Comment by ChaelKruip** [comment]
Thanks for your clarification @antw!
