### ISSUE TITLE
[ Technical ] It should be possible to run the load calculations for time-intervals

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#828]
Part of #802 

----

**Rough draft**

*Current situation:*
Currently the load calculation is done for the full year and all points are stored in cache. Afterwards the content of the nodes are fetched from the cache on a resolution base.

I would suggest to split the cache up into separate parts.

Right now the following folder structure is present:
````
<environment>
│   ├── <les id>
│   │   └── basic
│   │       ├── electricity
│   │       └── gas
````

I'd suggest to change it to:
````
<environment>
│   └── 442
│       └── basic
│           ├── electricity
│           │   ├── 0
│           │   └── 1
│           └── gas
│               ├── 0
│               └── 1
````
Where the numbers are the week numbers of the selection. The week 0 will always contain a low resolution calculation. 

---

**Idea 1: cut the load profiles when needed**

Technically I would think - and this is purely speculative because I'm sort of lost in the woods when looking at the calculation code - that it's giving the [calculation context](https://github.com/quintel/etmoses/blob/master/app/models/calculation/context.rb) an extra option called week number.

Based on the week number you can determine the resolution (week 0 = low resolution, week 1 till 52 is high resolution). Based on the week number you can also determine which set of frames to calculate (in essence `max = (length / 52) * week_number, min = (length / 52) * (week_number - 1)`. 

*What if week 0?*
Week 0 means the resolution is low. This will mean that we can group the load profile values by the max load of a certain time-step (the max of every 96th point if the length of the load profile is 35040) Like we are doing now but after the calculation is finished.

*What if week 1-52?*
Week 1-52 means the resolution is high. This will mean that we simply take the load profile values but cut a range out.  Like we are doing now but after the calculation is finished.

The only thing I'm worrying about this simple setup I have here is - what will happen at the last frame of a week when a strategy is applied? Does that need to be calculated for the whole year like it is now and than cut out in order to be effective? Or some check to see if the week number is not 52 or 0? 

*In short:*
Where I'm leaning towards is an option where the load profiles are pre-cut based on a resolution and a range of frames. However I have no idea if that has bigger implications considering strategies.

---

**Idea 2: Pre-cut the load profiles when uploading them**
What could also be done - considering larger LES's with more than > 100 different profiles is pre-cutting the load profiles. This would mean, that when uploading a load profile there will be 53 versions saved. The first being a low resolution profile (basically generating a csv of the max of every 96th/24th frame). And the other 52 being (`csv.each_slice(52)`) saved as high resolution profiles? 

This would still have the same implications. What to do when a strategy is applied? Will the strategy only apply for 'that week' or should it apply for the whole year and the week be the view of that week. Ofcourse it's the latest but I'm wondering how that will intertwine with this issue.

**Comment by antw** [comment]
> The only thing I'm worrying about this simple setup I have here is - what will happen at the last frame of a week when a strategy is applied? Does that need to be calculated for the whole year like it is now and than cut out in order to be effective? Or some check to see if the week number is not 52 or 0?

I'm not really sure what you mean by this. What significance is there to the last frame of a week when strategies are applied? Sorry if I'm being dense. :worried: 

--

> Idea 2: Pre-cut the load profiles when uploading them

Just so I'm clear: you mean to split the load curves which result from the network calculation into separate files, not the [load profiles](https://beta-moses.energytransitionmodel.com/profiles); is that right?

I think what prohibits this is @ChaelKruip's long-term requirement:

> [...] time-intervals of different duration and (a single point, a day, a month) or multiple intervals (a series of days spread over the year etc.) might become relevant to show as well. It would be good if this is kept in mind when re-designing the load calculation. Perhaps the load function could be given an array of start/stop times as an argument?

Rather than supplying a week number, I think it better to supply a time range which the `Context` can use to determine the frames to be calculated.

```ruby
start  = Time.new(2015, 2, 1)  # Year is not relevant; just ensure
finish = Time.new(2015, 2, 14) # it isn't a leap year!

Calculation::Context.new(..., time: start..finish)
```

... this way, a visitor could select any range of dates and times they like.

This does make for a more complicated cache though. If the user asks for Feb 1 00:00 to Feb 14 09:000, we have to look in the cache to make sure it has high-resolution values for those dates and times. If we do, we can return them straight from the cache; if not, we have to recalculate.

I actually think this is *way* more messy than was originally anticipated. Here's a hypothetical:

* Visitor calculates Feb 1 to Feb 7th.
* Visitor then calculates Feb 8 to Feb 14.

Both of these calculations are started with the assumption that all storage is half-full.

* Visitor now decides to view Feb 1 to Feb 14.

We can't show Feb 1 to Feb 14 from the previous two calculations, because Feb 8 to 14 was based on an assumption about storage which isn't true. Likely we have to recalculate the whole range. Basically, the high-resolution cache becomes useless.

**Comment by grdw** [comment]
> I'm not really sure what you mean by this. What significance is there to the last frame of a week when strategies are applied?

To explain a bit better: What I'm sort of worrying about is if you apply a strategy to the 'full year' - like it's happening now - if you apply that strategy to a week and one week only, will there be any unforseen changes to the load? Let's say, you have some excess load left and it needs to be put at the first day of the week following that week

> ... this way, a visitor could select any range of dates and times they like.

That's better though. Maybe if we use [`file#gets`](http://ruby-doc.org/core-2.3.0/IO.html#M002096) and other IO functionality we could still keep one file per node. This is purely hypothetical but what if we could - when writing the cache do it as follows:

User calculates Jan 1 to Jan 7th:

*Note to self: we obviously need to calculate the whole topology (let's say the topology is A -> B -> C) because of reasons explained in #802.*

We calculate frame 0 until 672. We than store frame 0 until 672 onto each file for every node, so you'll end up with A.tmp, B.tmp and C.tmp. I'm now wondering if it will be faster or slower to not MessagePack the result, but instead write the actual 672 frames as a new line to the files and when you read them, just read the first 672 lines instead of the full file. (If you want to read the next set of frames 673..1344 you would have to set the `lineno` of the file and take the next 672 lines etc.). We could also just MessagePack it - unmessagepack it and than cut out the first 672 lines. But I'm merely wondering if this will be faster or slower with > 100 nodes.

**Comment by ChaelKruip** [comment]
> I actually think this is way more messy than was originally anticipated.

My 2-cents for a first version: why not invalidate cache and re-calculate in all cases except for when the whole year has been calculated. If the user selects a sub-interval, it's going to be very messy indeed (and could even slow down the calculation!) to figure out what part may or may not be needed to be re-calculated. Because sub-intervals will be much smaller than a year in general, the speed-up will be worth it anyways.

**Comment by antw** [comment]
> why not invalidate cache and re-calculate in all cases except for when the whole year has been calculated?

I've come to a similar conclusion: the high-res cache should store either:

* The full year, if it has been calculated; and if not
* Only the values from the most recent calculation (changing which week is shown should invalidate the cache).

This means that if you switch between viewing different nodes, without changing which week is shown, we can pull the values out of the cache instead of having to recalculate.

**Comment by ChaelKruip** [comment]
> This means that if you switch between viewing different nodes, without changing which week is shown, we can pull the values out of the cache instead of having to recalculate.

Also, if you edit the market model or something else unrelated to the load calculation, those cached values can be re-used.

**Comment by grdw** [comment]
> those cached values can be re-used.

Yes they can. Also the business case should not calculate on a per week basis. Just noting, I think we already discussed this. :+1:

**Comment by grdw** [comment]
I'm no able to calculate a week only (with caching disabled) :dancers: 

![screen shot 2016-03-04 at 15 10 45](https://cloud.githubusercontent.com/assets/2676542/13529222/4d8b7c8e-e21b-11e5-8eb7-312efa0988ea.png)

![screen shot 2016-03-04 at 15 07 21](https://cloud.githubusercontent.com/assets/2676542/13529147/dbed7dde-e21a-11e5-95e4-26836f504469.png)

Look at those benchmarks. 

Still need to tweak a lot when it comes to caching - and what happens when selecting a different date. There are also some specs which are booming. Also the business case is something which shouldn't calculate when calculating a range which is not the full year. Still enough to do, but I thought I'd give a little heads up.

**Comment by ChaelKruip** [comment]
> I'm no able to calculate a week only (with caching disabled)

Very cool!

**Comment by grdw** [comment]
I'm hitting a bump at the moment. Whenever I'm selecting a range over a certain number > 8000 Rails throws a 

````
stack level too deep
["/Users/gerard/.rbenv/versions/2.1.2/lib/ruby/2.1.0/forwardable.rb:186"]
````

Which is a bit hard to debug.

**Comment by antw** [comment]
Ruby 2.2 (and newer) will give you a more meaningful error message in the event of a SystemStackError.

**Comment by grdw** [comment]
@antw thanks! I'll try that. I do know it's somewhere in the `PullConsumption` calculation where it freezes up.

**Comment by grdw** [comment]
One question: can I assume all Les's contain a profile which has a max of 35040 values?

**Comment by antw** [comment]
>  can I assume all Les's contain a profile which has a max of 35040 values?

*Maximum?* Yes I think so.

It would be nice to be compatible with profiles of 8760 values (one-per-hour); or even fewer. However, we don't currently support that, and I don't think there are any plans to do so. If it's easier, I think it fair to assume all profiles are *exactly* 35040 values.

**Comment by grdw** [comment]
**Status thusfar:**
I had to rewrite some code because the older version of this produced SystemStackError's and I couldn't really find out why. :disappointed: 

The select box is working now (also for a full year). The next thing, is disabling the business case calculation for week selections (I don't think this is a lot of work), some TLC and re-enabling the caching as discussed. Caching is still necesarry considering the load calculation on a week basis for Lochem:

![screen shot 2016-03-07 at 17 34 09](https://cloud.githubusercontent.com/assets/2676542/13575779/d3c5bfe6-e48a-11e5-97f4-8a8cc92726ae.png)

~8-9 seconds is still a little long.
