### ISSUE TITLE
Add Authorization to the Application

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#85]
Since some *Testing Grounds* can be very sensitive data, it should be prevented that other users could view any of the information associated with these Testing Grounds.

Also: there should be administrative users that can view everything. It should only be @ChaelKruip  to start with.

#### Question:
* Should we use Pundit or CanCan(Can)?

**Comment by ChaelKruip** [comment]
:+1:

**Comment by grdw** [comment]
@dennisschoenmakers do we really need to include a full gem in order to do something basic like  `if @user.admin?` and `if current_user == @testing_ground.user`?

**Comment by antw** [comment]
> do we really need to include a full gem in order to do something basic like if @user.admin? and if current_user == @testing_ground.user?

For the moment, probably not. Maybe we'll want finer-grained control later, and a proper authorisation will be worthwhile then.

**Comment by dennisschoenmakers** [comment]
> @dennisschoenmakers do we really need to include a full gem in order to do something basic like if @user.admin? and if current_user == @testing_ground.user?

Hmmm, I am afraid we will litter the app with these conditions, removing them later will be more painful, and I am getting convinced we will need it in the end anyways. So I tilt towards implementing a good solution straight away.

**Comment by antw** [comment]
> and I am getting convinced we will need it in the end anyways

Fair enough. :+1:

**Comment by antw** [comment]
While we're at it, I'm curious as to the justification for Monban over Devise. I know Devise isn't the new hotness, but it appears more actively maintained, gives us other useful features out-of-the-box (user activation, validation, forms), and will probably integrate easily with Pundit or CanCan. I'm open to persuasion, but at the moment I'm not really getting it.

**Comment by dennisschoenmakers** [comment]
Monban... yes, @grdw: convince us! :smiley:

**Comment by dennisschoenmakers** [comment]
![](http://upload.wikimedia.org/wikipedia/en/0/02/Statler_and_Waldorf.jpg)

**Comment by grdw** [comment]
It's tiny, it's readable, it does the absolute basics of signing in a user (which is what we wanted ;) ). That's the only reason. I find devise big, invasive and horrible to maintain. Besides it's only cool to use devise when you want everything exactly as the devise gem intended to. If you want something custom (which, from experience, is usually the case in a future scenario) than you're screwed.

**Comment by grdw** [comment]
@dennisschoenmakers and I were discussing lots of things considering authorization.

# The Basics
#### Private/public distinction between testing grounds. 

- Private means: only the user can view, edit, update his or her own testing ground. 
- Public means that everybody can show the testing ground but can't edit it. (Please discuss).

#### Topologies must belong to a user aswell, but given the freedom that a user can delete his or her own topology. 

*Only what must happen if a topology is being deleted when multiple users use that same topology?* 
Either all associated testing grounds are removed aswell to not cause any broken testing grounds (data-technically and for users a horrible solution, but totally practical from a software point-of-view). Or the topology is cloned and passed on to the first person - other than the initial creator of the topology - in line.

*Question: can a topology contain private information? Also, who can edit a topology?*

#### Load profiles should have a distinction between public/private
Same question regarding multiple people and deletion, accounts for load profiles as topologies.

# More advanced features / suggestions:
- Invite somebody to show/edit your private testing ground.
- Password protection?
- What if multiple people edit a testing ground/topology/load profile, does the testing ground/topology/load profile belong to multiple people?

To be continued

**Comment by antw** [comment]
### Topologies

> Only what must happen if a topology is being deleted when multiple users use that same topology? 
> Question: can a topology contain private information? Also, who can edit a topology?

My plan for `Topology` was inspired by Google Calendar (and others like it). When you have a recurring event, you may choose to edit the event and save your changes. When you hit "Save", you are presented with this:

![event](https://cloud.githubusercontent.com/assets/4383/7813199/beca7dea-03b0-11e5-9c7a-9505a9f50d43.png)

I thought that we could do something similar with `Topology`. We'd give the user the ability to apply their changes to the *existing* Topology model, or to save their changes *as a copy* so as not to break any testing grounds.

If they update the *existing* Topology we still have more work to do.

* **What happens if their changes will break a testing ground (e.g. renaming a node)?**
  I think we'd have to either enforce that the changes are saved as a new topology, or at least warn the user that their changes will be destructive.

* **What happens if *another user* is using this topology in their testing grounds?**
  We need to keep the original testing ground, create a clone (and apply the changes) for the user making the changes, *and update their testing grounds to use the new copy*.

I had intended for the "edit topology" feature to be part of the "edit testing ground" page, rather than being separate. I'm not 100% sure of that now, but it would be convenient.

> what must happen if a topology is being deleted [...] Or the topology is cloned and passed on to the first person - other than the initial creator of the topology - in line.

I think it best to create a clone *for each person using the topology*. I prefer that to delegating authority to a random user.

> Also, who can edit a topology?

Anyone. But if you're not the owner, I think your changes should be saved to a clone, not the original.

### Load Profiles

> Same question regarding multiple people and deletion, accounts for load profiles as topologies.

Same solution as topologies? Maybe? I'm not sure. :laughing:

If users will be uploading their own profiles, we'll need to tighten up the validation a bit and it would be nice to store a hash of the original file so that we can avoid creating duplicates.

### Advanced features

> Invite somebody to show/edit your private testing ground.
> Password protection?

I like the idea of invites more than password protection. The owner would have the ability to invite a user to the testing ground by e-mail address.

* If they have an account, send them an e-mail informing them that they have access and may edit.
* If they are not registered, send them a polite e-mail suggesting they sign up to view the testing ground.

> What if multiple people edit a testing ground/topology/load profile, does the testing ground/topology/load profile belong to multiple people?

Retain the original owner. I see this working like inviting someone to a private project on GitHub: the project/testing ground belongs to the "owner"; everyone else is a "collaborator".

**Comment by grdw** [comment]
> I thought that we could do something similar with Topology. We'd give the user the ability to apply their changes to the existing Topology model, or to save their changes as a copy so as not to break any testing grounds.

When would someone change an existing topology once it isn't yours? We could also only allow certain 'admin' users to do this, but I'm truly wondering when this will actually happen.
What I'm currently thinking about is: a user can only clone an existing topology or start one from scratch. Editing of topologies is only allowed for your own topologies (private topologies can't be cloned, public ones can (if public/private is needed)). Only admin users can edit all topologies.

Deletion must be done with extreme caution, much like a git repository. I think people must be sort of stirred away from the delete action - it's possible but not recommended. Especially if multiple people are using one user's topology. In my opinion a user must live up to the consequences of a delete action, if it breaks multiple testing grounds - they break for a logical reason.
