### ISSUE TITLE
Seperate accounts for Pro and Beta server

### ISSUE THREAD

**Issue by Sanne512** [quintel/etmoses#856]
Why are the accounts for the Pro and Beta server seperate?

**Comment by ChaelKruip** [comment]
@dennisschoenmakers can you answer this please?

**Comment by dennisschoenmakers** [comment]
> Why are the accounts for the Pro and Beta server seperate?

Each application is currently a fully functioning separate entity with its own list of users et cetera. This can be improved. We would like to make a *single sign on*, where user management of different applications (etmodel and etmoses) is shared, so that the user only has to sign up and log in once.

This new feature is logged in quintel/etcentral#138. Please note this is not scheduled to be implemented (yet) and will take a considerable amount of time to be properly implemented and have all the applications migrated.
