### ISSUE TITLE
Are Investment costs of EV taken into account?

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmoses#859]

**Comment by dennisschoenmakers** [comment]
Including @ChaelKruip

**Comment by ChaelKruip** [comment]
Now that we have a slider in the ETM for the extra costs of EVs, this extra cost should be included in ETMoses as well. The 'investment_cost' attribute can be used for this.

**Comment by grdw** [comment]
This sounds like an additional imported attribute that needs to be taken into account in the business case calculation?

**Comment by ChaelKruip** [comment]
> This sounds like an additional imported attribute that needs to be taken into account in the business case calculation?

Yes. You can use [this gquery](https://github.com/quintel/etsource/blob/master/gqueries/output_elements/output_series/vertical_stacked_bar_170_investment_electric_cars/electric_cars_additional_costs.gql)

**Comment by ChaelKruip** [comment]
What is the status of this @grdw?

**Comment by grdw** [comment]
@antw What would be a nice way to approach this? I'm thinking of creating a separate class called `ElectricVehicleBuilder` where build looks something like:

````ruby
def build
  TechnologyBuilder.build('transport_car_using_electricity', {}).merge(investment_cost: gquery)
end

def gquery
  # do gquery
end
````

**Comment by antw** [comment]
> I'm thinking of creating a separate class called ElectricVehicleBuilder where the build-method looks something like:

I *guess* so, but does that imply that `gquery` is making an API call to ETEngine to get the data? It might become a problem when importing a new scenario if several technologies have to do this.

An alternative would be to have some sort of "manager" class which takes an array of "builders", determines what data the builders need to create their technologies, and then sends as few requests as possible to ETEngine. If there several technologies need to perform a Gquery, *all* the Gqueries can be made with one request. Something like:

```ruby
class Import::Manager
  def initialize(builders, gquery_requestor)
    @builders = builders

    # gquery_requestor is some sort of class which knows the
    # ETEngine host and scenario ID, and how to get the Gqueries.
    @gquery_requestor = gquery_requestor
  end

  def technologies
    @builders.map do |builder|
      builder.build(data, gqueries)
    end
  end

  private

  def gqueries
    gquery_keys = @builders.flat_map(&:gqueries)
    # => ['gquery_one', 'gquery_two', 'gquery_three', ...]

    # Request all gqueries at the same time...
    @gquery_requestor.perform(gquery_keys)
  end
end

class ElectricVehicleBuilder < TechnologyBuilder
  def gqueries
    %w( electric_cars_additional_costs )
  end
end
```

I'm a bit alergic to the idea of defining these sorts of keys in *code* (in this case, references to Gqueries). It seems like they belong with the technology data, alongside the `importable_attributes`.

Instead of adding a separate EV builder class, maybe we can define the necessary Gqueries in the new technology YAML and make the feature more generic, and easier to reuse? `importable_gqueries`? I'm curious if you think that approach is viable.

**Comment by grdw** [comment]
> I'm curious if you think that approach is viable.

Yes. However, there are already a few loose technology builders that do requests through gqueries. I'm looking at Buldings and Households. Maybe we can make the manager as such that it also moves those gquery calls into the `Import::Manager`.

**Comment by ChaelKruip** [comment]
@grdw what is the status of this?

**Comment by grdw** [comment]
Pending

**Comment by ChaelKruip** [comment]
@grdw what is the status of this?

**Comment by antw** [comment]
I think @grdw [has finished this](https://github.com/quintel/etmoses/blob/395787e8f5ebe69b7a2438d440271f4849380a73/db/static/technologies/transport_car_using_electricity.yml#L19).

**Comment by grdw** [comment]
Yes I did 😅
