### ISSUE TITLE
Asset data for gas infrastructure needs to be retrieved and clearly documented

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmoses#870]
Both for the load calculation on the gas-network and the business case and other financial calculations, the following properties for **all relevant types** of pipes for **each relevant** pressure level need to be documented:

* investment cost [EUR]
* cost for digging in low building-density area [EUR/meter]
* cost for digging in medium building-density area [EUR/meter]
* cost for digging in high building-density area [EUR/meter]
* lifetime [year]
* yearly O&M cost [EUR]
* capacity [kW]

For all connecting technologies (GOSs, DRSs, etc.) the following properties need to be documented:

* investment cost [EUR]
* lifetime [year]
* yearly O&M cost [EUR]
* capacity (from low to high pressure) [kW]
* capacity (from high to low pressure) [kW]
* efficiency (from low to high pressure) [%]
* efficiency (from high to low pressure) [%]

Perhaps it would be best to use Markdown format such as [used for this document](https://github.com/quintel/documentation/blob/master/etmoses/average_cost_of_gas_infrastructure.md). Please add as many (links to) sources as possible.

**Comment by Sanne512** [comment]
I'm working on retreiving these numbers in Alliander, but it takes time. My question right now is, in order to prioritize this in relation to retreiving information about heath infrastructure, how necessary is this information to integrate the gas infrastructure in ETMoses? Because when I consider the analogy with electricity these numbers are necessary to create a LES, but the user enters these numbers manually. Is this going to be different for gas? 

Another question: the link to the Markdown format does not work, could you provide me a new link?

**Comment by Sanne512** [comment]
The efficiency from high to low pressure is 100% (0 kW), because it is a passive process without energy losses.

You request the efficiency in kW, but efficiency is usually a percentage. Do you want a percentage for the efficiency or do you want the losses in kW per compressor/booster?

**Comment by ChaelKruip** [comment]
> Do you want a percentage for the efficiency or do you want the losses in kW per compressor/booster?

Percentages please!

**Comment by ChaelKruip** [comment]
> Another question: the link to the Markdown format does not work, could you provide me a new link?

Here you go: [https://github.com/quintel/etmoses/wiki/gas-infrastructure](https://github.com/quintel/etmoses/wiki/gas-infrastructure)

**Comment by ChaelKruip** [comment]
> My question right now is, in order to prioritize this in relation to retreiving information about heath infrastructure, how necessary is this information to integrate the gas infrastructure in ETMoses? 

Right now, the priorities are as follows:

1. Which types of assets per pressure level need to be included (three types of pipes? Two types of 'connectors'?)
2. Numbers for the attributes of those types (see above)
3. Information about the heat network (sprint 3)

**Comment by ChaelKruip** [comment]
@Sanne512 what is the status of this? We are close to the deadline with this.

**Comment by Sanne512** [comment]
In the attachments an Excel file with asset data, the corresponding document for the GitHub (the word file is attached here and I'll e-mail the markdown version to @ChaelKruip ) and a picture to explain the structure of the gas infrastructure. 

I have a few remaining questions: 
- In the report from Enexis provided by Netbeheer Nederland you can find the amount of stations and pipe length of the Netherlands and specified by DSO at page 17, table 8. Which ones do you want to use? The numbers they provide for the stations are not the amount of the stations, but the amount of gas streets. A station can have multiple streets, like a medium voltage area can have mutiple transformators. 
- The connection pipes are neglected, but as shown in the Enexis repport they have a considerable length. What do you want to do with this?

At the moment this is all the information I could gather, that I am allowed to share. As you can see the capacities are missing and the costs cannot be provided in further detail than the total CAPEX and OPEX per type of pipe and station. 

Do you have further questions ? Or need other asset data? 

[Gas infrastructure 20160422 v0.2 word.docx](https://github.com/quintel/etmoses/files/231554/Gas.infrastructure.20160422.v0.2.word.docx)
[Kengetallen gasinfra 20160422 v0.2.xlsx](https://github.com/quintel/etmoses/files/231530/Kengetallen.gasinfra.20160422.v0.2.xlsx)
![topology gas infrastructure 20160422](https://cloud.githubusercontent.com/assets/17741822/14738137/48a3e4e6-0880-11e6-813e-c3873588ccee.PNG)

**Comment by Sanne512** [comment]
One addition to the information mentioned above: I forgot to inlude that the efficiency of the stations is 100% due to the passive manner of transporting the gas.

**Comment by ChaelKruip** [comment]
> the report from Enexis provided by Netbeheer Nederland

Where can I find this report?

> The numbers they provide for the stations are not the amount of the stations, but the amount of gas streets. A station can have multiple streets, like a medium voltage area can have mutiple transformators.

Sorry but I don't understand this comparison @Sanne512. Do you mean that a `station` is the equivalent of  a `transformer`? Is it possible to calculate back from 'gas streets' to 'stations'? Is a 'gas street' a physical street or something else?

> The connection pipes are neglected, but as shown in the Enexis repport they have a considerable length. What do you want to do with this?

Where are they being neglected? In the Excel sheet your provide @Sanne512? Why are they neglected?

> One addition to the information mentioned above: I forgot to inlude that the efficiency of the stations is 100% due to the passive manner of transporting the gas.

What about the efficiency for compression of low-pressure gas to higher pressure? Can you provide a number for the losses as a function of pressure jump?

**Comment by Sanne512** [comment]
@jeroenvdlogt could you sent the report to chael? And answer any further questions during my holiday? 

The gas goes through a straat,  like electricity through a transformer,  and like an electricity station can contain several transformers a gas station can contain several steeds. So a gas street is the actual equipement that transports the gas from a higher to a lower pressure. 
It is not possible to calculate back from streets to stations, but we can provide you the ratio of the stations of the alliander area.

The connection pipes are included in the sheet, but not in the different pressure levels, because they connect the buildings to the 100 mbar netwerk. 

About the efficiency for transporting gas upstream: the contact for these numbers is on holiday now. I'll contact her again when i'm back.

**Comment by ChaelKruip** [comment]
Thanks for the answers @Sanne512! 

The following additional questions have arisen after looking into the Excel sheet provided:

* What are the capacities [kW] of the ‘connectors’?
* Why does a GOS cost only 100 EUR?
* What are the EUR/MW/pressure_jump voor compression?
* What are the losses for compression in %/delta_P or %/delta_P/MW?
* Is a `District-station` the same thing as a `DRS`?

**Comment by Sanne512** [comment]
- the capacities of the connectors are unknown and i'm not able to retreive these numbers from within alliander 
- a gos only costs  €100, because alliander only has to pay for the area and structure around the gos, gts pays for the equipement inside It
- i don't have the numbers for compression (yet); i'm looking into that after my holiday
-  a district-station is the same as a drs

**Comment by jorisberkhout** [comment]
Thanks for the spreadsheets and answers, @Sanne512 . I have tried to translate the data provided into the format ETMoses expects it (see [Kengetallen.gasinfra.20160422.v0.3.xlsx](https://github.com/quintel/etmoses/files/240812/Kengetallen.gasinfra.20160422.v0.3.xlsx), `Input for YAML` sheet.

I have also tried to work out how much gas infrastructure is on average associated with one connection (where I took the national data you provided and `7,195,532` gas connections (based on [Energiecijfers.info](http://energiecijfers.info)). This is a straightforward exercise for the connectors, but gets trickier for the pipes.

I have tried to reconstruct the ratios for the different types of pipe within a specific pressure level on the `Data Liander` sheet from the data on the `Data report` sheet, but go lost at how the types of pipe on the `Data report` sheet map to the types on the `Data Liander` sheet.

What I have done instead is use the ratios @Sanne512 provided on the `Data Liander` sheet and the total length of pipes within a specific pressure level (where I assumed that all TransportLeiding (TL) are at 8 bar, all DistributieLeiding (DL) are at 4 bar and all AansluitLeiding are at 0.1 bar). This results in some typical number specified on the `Input for YAML` sheet. Do my reasoning and calculations make sense to you, @Sanne512 ?

**Comment by ChaelKruip** [comment]
> where I assumed that all TransportLeiding (TL) are at 8 bar

@Sanne512 please note, that the data-sheet states that these lines are at 1--4 bar right @jorisberkhout?

**Comment by jorisberkhout** [comment]
> right @jorisberkhout?

Correct, the referenced datasheet has only one entry for 8 bar pipes.

**Comment by ChaelKruip** [comment]
@Sanne512 can you give an indication when you can validate @jorisberkhout's assumptions and analysis?

**Comment by Sanne512** [comment]
I can do it now!

They way they relate to each other is that TL (transport leidingen) takes place at 8 or 4-1 bar, so the high and middle pressure that are specified on the first sheet. (When you compare this with electricity this is the medium voltage.) And the DL (distributieleidingen) correspond with 100 mbar pressure. (When you compare this with electricity this is the low voltage). The AL (aansluitleidingen) correspond with pipes at 30 mbar, which we have not included in the first sheet, because their influence on the capacity can be neglected. This is the final piece of pipe that connects the pipes under the pavement in the streets at 100 mbar to the houses, so they are part of the connection. 

I included an Excel sheet that shows how the pipes from the Liander data are related to the open Enexis data. I hope that this clarifies it enough. 

[Relation pipes Liander - open data Enexis 20160504.xlsx](https://github.com/quintel/etmoses/files/248823/Relation.pipes.Liander.-.open.data.Enexis.20160504.xlsx)

**Comment by Sanne512** [comment]
As for the compressors/boosters to transport gas from low to high pressure: we don't have any asset data about this, because these aren't part of our assets. At the moment transporting gas from low to high pressure only takes place at the Gasunie infrastructure (8 bar+) or at (green gas) producers, where the producer owns the compressor/booster. So for more information about these assets we advice you to contact them.

**Comment by Sanne512** [comment]
In case you didn't have the report of Enexis (yet) I uploaded it and I updated the table. 

The question about a general rule of thumb for placing new stations has been forwarded to gas experts. 


[Investeren in de toekomst 20160122.pdf](https://github.com/quintel/etmoses/files/256721/Investeren.in.de.toekomst.20160122.pdf)


[Relation pipes Liander - report investeren in de toekomst 20160510.xlsx](https://github.com/quintel/etmoses/files/256720/Relation.pipes.Liander.-.report.investeren.in.de.toekomst.20160510.xlsx)

**Comment by jorisberkhout** [comment]
Thanks for this, @Sanne512 . As discussed, I have combined all data provided by you into one analysis which is attached to this comment.

In this analysis I have determined the number of assets / length of pipes per connection (which is technically part of https://github.com/quintel/etmoses/issues/889). The results are in the table below.

<img width="541" alt="screen shot 2016-05-10 at 17 34 06" src="https://cloud.githubusercontent.com/assets/4669028/15152404/6d1c762c-16d5-11e6-926e-36c7270b015d.png">

A few remarks with this table:
- As discussed, I have combined the Enexis data for 100 and 200 mbar into our 100 mbar category
- I have also combined the Enexis data for 1 and 4 bar into our 4 bar category
- I found that 650 out of the 1050 GOSses owned by GTS are used by the DSO's (the other 400 are used directly by industry and power plants)

[20160510_Kengetallen_gasinfra_v1.0.xlsx](https://github.com/quintel/etmoses/files/257525/20160510_Kengetallen_gasinfra_v1.0.xlsx)

**Comment by jorisberkhout** [comment]
> The question about a general rule of thumb for placing new stations has been forwarded to gas experts.

I have a suggestion on how to solve this. Why don't we determine how many GOS, OS, DRS, HAS and AS you need for your LES based on the table above and the number of connections. To We can then round this number to the first higher integer to avoid having fractions of a connector in the LES.

**Comment by Sanne512** [comment]
> I have a suggestion on how to solve this. Why don't we determine how many GOS, OS, DRS, HAS and AS you need for your LES based on the table above and the number of connections. To We can then round this number to the first higher integer to avoid having fractions of a connector in the LES.<

I really like this idea! I've contacted a few gas experts and they couldn't give a straightforward answer or rule of thumb, because every situation differs a lot. So let's solve it this way.

**Comment by ChaelKruip** [comment]
> I have a suggestion on how to solve this. Why don't we determine how many GOS, OS, DRS, HAS and AS you need for your LES based on the table above and the number of connections.

I like this idea!

> We can then round this number to the first higher integer to avoid having fractions of a connector in the LES.

I think this is not going to work. If you model a street, it would be weird if your LES contains at least one whole GOS, OS, DRS, HAS etc. although you only use a fraction of that asset for that street in reality.

**Comment by ChaelKruip** [comment]
Can this be closed @Sanne512?
