### ISSUE TITLE
I am disabled to edit my own marktmodel

### ISSUE THREAD

**Issue by JeroenvdLogt** [quintel/etmoses#913]
default_marketmodel_TKI-village - Clone #3

This is a private marketmodel of my account jeroen.vande.logt@alliander.com but I am disabled to edit this marketmodel and to set it on public.

**Comment by grdw** [comment]
Do you mean:

- You can't visit the edit page?
- You can't make changes to the market model (as in; it doesn't save the changes)?

Because, I do notice that the edit buttons are missing under the market model in question (id=160).
You can however edit it [here](https://moses.energytransitionmodel.com/market_models/160/edit).

Also the save button is partially hidden:

![screen shot 2016-04-18 at 10 17 32](https://cloud.githubusercontent.com/assets/2676542/14597698/c9aed670-054e-11e6-8a22-c18abc77960c.png)

**Comment by grdw** [comment]
After some further investigation I found that the footer 'spacing' is incorrect. I fixed it and merged it to master. This should make the edit buttons visible again.

**Comment by grdw** [comment]
@JeroenvdLogt can this be closed?

**Comment by grdw** [comment]
Closing, re-open if it re-occurs.
