### ISSUE TITLE
Adding profiles for heat source technologies

### ISSUE THREAD

**Issue by grdw** [quintel/etmoses#991]
This might seem like the simplest solution to me (please correct me if I'm cutting corners here @antw ):

Since heat source technologies are basically a subset of technologies couldn't we keep the current `LoadProfile` functionallity exactly as is. But instead of being able to connect only to the normal technologies, add the functionality to be also able to connect to heat sources?

Maybe we should include a switch in the front-end to switch between "Technologies" and "Heat sources"?

<img width="519" alt="screen shot 2016-05-24 at 12 08 17" src="https://cloud.githubusercontent.com/assets/2676542/15500255/3cbf584a-21a8-11e6-9074-1a50ea306fc9.png">

--

Also the initial profiles for `HeatSources` are coming from the Merit order if I understood correctly, scaling up the 8760 values tot 35040 values by duplicating each row by 4.

**Comment by antw** [comment]
My understanding is that heat sources *are* technologies: they're producers, just like solar panels. I expect they'd have a profile and a (negative) capacity or demand. I'm not even sure that there needs to be a separate HeatSources class because I'm not aware of any distinction between these "sources" and ordinary technologies. Correct me if I'm wrong please!

> Also the initial profiles for HeatSources are coming from the Merit order if I understood correctly

I think @ChaelKruip decided against using Merit for the profiles. Again, correct me if I've misunderstood.

**Comment by grdw** [comment]
> I'm not even sure that there needs to be a separate HeatSources class

This sounds even better 👍. It was just a little bit of separation but it's a bit pointless I guess.
